services:
  sales:
    build: .
    container_name: sales
    restart: unless-stopped
    environment:
      - SERVICE_NAME=sales
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - DEBUG=${DEBUG}
      - AUTOMIGRATE=${AUTOMIGRATE}
