services:
  db:
    image: postgres:15
    container_name: sales_db
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales
    ports:
      - '5440:5432'
    volumes:
      - sales_data:/var/lib/postgresql/data

  nats:
    image: nats:2.10
    container_name: sales_nats
    ports:
      - '4222:4222'

  service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sales_service
    ports:
      - '8006:8000'
      - '9006:9000'
    depends_on:
      - db
      - nats
    environment:
      - AUTOMIGRATE=true
    command: ["./app", "-conf", "config.yaml"]

volumes:
  sales_data:
