// Code generated by ent, DO NOT EDIT.

package cashierlog

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/makesalekz/sales/ent/enum"
)

const (
	// Label holds the string label denoting the cashierlog type in the database.
	Label = "cashier_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCashierID holds the string denoting the cashier_id field in the database.
	FieldCashierID = "cashier_id"
	// FieldShiftID holds the string denoting the shift_id field in the database.
	FieldShiftID = "shift_id"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldEntityType holds the string denoting the entity_type field in the database.
	FieldEntityType = "entity_type"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the cashierlog in the database.
	Table = "cashier_logs"
)

// Columns holds all SQL columns for cashierlog fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldCashierID,
	FieldShiftID,
	FieldAction,
	FieldEntityID,
	FieldEntityType,
	FieldAmount,
	FieldDescription,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultShiftID holds the default value on creation for the "shift_id" field.
	DefaultShiftID int64
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a enum.CashierLogAction) error {
	switch a {
	case "SALE", "RETURN", "SHIFT_OPEN", "SHIFT_CLOSE", "DISCOUNT", "VOID":
		return nil
	default:
		return fmt.Errorf("cashierlog: invalid enum value for action field: %q", a)
	}
}

// OrderOption defines the ordering options for the CashierLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCashierID orders the results by the cashier_id field.
func ByCashierID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCashierID, opts...).ToFunc()
}

// ByShiftID orders the results by the shift_id field.
func ByShiftID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShiftID, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByEntityType orders the results by the entity_type field.
func ByEntityType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityType, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
