// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/makesalekz/sales/internal/biz"
	"github.com/makesalekz/sales/internal/conf"
	"github.com/makesalekz/sales/internal/data"
	"github.com/makesalekz/sales/internal/server"
	"github.com/makesalekz/sales/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	salesRepo := data.NewSalesRepo(dataData)
	conn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	saleCompletedPublisher := data.NewSaleCompletedPublisher(conn, logger)
	cashierLogRepo := data.NewCashierLogRepo(dataData)
	cashierLogger := biz.NewCashierLogger(cashierLogRepo, logger)
	salesUsecase := biz.NewSalesUsecase(logger, salesRepo, saleCompletedPublisher, cashierLogger)
	salesService := service.NewSalesService(salesUsecase)
	shiftsRepo := data.NewShiftsRepo(dataData)
	shiftsUsecase := biz.NewShiftsUsecase(shiftsRepo, cashierLogger)
	shiftServiceImpl := service.NewShiftService(shiftsUsecase)
	returnsRepo := data.NewReturnsRepo(dataData)
	returnCompletedPublisher := data.NewReturnCompletedPublisher(conn, logger)
	returnsUsecase := biz.NewReturnsUsecase(logger, returnsRepo, salesRepo, returnCompletedPublisher, cashierLogger)
	returnsServiceImpl := service.NewReturnsService(returnsUsecase)
	cashierLogUsecase := biz.NewCashierLogUsecase(cashierLogRepo)
	cashierLogServiceImpl := service.NewCashierLogService(cashierLogUsecase)
	syncUsecase := biz.NewSyncUsecase(logger, salesUsecase, returnsUsecase, salesRepo, returnsRepo)
	syncServiceImpl := service.NewSyncService(syncUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, salesService, shiftServiceImpl, returnsServiceImpl, cashierLogServiceImpl, syncServiceImpl)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
