// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CashierLogsColumns holds the columns for the "cashier_logs" table.
	CashierLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "cashier_id", Type: field.TypeInt64},
		{Name: "shift_id", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"SALE", "RETURN", "SHIFT_OPEN", "SHIFT_CLOSE", "DISCOUNT", "VOID"}},
		{Name: "entity_id", Type: field.TypeInt64},
		{Name: "entity_type", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CashierLogsTable holds the schema information for the "cashier_logs" table.
	CashierLogsTable = &schema.Table{
		Name:       "cashier_logs",
		Columns:    CashierLogsColumns,
		PrimaryKey: []*schema.Column{CashierLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "cashierlog_tenant_id_cashier_id",
				Unique:  false,
				Columns: []*schema.Column{CashierLogsColumns[1], CashierLogsColumns[2]},
			},
			{
				Name:    "cashierlog_tenant_id_shift_id",
				Unique:  false,
				Columns: []*schema.Column{CashierLogsColumns[1], CashierLogsColumns[3]},
			},
			{
				Name:    "cashierlog_tenant_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{CashierLogsColumns[1], CashierLogsColumns[9]},
			},
		},
	}
	// SalesColumns holds the columns for the "sales" table.
	SalesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "uuid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "shift_id", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "cashier_id", Type: field.TypeInt64},
		{Name: "total", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "discount_total", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "discount_type", Type: field.TypeEnum, Enums: []string{"NONE", "PERCENTAGE", "FIXED"}, Default: "NONE"},
		{Name: "discount_value", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "payment_type", Type: field.TypeEnum, Enums: []string{"CASH", "CARD", "MIXED"}, Default: "CASH"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"COMPLETED", "RETURNED"}, Default: "COMPLETED"},
	}
	// SalesTable holds the schema information for the "sales" table.
	SalesTable = &schema.Table{
		Name:       "sales",
		Columns:    SalesColumns,
		PrimaryKey: []*schema.Column{SalesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sale_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SalesColumns[4]},
			},
			{
				Name:    "sale_tenant_id_shift_id",
				Unique:  false,
				Columns: []*schema.Column{SalesColumns[4], SalesColumns[5]},
			},
		},
	}
	// SaleItemsColumns holds the columns for the "sale_items" table.
	SaleItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "product_id", Type: field.TypeInt64},
		{Name: "product_name", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "unit_price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "discount", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "total", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "sale_id", Type: field.TypeInt64},
	}
	// SaleItemsTable holds the schema information for the "sale_items" table.
	SaleItemsTable = &schema.Table{
		Name:       "sale_items",
		Columns:    SaleItemsColumns,
		PrimaryKey: []*schema.Column{SaleItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sale_items_sales_items",
				Columns:    []*schema.Column{SaleItemsColumns[9]},
				RefColumns: []*schema.Column{SalesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "saleitem_sale_id",
				Unique:  false,
				Columns: []*schema.Column{SaleItemsColumns[9]},
			},
		},
	}
	// SaleReturnsColumns holds the columns for the "sale_returns" table.
	SaleReturnsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "uuid", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "cashier_id", Type: field.TypeInt64},
		{Name: "total", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "sale_id", Type: field.TypeInt64},
	}
	// SaleReturnsTable holds the schema information for the "sale_returns" table.
	SaleReturnsTable = &schema.Table{
		Name:       "sale_returns",
		Columns:    SaleReturnsColumns,
		PrimaryKey: []*schema.Column{SaleReturnsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sale_returns_sales_returns",
				Columns:    []*schema.Column{SaleReturnsColumns[7]},
				RefColumns: []*schema.Column{SalesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "salereturn_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SaleReturnsColumns[4]},
			},
			{
				Name:    "salereturn_sale_id",
				Unique:  false,
				Columns: []*schema.Column{SaleReturnsColumns[7]},
			},
		},
	}
	// SaleReturnItemsColumns holds the columns for the "sale_return_items" table.
	SaleReturnItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "sale_item_id", Type: field.TypeInt64},
		{Name: "product_id", Type: field.TypeInt64},
		{Name: "quantity", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "unit_price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "total", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "sale_return_id", Type: field.TypeInt64},
	}
	// SaleReturnItemsTable holds the schema information for the "sale_return_items" table.
	SaleReturnItemsTable = &schema.Table{
		Name:       "sale_return_items",
		Columns:    SaleReturnItemsColumns,
		PrimaryKey: []*schema.Column{SaleReturnItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sale_return_items_sale_returns_items",
				Columns:    []*schema.Column{SaleReturnItemsColumns[8]},
				RefColumns: []*schema.Column{SaleReturnsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "salereturnitem_sale_return_id",
				Unique:  false,
				Columns: []*schema.Column{SaleReturnItemsColumns[8]},
			},
			{
				Name:    "salereturnitem_sale_item_id",
				Unique:  false,
				Columns: []*schema.Column{SaleReturnItemsColumns[3]},
			},
		},
	}
	// ShiftsColumns holds the columns for the "shifts" table.
	ShiftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "cashier_id", Type: field.TypeInt64},
		{Name: "store_id", Type: field.TypeInt64, Nullable: true},
		{Name: "opening_amount", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "closing_amount", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "total_sales", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "total_returns", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"OPEN", "CLOSED"}, Default: "OPEN"},
		{Name: "opened_at", Type: field.TypeTime},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true},
	}
	// ShiftsTable holds the schema information for the "shifts" table.
	ShiftsTable = &schema.Table{
		Name:       "shifts",
		Columns:    ShiftsColumns,
		PrimaryKey: []*schema.Column{ShiftsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "shift_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ShiftsColumns[3]},
			},
			{
				Name:    "shift_tenant_id_cashier_id_status",
				Unique:  false,
				Columns: []*schema.Column{ShiftsColumns[3], ShiftsColumns[4], ShiftsColumns[10]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CashierLogsTable,
		SalesTable,
		SaleItemsTable,
		SaleReturnsTable,
		SaleReturnItemsTable,
		ShiftsTable,
	}
)

func init() {
	SaleItemsTable.ForeignKeys[0].RefTable = SalesTable
	SaleReturnsTable.ForeignKeys[0].RefTable = SalesTable
	SaleReturnItemsTable.ForeignKeys[0].RefTable = SaleReturnsTable
}
