// Code generated by ent, DO NOT EDIT.

package sale

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/enum"
	"gitlab.calendaria.team/services/sales/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldUpdatedAt, v))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v string) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldUUID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldTenantID, v))
}

// ShiftID applies equality check predicate on the "shift_id" field. It's identical to ShiftIDEQ.
func ShiftID(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldShiftID, v))
}

// CashierID applies equality check predicate on the "cashier_id" field. It's identical to CashierIDEQ.
func CashierID(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldCashierID, v))
}

// Total applies equality check predicate on the "total" field. It's identical to TotalEQ.
func Total(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldTotal, v))
}

// DiscountTotal applies equality check predicate on the "discount_total" field. It's identical to DiscountTotalEQ.
func DiscountTotal(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldDiscountTotal, v))
}

// DiscountValue applies equality check predicate on the "discount_value" field. It's identical to DiscountValueEQ.
func DiscountValue(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldDiscountValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldUpdatedAt, v))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v string) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v string) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...string) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...string) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v string) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v string) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v string) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v string) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldUUID, v))
}

// UUIDContains applies the Contains predicate on the "uuid" field.
func UUIDContains(v string) predicate.Sale {
	return predicate.Sale(sql.FieldContains(FieldUUID, v))
}

// UUIDHasPrefix applies the HasPrefix predicate on the "uuid" field.
func UUIDHasPrefix(v string) predicate.Sale {
	return predicate.Sale(sql.FieldHasPrefix(FieldUUID, v))
}

// UUIDHasSuffix applies the HasSuffix predicate on the "uuid" field.
func UUIDHasSuffix(v string) predicate.Sale {
	return predicate.Sale(sql.FieldHasSuffix(FieldUUID, v))
}

// UUIDIsNil applies the IsNil predicate on the "uuid" field.
func UUIDIsNil() predicate.Sale {
	return predicate.Sale(sql.FieldIsNull(FieldUUID))
}

// UUIDNotNil applies the NotNil predicate on the "uuid" field.
func UUIDNotNil() predicate.Sale {
	return predicate.Sale(sql.FieldNotNull(FieldUUID))
}

// UUIDEqualFold applies the EqualFold predicate on the "uuid" field.
func UUIDEqualFold(v string) predicate.Sale {
	return predicate.Sale(sql.FieldEqualFold(FieldUUID, v))
}

// UUIDContainsFold applies the ContainsFold predicate on the "uuid" field.
func UUIDContainsFold(v string) predicate.Sale {
	return predicate.Sale(sql.FieldContainsFold(FieldUUID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldTenantID, v))
}

// ShiftIDEQ applies the EQ predicate on the "shift_id" field.
func ShiftIDEQ(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldShiftID, v))
}

// ShiftIDNEQ applies the NEQ predicate on the "shift_id" field.
func ShiftIDNEQ(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldShiftID, v))
}

// ShiftIDIn applies the In predicate on the "shift_id" field.
func ShiftIDIn(vs ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldShiftID, vs...))
}

// ShiftIDNotIn applies the NotIn predicate on the "shift_id" field.
func ShiftIDNotIn(vs ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldShiftID, vs...))
}

// ShiftIDGT applies the GT predicate on the "shift_id" field.
func ShiftIDGT(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldShiftID, v))
}

// ShiftIDGTE applies the GTE predicate on the "shift_id" field.
func ShiftIDGTE(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldShiftID, v))
}

// ShiftIDLT applies the LT predicate on the "shift_id" field.
func ShiftIDLT(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldShiftID, v))
}

// ShiftIDLTE applies the LTE predicate on the "shift_id" field.
func ShiftIDLTE(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldShiftID, v))
}

// ShiftIDIsNil applies the IsNil predicate on the "shift_id" field.
func ShiftIDIsNil() predicate.Sale {
	return predicate.Sale(sql.FieldIsNull(FieldShiftID))
}

// ShiftIDNotNil applies the NotNil predicate on the "shift_id" field.
func ShiftIDNotNil() predicate.Sale {
	return predicate.Sale(sql.FieldNotNull(FieldShiftID))
}

// CashierIDEQ applies the EQ predicate on the "cashier_id" field.
func CashierIDEQ(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldCashierID, v))
}

// CashierIDNEQ applies the NEQ predicate on the "cashier_id" field.
func CashierIDNEQ(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldCashierID, v))
}

// CashierIDIn applies the In predicate on the "cashier_id" field.
func CashierIDIn(vs ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldCashierID, vs...))
}

// CashierIDNotIn applies the NotIn predicate on the "cashier_id" field.
func CashierIDNotIn(vs ...int64) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldCashierID, vs...))
}

// CashierIDGT applies the GT predicate on the "cashier_id" field.
func CashierIDGT(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldCashierID, v))
}

// CashierIDGTE applies the GTE predicate on the "cashier_id" field.
func CashierIDGTE(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldCashierID, v))
}

// CashierIDLT applies the LT predicate on the "cashier_id" field.
func CashierIDLT(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldCashierID, v))
}

// CashierIDLTE applies the LTE predicate on the "cashier_id" field.
func CashierIDLTE(v int64) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldCashierID, v))
}

// TotalEQ applies the EQ predicate on the "total" field.
func TotalEQ(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldTotal, v))
}

// TotalNEQ applies the NEQ predicate on the "total" field.
func TotalNEQ(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldTotal, v))
}

// TotalIn applies the In predicate on the "total" field.
func TotalIn(vs ...decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldTotal, vs...))
}

// TotalNotIn applies the NotIn predicate on the "total" field.
func TotalNotIn(vs ...decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldTotal, vs...))
}

// TotalGT applies the GT predicate on the "total" field.
func TotalGT(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldTotal, v))
}

// TotalGTE applies the GTE predicate on the "total" field.
func TotalGTE(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldTotal, v))
}

// TotalLT applies the LT predicate on the "total" field.
func TotalLT(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldTotal, v))
}

// TotalLTE applies the LTE predicate on the "total" field.
func TotalLTE(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldTotal, v))
}

// DiscountTotalEQ applies the EQ predicate on the "discount_total" field.
func DiscountTotalEQ(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldDiscountTotal, v))
}

// DiscountTotalNEQ applies the NEQ predicate on the "discount_total" field.
func DiscountTotalNEQ(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldDiscountTotal, v))
}

// DiscountTotalIn applies the In predicate on the "discount_total" field.
func DiscountTotalIn(vs ...decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldDiscountTotal, vs...))
}

// DiscountTotalNotIn applies the NotIn predicate on the "discount_total" field.
func DiscountTotalNotIn(vs ...decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldDiscountTotal, vs...))
}

// DiscountTotalGT applies the GT predicate on the "discount_total" field.
func DiscountTotalGT(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldDiscountTotal, v))
}

// DiscountTotalGTE applies the GTE predicate on the "discount_total" field.
func DiscountTotalGTE(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldDiscountTotal, v))
}

// DiscountTotalLT applies the LT predicate on the "discount_total" field.
func DiscountTotalLT(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldDiscountTotal, v))
}

// DiscountTotalLTE applies the LTE predicate on the "discount_total" field.
func DiscountTotalLTE(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldDiscountTotal, v))
}

// DiscountTotalIsNil applies the IsNil predicate on the "discount_total" field.
func DiscountTotalIsNil() predicate.Sale {
	return predicate.Sale(sql.FieldIsNull(FieldDiscountTotal))
}

// DiscountTotalNotNil applies the NotNil predicate on the "discount_total" field.
func DiscountTotalNotNil() predicate.Sale {
	return predicate.Sale(sql.FieldNotNull(FieldDiscountTotal))
}

// DiscountTypeEQ applies the EQ predicate on the "discount_type" field.
func DiscountTypeEQ(v enum.DiscountType) predicate.Sale {
	vc := v
	return predicate.Sale(sql.FieldEQ(FieldDiscountType, vc))
}

// DiscountTypeNEQ applies the NEQ predicate on the "discount_type" field.
func DiscountTypeNEQ(v enum.DiscountType) predicate.Sale {
	vc := v
	return predicate.Sale(sql.FieldNEQ(FieldDiscountType, vc))
}

// DiscountTypeIn applies the In predicate on the "discount_type" field.
func DiscountTypeIn(vs ...enum.DiscountType) predicate.Sale {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sale(sql.FieldIn(FieldDiscountType, v...))
}

// DiscountTypeNotIn applies the NotIn predicate on the "discount_type" field.
func DiscountTypeNotIn(vs ...enum.DiscountType) predicate.Sale {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sale(sql.FieldNotIn(FieldDiscountType, v...))
}

// DiscountValueEQ applies the EQ predicate on the "discount_value" field.
func DiscountValueEQ(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldEQ(FieldDiscountValue, v))
}

// DiscountValueNEQ applies the NEQ predicate on the "discount_value" field.
func DiscountValueNEQ(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldNEQ(FieldDiscountValue, v))
}

// DiscountValueIn applies the In predicate on the "discount_value" field.
func DiscountValueIn(vs ...decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldIn(FieldDiscountValue, vs...))
}

// DiscountValueNotIn applies the NotIn predicate on the "discount_value" field.
func DiscountValueNotIn(vs ...decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldNotIn(FieldDiscountValue, vs...))
}

// DiscountValueGT applies the GT predicate on the "discount_value" field.
func DiscountValueGT(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldGT(FieldDiscountValue, v))
}

// DiscountValueGTE applies the GTE predicate on the "discount_value" field.
func DiscountValueGTE(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldGTE(FieldDiscountValue, v))
}

// DiscountValueLT applies the LT predicate on the "discount_value" field.
func DiscountValueLT(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldLT(FieldDiscountValue, v))
}

// DiscountValueLTE applies the LTE predicate on the "discount_value" field.
func DiscountValueLTE(v decimal.Decimal) predicate.Sale {
	return predicate.Sale(sql.FieldLTE(FieldDiscountValue, v))
}

// DiscountValueIsNil applies the IsNil predicate on the "discount_value" field.
func DiscountValueIsNil() predicate.Sale {
	return predicate.Sale(sql.FieldIsNull(FieldDiscountValue))
}

// DiscountValueNotNil applies the NotNil predicate on the "discount_value" field.
func DiscountValueNotNil() predicate.Sale {
	return predicate.Sale(sql.FieldNotNull(FieldDiscountValue))
}

// PaymentTypeEQ applies the EQ predicate on the "payment_type" field.
func PaymentTypeEQ(v enum.PaymentType) predicate.Sale {
	vc := v
	return predicate.Sale(sql.FieldEQ(FieldPaymentType, vc))
}

// PaymentTypeNEQ applies the NEQ predicate on the "payment_type" field.
func PaymentTypeNEQ(v enum.PaymentType) predicate.Sale {
	vc := v
	return predicate.Sale(sql.FieldNEQ(FieldPaymentType, vc))
}

// PaymentTypeIn applies the In predicate on the "payment_type" field.
func PaymentTypeIn(vs ...enum.PaymentType) predicate.Sale {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sale(sql.FieldIn(FieldPaymentType, v...))
}

// PaymentTypeNotIn applies the NotIn predicate on the "payment_type" field.
func PaymentTypeNotIn(vs ...enum.PaymentType) predicate.Sale {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sale(sql.FieldNotIn(FieldPaymentType, v...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v enum.SaleStatus) predicate.Sale {
	vc := v
	return predicate.Sale(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v enum.SaleStatus) predicate.Sale {
	vc := v
	return predicate.Sale(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...enum.SaleStatus) predicate.Sale {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sale(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...enum.SaleStatus) predicate.Sale {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Sale(sql.FieldNotIn(FieldStatus, v...))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.Sale {
	return predicate.Sale(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.SaleItem) predicate.Sale {
	return predicate.Sale(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReturns applies the HasEdge predicate on the "returns" edge.
func HasReturns() predicate.Sale {
	return predicate.Sale(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ReturnsTable, ReturnsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReturnsWith applies the HasEdge predicate on the "returns" edge with a given conditions (other predicates).
func HasReturnsWith(preds ...predicate.SaleReturn) predicate.Sale {
	return predicate.Sale(func(s *sql.Selector) {
		step := newReturnsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sale) predicate.Sale {
	return predicate.Sale(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sale) predicate.Sale {
	return predicate.Sale(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sale) predicate.Sale {
	return predicate.Sale(sql.NotPredicates(p))
}
