// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/sales/ent/cashierlog"
	"github.com/makesalekz/sales/ent/predicate"
)

// CashierLogUpdate is the builder for updating CashierLog entities.
type CashierLogUpdate struct {
	config
	hooks     []Hook
	mutation  *CashierLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the CashierLogUpdate builder.
func (_u *CashierLogUpdate) Where(ps ...predicate.CashierLog) *CashierLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the CashierLogMutation object of the builder.
func (_u *CashierLogUpdate) Mutation() *CashierLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CashierLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CashierLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CashierLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CashierLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CashierLogUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CashierLogUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CashierLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(cashierlog.Table, cashierlog.Columns, sqlgraph.NewFieldSpec(cashierlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ShiftIDCleared() {
		_spec.ClearField(cashierlog.FieldShiftID, field.TypeInt64)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(cashierlog.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cashierlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CashierLogUpdateOne is the builder for updating a single CashierLog entity.
type CashierLogUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *CashierLogMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Mutation returns the CashierLogMutation object of the builder.
func (_u *CashierLogUpdateOne) Mutation() *CashierLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the CashierLogUpdate builder.
func (_u *CashierLogUpdateOne) Where(ps ...predicate.CashierLog) *CashierLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CashierLogUpdateOne) Select(field string, fields ...string) *CashierLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CashierLog entity.
func (_u *CashierLogUpdateOne) Save(ctx context.Context) (*CashierLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CashierLogUpdateOne) SaveX(ctx context.Context) *CashierLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CashierLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CashierLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *CashierLogUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *CashierLogUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *CashierLogUpdateOne) sqlSave(ctx context.Context) (_node *CashierLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(cashierlog.Table, cashierlog.Columns, sqlgraph.NewFieldSpec(cashierlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CashierLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cashierlog.FieldID)
		for _, f := range fields {
			if !cashierlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cashierlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.ShiftIDCleared() {
		_spec.ClearField(cashierlog.FieldShiftID, field.TypeInt64)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(cashierlog.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &CashierLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cashierlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
