// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/sales/ent/cashierlog"
	"github.com/makesalekz/sales/ent/enum"
)

// CashierLogCreate is the builder for creating a CashierLog entity.
type CashierLogCreate struct {
	config
	mutation *CashierLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *CashierLogCreate) SetTenantID(v int64) *CashierLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCashierID sets the "cashier_id" field.
func (_c *CashierLogCreate) SetCashierID(v int64) *CashierLogCreate {
	_c.mutation.SetCashierID(v)
	return _c
}

// SetShiftID sets the "shift_id" field.
func (_c *CashierLogCreate) SetShiftID(v int64) *CashierLogCreate {
	_c.mutation.SetShiftID(v)
	return _c
}

// SetNillableShiftID sets the "shift_id" field if the given value is not nil.
func (_c *CashierLogCreate) SetNillableShiftID(v *int64) *CashierLogCreate {
	if v != nil {
		_c.SetShiftID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *CashierLogCreate) SetAction(v enum.CashierLogAction) *CashierLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetEntityID sets the "entity_id" field.
func (_c *CashierLogCreate) SetEntityID(v int64) *CashierLogCreate {
	_c.mutation.SetEntityID(v)
	return _c
}

// SetEntityType sets the "entity_type" field.
func (_c *CashierLogCreate) SetEntityType(v string) *CashierLogCreate {
	_c.mutation.SetEntityType(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *CashierLogCreate) SetAmount(v decimal.Decimal) *CashierLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CashierLogCreate) SetDescription(v string) *CashierLogCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CashierLogCreate) SetNillableDescription(v *string) *CashierLogCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CashierLogCreate) SetCreatedAt(v time.Time) *CashierLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CashierLogCreate) SetNillableCreatedAt(v *time.Time) *CashierLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CashierLogCreate) SetID(v int64) *CashierLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CashierLogMutation object of the builder.
func (_c *CashierLogCreate) Mutation() *CashierLogMutation {
	return _c.mutation
}

// Save creates the CashierLog in the database.
func (_c *CashierLogCreate) Save(ctx context.Context) (*CashierLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CashierLogCreate) SaveX(ctx context.Context) *CashierLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CashierLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CashierLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CashierLogCreate) defaults() {
	if _, ok := _c.mutation.ShiftID(); !ok {
		v := cashierlog.DefaultShiftID
		_c.mutation.SetShiftID(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := cashierlog.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := cashierlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CashierLogCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CashierLog.tenant_id"`)}
	}
	if _, ok := _c.mutation.CashierID(); !ok {
		return &ValidationError{Name: "cashier_id", err: errors.New(`ent: missing required field "CashierLog.cashier_id"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "CashierLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := cashierlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "CashierLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "CashierLog.entity_id"`)}
	}
	if _, ok := _c.mutation.EntityType(); !ok {
		return &ValidationError{Name: "entity_type", err: errors.New(`ent: missing required field "CashierLog.entity_type"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "CashierLog.amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CashierLog.created_at"`)}
	}
	return nil
}

func (_c *CashierLogCreate) sqlSave(ctx context.Context) (*CashierLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CashierLogCreate) createSpec() (*CashierLog, *sqlgraph.CreateSpec) {
	var (
		_node = &CashierLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(cashierlog.Table, sqlgraph.NewFieldSpec(cashierlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(cashierlog.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CashierID(); ok {
		_spec.SetField(cashierlog.FieldCashierID, field.TypeInt64, value)
		_node.CashierID = value
	}
	if value, ok := _c.mutation.ShiftID(); ok {
		_spec.SetField(cashierlog.FieldShiftID, field.TypeInt64, value)
		_node.ShiftID = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(cashierlog.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.EntityID(); ok {
		_spec.SetField(cashierlog.FieldEntityID, field.TypeInt64, value)
		_node.EntityID = value
	}
	if value, ok := _c.mutation.EntityType(); ok {
		_spec.SetField(cashierlog.FieldEntityType, field.TypeString, value)
		_node.EntityType = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(cashierlog.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(cashierlog.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(cashierlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CashierLog.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CashierLogUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *CashierLogCreate) OnConflict(opts ...sql.ConflictOption) *CashierLogUpsertOne {
	_c.conflict = opts
	return &CashierLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CashierLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CashierLogCreate) OnConflictColumns(columns ...string) *CashierLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CashierLogUpsertOne{
		create: _c,
	}
}

type (
	// CashierLogUpsertOne is the builder for "upsert"-ing
	//  one CashierLog node.
	CashierLogUpsertOne struct {
		create *CashierLogCreate
	}

	// CashierLogUpsert is the "OnConflict" setter.
	CashierLogUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CashierLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(cashierlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CashierLogUpsertOne) UpdateNewValues() *CashierLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(cashierlog.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(cashierlog.FieldTenantID)
		}
		if _, exists := u.create.mutation.CashierID(); exists {
			s.SetIgnore(cashierlog.FieldCashierID)
		}
		if _, exists := u.create.mutation.ShiftID(); exists {
			s.SetIgnore(cashierlog.FieldShiftID)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(cashierlog.FieldAction)
		}
		if _, exists := u.create.mutation.EntityID(); exists {
			s.SetIgnore(cashierlog.FieldEntityID)
		}
		if _, exists := u.create.mutation.EntityType(); exists {
			s.SetIgnore(cashierlog.FieldEntityType)
		}
		if _, exists := u.create.mutation.Amount(); exists {
			s.SetIgnore(cashierlog.FieldAmount)
		}
		if _, exists := u.create.mutation.Description(); exists {
			s.SetIgnore(cashierlog.FieldDescription)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(cashierlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CashierLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CashierLogUpsertOne) Ignore() *CashierLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CashierLogUpsertOne) DoNothing() *CashierLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CashierLogCreate.OnConflict
// documentation for more info.
func (u *CashierLogUpsertOne) Update(set func(*CashierLogUpsert)) *CashierLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CashierLogUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *CashierLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CashierLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CashierLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CashierLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CashierLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CashierLogCreateBulk is the builder for creating many CashierLog entities in bulk.
type CashierLogCreateBulk struct {
	config
	err      error
	builders []*CashierLogCreate
	conflict []sql.ConflictOption
}

// Save creates the CashierLog entities in the database.
func (_c *CashierLogCreateBulk) Save(ctx context.Context) ([]*CashierLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CashierLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CashierLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CashierLogCreateBulk) SaveX(ctx context.Context) []*CashierLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CashierLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CashierLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CashierLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CashierLogUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *CashierLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *CashierLogUpsertBulk {
	_c.conflict = opts
	return &CashierLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CashierLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CashierLogCreateBulk) OnConflictColumns(columns ...string) *CashierLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CashierLogUpsertBulk{
		create: _c,
	}
}

// CashierLogUpsertBulk is the builder for "upsert"-ing
// a bulk of CashierLog nodes.
type CashierLogUpsertBulk struct {
	create *CashierLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CashierLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(cashierlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CashierLogUpsertBulk) UpdateNewValues() *CashierLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(cashierlog.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(cashierlog.FieldTenantID)
			}
			if _, exists := b.mutation.CashierID(); exists {
				s.SetIgnore(cashierlog.FieldCashierID)
			}
			if _, exists := b.mutation.ShiftID(); exists {
				s.SetIgnore(cashierlog.FieldShiftID)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(cashierlog.FieldAction)
			}
			if _, exists := b.mutation.EntityID(); exists {
				s.SetIgnore(cashierlog.FieldEntityID)
			}
			if _, exists := b.mutation.EntityType(); exists {
				s.SetIgnore(cashierlog.FieldEntityType)
			}
			if _, exists := b.mutation.Amount(); exists {
				s.SetIgnore(cashierlog.FieldAmount)
			}
			if _, exists := b.mutation.Description(); exists {
				s.SetIgnore(cashierlog.FieldDescription)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(cashierlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CashierLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CashierLogUpsertBulk) Ignore() *CashierLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CashierLogUpsertBulk) DoNothing() *CashierLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CashierLogCreateBulk.OnConflict
// documentation for more info.
func (u *CashierLogUpsertBulk) Update(set func(*CashierLogUpsert)) *CashierLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CashierLogUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *CashierLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CashierLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CashierLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CashierLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
