// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/predicate"
	"gitlab.calendaria.team/services/sales/ent/saleitem"
)

// SaleItemUpdate is the builder for updating SaleItem entities.
type SaleItemUpdate struct {
	config
	hooks     []Hook
	mutation  *SaleItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SaleItemUpdate builder.
func (_u *SaleItemUpdate) Where(ps ...predicate.SaleItem) *SaleItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SaleItemUpdate) SetUpdatedAt(v time.Time) *SaleItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *SaleItemUpdate) SetProductName(v string) *SaleItemUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *SaleItemUpdate) SetNillableProductName(v *string) *SaleItemUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *SaleItemUpdate) SetQuantity(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *SaleItemUpdate) SetNillableQuantity(v *decimal.Decimal) *SaleItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *SaleItemUpdate) AddQuantity(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *SaleItemUpdate) SetUnitPrice(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *SaleItemUpdate) SetNillableUnitPrice(v *decimal.Decimal) *SaleItemUpdate {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *SaleItemUpdate) AddUnitPrice(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *SaleItemUpdate) SetDiscount(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.ResetDiscount()
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *SaleItemUpdate) SetNillableDiscount(v *decimal.Decimal) *SaleItemUpdate {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// AddDiscount adds value to the "discount" field.
func (_u *SaleItemUpdate) AddDiscount(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.AddDiscount(v)
	return _u
}

// ClearDiscount clears the value of the "discount" field.
func (_u *SaleItemUpdate) ClearDiscount() *SaleItemUpdate {
	_u.mutation.ClearDiscount()
	return _u
}

// SetTotal sets the "total" field.
func (_u *SaleItemUpdate) SetTotal(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *SaleItemUpdate) SetNillableTotal(v *decimal.Decimal) *SaleItemUpdate {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *SaleItemUpdate) AddTotal(v decimal.Decimal) *SaleItemUpdate {
	_u.mutation.AddTotal(v)
	return _u
}

// Mutation returns the SaleItemMutation object of the builder.
func (_u *SaleItemUpdate) Mutation() *SaleItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SaleItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SaleItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SaleItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SaleItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SaleItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := saleitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SaleItemUpdate) check() error {
	if _u.mutation.SaleCleared() && len(_u.mutation.SaleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SaleItem.sale"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SaleItemUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleItemUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SaleItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(saleitem.Table, saleitem.Columns, sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(saleitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(saleitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(saleitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(saleitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(saleitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(saleitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(saleitem.FieldDiscount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscount(); ok {
		_spec.AddField(saleitem.FieldDiscount, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountCleared() {
		_spec.ClearField(saleitem.FieldDiscount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(saleitem.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(saleitem.FieldTotal, field.TypeFloat64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{saleitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SaleItemUpdateOne is the builder for updating a single SaleItem entity.
type SaleItemUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SaleItemMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SaleItemUpdateOne) SetUpdatedAt(v time.Time) *SaleItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *SaleItemUpdateOne) SetProductName(v string) *SaleItemUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *SaleItemUpdateOne) SetNillableProductName(v *string) *SaleItemUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *SaleItemUpdateOne) SetQuantity(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *SaleItemUpdateOne) SetNillableQuantity(v *decimal.Decimal) *SaleItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *SaleItemUpdateOne) AddQuantity(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetUnitPrice sets the "unit_price" field.
func (_u *SaleItemUpdateOne) SetUnitPrice(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.ResetUnitPrice()
	_u.mutation.SetUnitPrice(v)
	return _u
}

// SetNillableUnitPrice sets the "unit_price" field if the given value is not nil.
func (_u *SaleItemUpdateOne) SetNillableUnitPrice(v *decimal.Decimal) *SaleItemUpdateOne {
	if v != nil {
		_u.SetUnitPrice(*v)
	}
	return _u
}

// AddUnitPrice adds value to the "unit_price" field.
func (_u *SaleItemUpdateOne) AddUnitPrice(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.AddUnitPrice(v)
	return _u
}

// SetDiscount sets the "discount" field.
func (_u *SaleItemUpdateOne) SetDiscount(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.ResetDiscount()
	_u.mutation.SetDiscount(v)
	return _u
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_u *SaleItemUpdateOne) SetNillableDiscount(v *decimal.Decimal) *SaleItemUpdateOne {
	if v != nil {
		_u.SetDiscount(*v)
	}
	return _u
}

// AddDiscount adds value to the "discount" field.
func (_u *SaleItemUpdateOne) AddDiscount(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.AddDiscount(v)
	return _u
}

// ClearDiscount clears the value of the "discount" field.
func (_u *SaleItemUpdateOne) ClearDiscount() *SaleItemUpdateOne {
	_u.mutation.ClearDiscount()
	return _u
}

// SetTotal sets the "total" field.
func (_u *SaleItemUpdateOne) SetTotal(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *SaleItemUpdateOne) SetNillableTotal(v *decimal.Decimal) *SaleItemUpdateOne {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *SaleItemUpdateOne) AddTotal(v decimal.Decimal) *SaleItemUpdateOne {
	_u.mutation.AddTotal(v)
	return _u
}

// Mutation returns the SaleItemMutation object of the builder.
func (_u *SaleItemUpdateOne) Mutation() *SaleItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the SaleItemUpdate builder.
func (_u *SaleItemUpdateOne) Where(ps ...predicate.SaleItem) *SaleItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SaleItemUpdateOne) Select(field string, fields ...string) *SaleItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SaleItem entity.
func (_u *SaleItemUpdateOne) Save(ctx context.Context) (*SaleItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SaleItemUpdateOne) SaveX(ctx context.Context) *SaleItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SaleItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SaleItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SaleItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := saleitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SaleItemUpdateOne) check() error {
	if _u.mutation.SaleCleared() && len(_u.mutation.SaleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SaleItem.sale"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SaleItemUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleItemUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SaleItemUpdateOne) sqlSave(ctx context.Context) (_node *SaleItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(saleitem.Table, saleitem.Columns, sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SaleItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, saleitem.FieldID)
		for _, f := range fields {
			if !saleitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != saleitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(saleitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(saleitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(saleitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(saleitem.FieldQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitPrice(); ok {
		_spec.SetField(saleitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitPrice(); ok {
		_spec.AddField(saleitem.FieldUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Discount(); ok {
		_spec.SetField(saleitem.FieldDiscount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscount(); ok {
		_spec.AddField(saleitem.FieldDiscount, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountCleared() {
		_spec.ClearField(saleitem.FieldDiscount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(saleitem.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(saleitem.FieldTotal, field.TypeFloat64, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SaleItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{saleitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
