// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/sales/ent/enum"
	"github.com/makesalekz/sales/ent/predicate"
	"github.com/makesalekz/sales/ent/sale"
	"github.com/makesalekz/sales/ent/saleitem"
	"github.com/makesalekz/sales/ent/salereturn"
)

// SaleUpdate is the builder for updating Sale entities.
type SaleUpdate struct {
	config
	hooks     []Hook
	mutation  *SaleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SaleUpdate builder.
func (_u *SaleUpdate) Where(ps ...predicate.Sale) *SaleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SaleUpdate) SetUpdatedAt(v time.Time) *SaleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUUID sets the "uuid" field.
func (_u *SaleUpdate) SetUUID(v string) *SaleUpdate {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *SaleUpdate) SetNillableUUID(v *string) *SaleUpdate {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// ClearUUID clears the value of the "uuid" field.
func (_u *SaleUpdate) ClearUUID() *SaleUpdate {
	_u.mutation.ClearUUID()
	return _u
}

// SetShiftID sets the "shift_id" field.
func (_u *SaleUpdate) SetShiftID(v int64) *SaleUpdate {
	_u.mutation.ResetShiftID()
	_u.mutation.SetShiftID(v)
	return _u
}

// SetNillableShiftID sets the "shift_id" field if the given value is not nil.
func (_u *SaleUpdate) SetNillableShiftID(v *int64) *SaleUpdate {
	if v != nil {
		_u.SetShiftID(*v)
	}
	return _u
}

// AddShiftID adds value to the "shift_id" field.
func (_u *SaleUpdate) AddShiftID(v int64) *SaleUpdate {
	_u.mutation.AddShiftID(v)
	return _u
}

// ClearShiftID clears the value of the "shift_id" field.
func (_u *SaleUpdate) ClearShiftID() *SaleUpdate {
	_u.mutation.ClearShiftID()
	return _u
}

// SetTotal sets the "total" field.
func (_u *SaleUpdate) SetTotal(v decimal.Decimal) *SaleUpdate {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *SaleUpdate) SetNillableTotal(v *decimal.Decimal) *SaleUpdate {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *SaleUpdate) AddTotal(v decimal.Decimal) *SaleUpdate {
	_u.mutation.AddTotal(v)
	return _u
}

// SetDiscountTotal sets the "discount_total" field.
func (_u *SaleUpdate) SetDiscountTotal(v decimal.Decimal) *SaleUpdate {
	_u.mutation.ResetDiscountTotal()
	_u.mutation.SetDiscountTotal(v)
	return _u
}

// SetNillableDiscountTotal sets the "discount_total" field if the given value is not nil.
func (_u *SaleUpdate) SetNillableDiscountTotal(v *decimal.Decimal) *SaleUpdate {
	if v != nil {
		_u.SetDiscountTotal(*v)
	}
	return _u
}

// AddDiscountTotal adds value to the "discount_total" field.
func (_u *SaleUpdate) AddDiscountTotal(v decimal.Decimal) *SaleUpdate {
	_u.mutation.AddDiscountTotal(v)
	return _u
}

// ClearDiscountTotal clears the value of the "discount_total" field.
func (_u *SaleUpdate) ClearDiscountTotal() *SaleUpdate {
	_u.mutation.ClearDiscountTotal()
	return _u
}

// SetDiscountType sets the "discount_type" field.
func (_u *SaleUpdate) SetDiscountType(v enum.DiscountType) *SaleUpdate {
	_u.mutation.SetDiscountType(v)
	return _u
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (_u *SaleUpdate) SetNillableDiscountType(v *enum.DiscountType) *SaleUpdate {
	if v != nil {
		_u.SetDiscountType(*v)
	}
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *SaleUpdate) SetDiscountValue(v decimal.Decimal) *SaleUpdate {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *SaleUpdate) SetNillableDiscountValue(v *decimal.Decimal) *SaleUpdate {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *SaleUpdate) AddDiscountValue(v decimal.Decimal) *SaleUpdate {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// ClearDiscountValue clears the value of the "discount_value" field.
func (_u *SaleUpdate) ClearDiscountValue() *SaleUpdate {
	_u.mutation.ClearDiscountValue()
	return _u
}

// SetPaymentType sets the "payment_type" field.
func (_u *SaleUpdate) SetPaymentType(v enum.PaymentType) *SaleUpdate {
	_u.mutation.SetPaymentType(v)
	return _u
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (_u *SaleUpdate) SetNillablePaymentType(v *enum.PaymentType) *SaleUpdate {
	if v != nil {
		_u.SetPaymentType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SaleUpdate) SetStatus(v enum.SaleStatus) *SaleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SaleUpdate) SetNillableStatus(v *enum.SaleStatus) *SaleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddItemIDs adds the "items" edge to the SaleItem entity by IDs.
func (_u *SaleUpdate) AddItemIDs(ids ...int64) *SaleUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the SaleItem entity.
func (_u *SaleUpdate) AddItems(v ...*SaleItem) *SaleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddReturnIDs adds the "returns" edge to the SaleReturn entity by IDs.
func (_u *SaleUpdate) AddReturnIDs(ids ...int64) *SaleUpdate {
	_u.mutation.AddReturnIDs(ids...)
	return _u
}

// AddReturns adds the "returns" edges to the SaleReturn entity.
func (_u *SaleUpdate) AddReturns(v ...*SaleReturn) *SaleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReturnIDs(ids...)
}

// Mutation returns the SaleMutation object of the builder.
func (_u *SaleUpdate) Mutation() *SaleMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the SaleItem entity.
func (_u *SaleUpdate) ClearItems() *SaleUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to SaleItem entities by IDs.
func (_u *SaleUpdate) RemoveItemIDs(ids ...int64) *SaleUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to SaleItem entities.
func (_u *SaleUpdate) RemoveItems(v ...*SaleItem) *SaleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearReturns clears all "returns" edges to the SaleReturn entity.
func (_u *SaleUpdate) ClearReturns() *SaleUpdate {
	_u.mutation.ClearReturns()
	return _u
}

// RemoveReturnIDs removes the "returns" edge to SaleReturn entities by IDs.
func (_u *SaleUpdate) RemoveReturnIDs(ids ...int64) *SaleUpdate {
	_u.mutation.RemoveReturnIDs(ids...)
	return _u
}

// RemoveReturns removes "returns" edges to SaleReturn entities.
func (_u *SaleUpdate) RemoveReturns(v ...*SaleReturn) *SaleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReturnIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SaleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SaleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SaleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SaleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SaleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sale.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SaleUpdate) check() error {
	if v, ok := _u.mutation.DiscountType(); ok {
		if err := sale.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "Sale.discount_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentType(); ok {
		if err := sale.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "Sale.payment_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sale.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sale.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SaleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SaleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sale.Table, sale.Columns, sqlgraph.NewFieldSpec(sale.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sale.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(sale.FieldUUID, field.TypeString, value)
	}
	if _u.mutation.UUIDCleared() {
		_spec.ClearField(sale.FieldUUID, field.TypeString)
	}
	if value, ok := _u.mutation.ShiftID(); ok {
		_spec.SetField(sale.FieldShiftID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedShiftID(); ok {
		_spec.AddField(sale.FieldShiftID, field.TypeInt64, value)
	}
	if _u.mutation.ShiftIDCleared() {
		_spec.ClearField(sale.FieldShiftID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(sale.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(sale.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountTotal(); ok {
		_spec.SetField(sale.FieldDiscountTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountTotal(); ok {
		_spec.AddField(sale.FieldDiscountTotal, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountTotalCleared() {
		_spec.ClearField(sale.FieldDiscountTotal, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DiscountType(); ok {
		_spec.SetField(sale.FieldDiscountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(sale.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(sale.FieldDiscountValue, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountValueCleared() {
		_spec.ClearField(sale.FieldDiscountValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PaymentType(); ok {
		_spec.SetField(sale.FieldPaymentType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sale.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ItemsTable,
			Columns: []string{sale.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ItemsTable,
			Columns: []string{sale.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ItemsTable,
			Columns: []string{sale.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReturnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ReturnsTable,
			Columns: []string{sale.ReturnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReturnsIDs(); len(nodes) > 0 && !_u.mutation.ReturnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ReturnsTable,
			Columns: []string{sale.ReturnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReturnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ReturnsTable,
			Columns: []string{sale.ReturnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sale.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SaleUpdateOne is the builder for updating a single Sale entity.
type SaleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SaleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SaleUpdateOne) SetUpdatedAt(v time.Time) *SaleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUUID sets the "uuid" field.
func (_u *SaleUpdateOne) SetUUID(v string) *SaleUpdateOne {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillableUUID(v *string) *SaleUpdateOne {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// ClearUUID clears the value of the "uuid" field.
func (_u *SaleUpdateOne) ClearUUID() *SaleUpdateOne {
	_u.mutation.ClearUUID()
	return _u
}

// SetShiftID sets the "shift_id" field.
func (_u *SaleUpdateOne) SetShiftID(v int64) *SaleUpdateOne {
	_u.mutation.ResetShiftID()
	_u.mutation.SetShiftID(v)
	return _u
}

// SetNillableShiftID sets the "shift_id" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillableShiftID(v *int64) *SaleUpdateOne {
	if v != nil {
		_u.SetShiftID(*v)
	}
	return _u
}

// AddShiftID adds value to the "shift_id" field.
func (_u *SaleUpdateOne) AddShiftID(v int64) *SaleUpdateOne {
	_u.mutation.AddShiftID(v)
	return _u
}

// ClearShiftID clears the value of the "shift_id" field.
func (_u *SaleUpdateOne) ClearShiftID() *SaleUpdateOne {
	_u.mutation.ClearShiftID()
	return _u
}

// SetTotal sets the "total" field.
func (_u *SaleUpdateOne) SetTotal(v decimal.Decimal) *SaleUpdateOne {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillableTotal(v *decimal.Decimal) *SaleUpdateOne {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *SaleUpdateOne) AddTotal(v decimal.Decimal) *SaleUpdateOne {
	_u.mutation.AddTotal(v)
	return _u
}

// SetDiscountTotal sets the "discount_total" field.
func (_u *SaleUpdateOne) SetDiscountTotal(v decimal.Decimal) *SaleUpdateOne {
	_u.mutation.ResetDiscountTotal()
	_u.mutation.SetDiscountTotal(v)
	return _u
}

// SetNillableDiscountTotal sets the "discount_total" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillableDiscountTotal(v *decimal.Decimal) *SaleUpdateOne {
	if v != nil {
		_u.SetDiscountTotal(*v)
	}
	return _u
}

// AddDiscountTotal adds value to the "discount_total" field.
func (_u *SaleUpdateOne) AddDiscountTotal(v decimal.Decimal) *SaleUpdateOne {
	_u.mutation.AddDiscountTotal(v)
	return _u
}

// ClearDiscountTotal clears the value of the "discount_total" field.
func (_u *SaleUpdateOne) ClearDiscountTotal() *SaleUpdateOne {
	_u.mutation.ClearDiscountTotal()
	return _u
}

// SetDiscountType sets the "discount_type" field.
func (_u *SaleUpdateOne) SetDiscountType(v enum.DiscountType) *SaleUpdateOne {
	_u.mutation.SetDiscountType(v)
	return _u
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillableDiscountType(v *enum.DiscountType) *SaleUpdateOne {
	if v != nil {
		_u.SetDiscountType(*v)
	}
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *SaleUpdateOne) SetDiscountValue(v decimal.Decimal) *SaleUpdateOne {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillableDiscountValue(v *decimal.Decimal) *SaleUpdateOne {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *SaleUpdateOne) AddDiscountValue(v decimal.Decimal) *SaleUpdateOne {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// ClearDiscountValue clears the value of the "discount_value" field.
func (_u *SaleUpdateOne) ClearDiscountValue() *SaleUpdateOne {
	_u.mutation.ClearDiscountValue()
	return _u
}

// SetPaymentType sets the "payment_type" field.
func (_u *SaleUpdateOne) SetPaymentType(v enum.PaymentType) *SaleUpdateOne {
	_u.mutation.SetPaymentType(v)
	return _u
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillablePaymentType(v *enum.PaymentType) *SaleUpdateOne {
	if v != nil {
		_u.SetPaymentType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SaleUpdateOne) SetStatus(v enum.SaleStatus) *SaleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SaleUpdateOne) SetNillableStatus(v *enum.SaleStatus) *SaleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddItemIDs adds the "items" edge to the SaleItem entity by IDs.
func (_u *SaleUpdateOne) AddItemIDs(ids ...int64) *SaleUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the SaleItem entity.
func (_u *SaleUpdateOne) AddItems(v ...*SaleItem) *SaleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddReturnIDs adds the "returns" edge to the SaleReturn entity by IDs.
func (_u *SaleUpdateOne) AddReturnIDs(ids ...int64) *SaleUpdateOne {
	_u.mutation.AddReturnIDs(ids...)
	return _u
}

// AddReturns adds the "returns" edges to the SaleReturn entity.
func (_u *SaleUpdateOne) AddReturns(v ...*SaleReturn) *SaleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReturnIDs(ids...)
}

// Mutation returns the SaleMutation object of the builder.
func (_u *SaleUpdateOne) Mutation() *SaleMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the SaleItem entity.
func (_u *SaleUpdateOne) ClearItems() *SaleUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to SaleItem entities by IDs.
func (_u *SaleUpdateOne) RemoveItemIDs(ids ...int64) *SaleUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to SaleItem entities.
func (_u *SaleUpdateOne) RemoveItems(v ...*SaleItem) *SaleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearReturns clears all "returns" edges to the SaleReturn entity.
func (_u *SaleUpdateOne) ClearReturns() *SaleUpdateOne {
	_u.mutation.ClearReturns()
	return _u
}

// RemoveReturnIDs removes the "returns" edge to SaleReturn entities by IDs.
func (_u *SaleUpdateOne) RemoveReturnIDs(ids ...int64) *SaleUpdateOne {
	_u.mutation.RemoveReturnIDs(ids...)
	return _u
}

// RemoveReturns removes "returns" edges to SaleReturn entities.
func (_u *SaleUpdateOne) RemoveReturns(v ...*SaleReturn) *SaleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReturnIDs(ids...)
}

// Where appends a list predicates to the SaleUpdate builder.
func (_u *SaleUpdateOne) Where(ps ...predicate.Sale) *SaleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SaleUpdateOne) Select(field string, fields ...string) *SaleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sale entity.
func (_u *SaleUpdateOne) Save(ctx context.Context) (*Sale, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SaleUpdateOne) SaveX(ctx context.Context) *Sale {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SaleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SaleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SaleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sale.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SaleUpdateOne) check() error {
	if v, ok := _u.mutation.DiscountType(); ok {
		if err := sale.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "Sale.discount_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentType(); ok {
		if err := sale.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "Sale.payment_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sale.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sale.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SaleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SaleUpdateOne) sqlSave(ctx context.Context) (_node *Sale, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sale.Table, sale.Columns, sqlgraph.NewFieldSpec(sale.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sale.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sale.FieldID)
		for _, f := range fields {
			if !sale.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sale.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sale.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(sale.FieldUUID, field.TypeString, value)
	}
	if _u.mutation.UUIDCleared() {
		_spec.ClearField(sale.FieldUUID, field.TypeString)
	}
	if value, ok := _u.mutation.ShiftID(); ok {
		_spec.SetField(sale.FieldShiftID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedShiftID(); ok {
		_spec.AddField(sale.FieldShiftID, field.TypeInt64, value)
	}
	if _u.mutation.ShiftIDCleared() {
		_spec.ClearField(sale.FieldShiftID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(sale.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(sale.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountTotal(); ok {
		_spec.SetField(sale.FieldDiscountTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountTotal(); ok {
		_spec.AddField(sale.FieldDiscountTotal, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountTotalCleared() {
		_spec.ClearField(sale.FieldDiscountTotal, field.TypeFloat64)
	}
	if value, ok := _u.mutation.DiscountType(); ok {
		_spec.SetField(sale.FieldDiscountType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(sale.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(sale.FieldDiscountValue, field.TypeFloat64, value)
	}
	if _u.mutation.DiscountValueCleared() {
		_spec.ClearField(sale.FieldDiscountValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PaymentType(); ok {
		_spec.SetField(sale.FieldPaymentType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sale.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ItemsTable,
			Columns: []string{sale.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ItemsTable,
			Columns: []string{sale.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ItemsTable,
			Columns: []string{sale.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReturnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ReturnsTable,
			Columns: []string{sale.ReturnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReturnsIDs(); len(nodes) > 0 && !_u.mutation.ReturnsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ReturnsTable,
			Columns: []string{sale.ReturnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReturnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ReturnsTable,
			Columns: []string{sale.ReturnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Sale{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sale.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
