// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/sales/ent/enum"
	"github.com/makesalekz/sales/ent/sale"
	"github.com/makesalekz/sales/ent/saleitem"
	"github.com/makesalekz/sales/ent/salereturn"
)

// SaleCreate is the builder for creating a Sale entity.
type SaleCreate struct {
	config
	mutation *SaleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SaleCreate) SetCreatedAt(v time.Time) *SaleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SaleCreate) SetNillableCreatedAt(v *time.Time) *SaleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SaleCreate) SetUpdatedAt(v time.Time) *SaleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SaleCreate) SetNillableUpdatedAt(v *time.Time) *SaleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUUID sets the "uuid" field.
func (_c *SaleCreate) SetUUID(v string) *SaleCreate {
	_c.mutation.SetUUID(v)
	return _c
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_c *SaleCreate) SetNillableUUID(v *string) *SaleCreate {
	if v != nil {
		_c.SetUUID(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SaleCreate) SetTenantID(v int64) *SaleCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetShiftID sets the "shift_id" field.
func (_c *SaleCreate) SetShiftID(v int64) *SaleCreate {
	_c.mutation.SetShiftID(v)
	return _c
}

// SetNillableShiftID sets the "shift_id" field if the given value is not nil.
func (_c *SaleCreate) SetNillableShiftID(v *int64) *SaleCreate {
	if v != nil {
		_c.SetShiftID(*v)
	}
	return _c
}

// SetCashierID sets the "cashier_id" field.
func (_c *SaleCreate) SetCashierID(v int64) *SaleCreate {
	_c.mutation.SetCashierID(v)
	return _c
}

// SetTotal sets the "total" field.
func (_c *SaleCreate) SetTotal(v decimal.Decimal) *SaleCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// SetDiscountTotal sets the "discount_total" field.
func (_c *SaleCreate) SetDiscountTotal(v decimal.Decimal) *SaleCreate {
	_c.mutation.SetDiscountTotal(v)
	return _c
}

// SetNillableDiscountTotal sets the "discount_total" field if the given value is not nil.
func (_c *SaleCreate) SetNillableDiscountTotal(v *decimal.Decimal) *SaleCreate {
	if v != nil {
		_c.SetDiscountTotal(*v)
	}
	return _c
}

// SetDiscountType sets the "discount_type" field.
func (_c *SaleCreate) SetDiscountType(v enum.DiscountType) *SaleCreate {
	_c.mutation.SetDiscountType(v)
	return _c
}

// SetNillableDiscountType sets the "discount_type" field if the given value is not nil.
func (_c *SaleCreate) SetNillableDiscountType(v *enum.DiscountType) *SaleCreate {
	if v != nil {
		_c.SetDiscountType(*v)
	}
	return _c
}

// SetDiscountValue sets the "discount_value" field.
func (_c *SaleCreate) SetDiscountValue(v decimal.Decimal) *SaleCreate {
	_c.mutation.SetDiscountValue(v)
	return _c
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_c *SaleCreate) SetNillableDiscountValue(v *decimal.Decimal) *SaleCreate {
	if v != nil {
		_c.SetDiscountValue(*v)
	}
	return _c
}

// SetPaymentType sets the "payment_type" field.
func (_c *SaleCreate) SetPaymentType(v enum.PaymentType) *SaleCreate {
	_c.mutation.SetPaymentType(v)
	return _c
}

// SetNillablePaymentType sets the "payment_type" field if the given value is not nil.
func (_c *SaleCreate) SetNillablePaymentType(v *enum.PaymentType) *SaleCreate {
	if v != nil {
		_c.SetPaymentType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SaleCreate) SetStatus(v enum.SaleStatus) *SaleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SaleCreate) SetNillableStatus(v *enum.SaleStatus) *SaleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SaleCreate) SetID(v int64) *SaleCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddItemIDs adds the "items" edge to the SaleItem entity by IDs.
func (_c *SaleCreate) AddItemIDs(ids ...int64) *SaleCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the SaleItem entity.
func (_c *SaleCreate) AddItems(v ...*SaleItem) *SaleCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// AddReturnIDs adds the "returns" edge to the SaleReturn entity by IDs.
func (_c *SaleCreate) AddReturnIDs(ids ...int64) *SaleCreate {
	_c.mutation.AddReturnIDs(ids...)
	return _c
}

// AddReturns adds the "returns" edges to the SaleReturn entity.
func (_c *SaleCreate) AddReturns(v ...*SaleReturn) *SaleCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReturnIDs(ids...)
}

// Mutation returns the SaleMutation object of the builder.
func (_c *SaleCreate) Mutation() *SaleMutation {
	return _c.mutation
}

// Save creates the Sale in the database.
func (_c *SaleCreate) Save(ctx context.Context) (*Sale, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SaleCreate) SaveX(ctx context.Context) *Sale {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SaleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sale.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sale.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ShiftID(); !ok {
		v := sale.DefaultShiftID
		_c.mutation.SetShiftID(v)
	}
	if _, ok := _c.mutation.DiscountType(); !ok {
		v := sale.DefaultDiscountType
		_c.mutation.SetDiscountType(v)
	}
	if _, ok := _c.mutation.PaymentType(); !ok {
		v := sale.DefaultPaymentType
		_c.mutation.SetPaymentType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sale.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SaleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Sale.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Sale.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Sale.tenant_id"`)}
	}
	if _, ok := _c.mutation.CashierID(); !ok {
		return &ValidationError{Name: "cashier_id", err: errors.New(`ent: missing required field "Sale.cashier_id"`)}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "Sale.total"`)}
	}
	if _, ok := _c.mutation.DiscountType(); !ok {
		return &ValidationError{Name: "discount_type", err: errors.New(`ent: missing required field "Sale.discount_type"`)}
	}
	if v, ok := _c.mutation.DiscountType(); ok {
		if err := sale.DiscountTypeValidator(v); err != nil {
			return &ValidationError{Name: "discount_type", err: fmt.Errorf(`ent: validator failed for field "Sale.discount_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentType(); !ok {
		return &ValidationError{Name: "payment_type", err: errors.New(`ent: missing required field "Sale.payment_type"`)}
	}
	if v, ok := _c.mutation.PaymentType(); ok {
		if err := sale.PaymentTypeValidator(v); err != nil {
			return &ValidationError{Name: "payment_type", err: fmt.Errorf(`ent: validator failed for field "Sale.payment_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Sale.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sale.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sale.status": %w`, err)}
		}
	}
	return nil
}

func (_c *SaleCreate) sqlSave(ctx context.Context) (*Sale, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SaleCreate) createSpec() (*Sale, *sqlgraph.CreateSpec) {
	var (
		_node = &Sale{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sale.Table, sqlgraph.NewFieldSpec(sale.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sale.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sale.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UUID(); ok {
		_spec.SetField(sale.FieldUUID, field.TypeString, value)
		_node.UUID = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(sale.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.ShiftID(); ok {
		_spec.SetField(sale.FieldShiftID, field.TypeInt64, value)
		_node.ShiftID = value
	}
	if value, ok := _c.mutation.CashierID(); ok {
		_spec.SetField(sale.FieldCashierID, field.TypeInt64, value)
		_node.CashierID = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(sale.FieldTotal, field.TypeFloat64, value)
		_node.Total = value
	}
	if value, ok := _c.mutation.DiscountTotal(); ok {
		_spec.SetField(sale.FieldDiscountTotal, field.TypeFloat64, value)
		_node.DiscountTotal = value
	}
	if value, ok := _c.mutation.DiscountType(); ok {
		_spec.SetField(sale.FieldDiscountType, field.TypeEnum, value)
		_node.DiscountType = value
	}
	if value, ok := _c.mutation.DiscountValue(); ok {
		_spec.SetField(sale.FieldDiscountValue, field.TypeFloat64, value)
		_node.DiscountValue = value
	}
	if value, ok := _c.mutation.PaymentType(); ok {
		_spec.SetField(sale.FieldPaymentType, field.TypeEnum, value)
		_node.PaymentType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sale.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ItemsTable,
			Columns: []string{sale.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReturnsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sale.ReturnsTable,
			Columns: []string{sale.ReturnsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Sale.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleCreate) OnConflict(opts ...sql.ConflictOption) *SaleUpsertOne {
	_c.conflict = opts
	return &SaleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Sale.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleCreate) OnConflictColumns(columns ...string) *SaleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleUpsertOne{
		create: _c,
	}
}

type (
	// SaleUpsertOne is the builder for "upsert"-ing
	//  one Sale node.
	SaleUpsertOne struct {
		create *SaleCreate
	}

	// SaleUpsert is the "OnConflict" setter.
	SaleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleUpsert) SetUpdatedAt(v time.Time) *SaleUpsert {
	u.Set(sale.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleUpsert) UpdateUpdatedAt() *SaleUpsert {
	u.SetExcluded(sale.FieldUpdatedAt)
	return u
}

// SetUUID sets the "uuid" field.
func (u *SaleUpsert) SetUUID(v string) *SaleUpsert {
	u.Set(sale.FieldUUID, v)
	return u
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *SaleUpsert) UpdateUUID() *SaleUpsert {
	u.SetExcluded(sale.FieldUUID)
	return u
}

// ClearUUID clears the value of the "uuid" field.
func (u *SaleUpsert) ClearUUID() *SaleUpsert {
	u.SetNull(sale.FieldUUID)
	return u
}

// SetShiftID sets the "shift_id" field.
func (u *SaleUpsert) SetShiftID(v int64) *SaleUpsert {
	u.Set(sale.FieldShiftID, v)
	return u
}

// UpdateShiftID sets the "shift_id" field to the value that was provided on create.
func (u *SaleUpsert) UpdateShiftID() *SaleUpsert {
	u.SetExcluded(sale.FieldShiftID)
	return u
}

// AddShiftID adds v to the "shift_id" field.
func (u *SaleUpsert) AddShiftID(v int64) *SaleUpsert {
	u.Add(sale.FieldShiftID, v)
	return u
}

// ClearShiftID clears the value of the "shift_id" field.
func (u *SaleUpsert) ClearShiftID() *SaleUpsert {
	u.SetNull(sale.FieldShiftID)
	return u
}

// SetTotal sets the "total" field.
func (u *SaleUpsert) SetTotal(v decimal.Decimal) *SaleUpsert {
	u.Set(sale.FieldTotal, v)
	return u
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleUpsert) UpdateTotal() *SaleUpsert {
	u.SetExcluded(sale.FieldTotal)
	return u
}

// AddTotal adds v to the "total" field.
func (u *SaleUpsert) AddTotal(v decimal.Decimal) *SaleUpsert {
	u.Add(sale.FieldTotal, v)
	return u
}

// SetDiscountTotal sets the "discount_total" field.
func (u *SaleUpsert) SetDiscountTotal(v decimal.Decimal) *SaleUpsert {
	u.Set(sale.FieldDiscountTotal, v)
	return u
}

// UpdateDiscountTotal sets the "discount_total" field to the value that was provided on create.
func (u *SaleUpsert) UpdateDiscountTotal() *SaleUpsert {
	u.SetExcluded(sale.FieldDiscountTotal)
	return u
}

// AddDiscountTotal adds v to the "discount_total" field.
func (u *SaleUpsert) AddDiscountTotal(v decimal.Decimal) *SaleUpsert {
	u.Add(sale.FieldDiscountTotal, v)
	return u
}

// ClearDiscountTotal clears the value of the "discount_total" field.
func (u *SaleUpsert) ClearDiscountTotal() *SaleUpsert {
	u.SetNull(sale.FieldDiscountTotal)
	return u
}

// SetDiscountType sets the "discount_type" field.
func (u *SaleUpsert) SetDiscountType(v enum.DiscountType) *SaleUpsert {
	u.Set(sale.FieldDiscountType, v)
	return u
}

// UpdateDiscountType sets the "discount_type" field to the value that was provided on create.
func (u *SaleUpsert) UpdateDiscountType() *SaleUpsert {
	u.SetExcluded(sale.FieldDiscountType)
	return u
}

// SetDiscountValue sets the "discount_value" field.
func (u *SaleUpsert) SetDiscountValue(v decimal.Decimal) *SaleUpsert {
	u.Set(sale.FieldDiscountValue, v)
	return u
}

// UpdateDiscountValue sets the "discount_value" field to the value that was provided on create.
func (u *SaleUpsert) UpdateDiscountValue() *SaleUpsert {
	u.SetExcluded(sale.FieldDiscountValue)
	return u
}

// AddDiscountValue adds v to the "discount_value" field.
func (u *SaleUpsert) AddDiscountValue(v decimal.Decimal) *SaleUpsert {
	u.Add(sale.FieldDiscountValue, v)
	return u
}

// ClearDiscountValue clears the value of the "discount_value" field.
func (u *SaleUpsert) ClearDiscountValue() *SaleUpsert {
	u.SetNull(sale.FieldDiscountValue)
	return u
}

// SetPaymentType sets the "payment_type" field.
func (u *SaleUpsert) SetPaymentType(v enum.PaymentType) *SaleUpsert {
	u.Set(sale.FieldPaymentType, v)
	return u
}

// UpdatePaymentType sets the "payment_type" field to the value that was provided on create.
func (u *SaleUpsert) UpdatePaymentType() *SaleUpsert {
	u.SetExcluded(sale.FieldPaymentType)
	return u
}

// SetStatus sets the "status" field.
func (u *SaleUpsert) SetStatus(v enum.SaleStatus) *SaleUpsert {
	u.Set(sale.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SaleUpsert) UpdateStatus() *SaleUpsert {
	u.SetExcluded(sale.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Sale.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sale.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleUpsertOne) UpdateNewValues() *SaleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(sale.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sale.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(sale.FieldTenantID)
		}
		if _, exists := u.create.mutation.CashierID(); exists {
			s.SetIgnore(sale.FieldCashierID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Sale.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SaleUpsertOne) Ignore() *SaleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleUpsertOne) DoNothing() *SaleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleCreate.OnConflict
// documentation for more info.
func (u *SaleUpsertOne) Update(set func(*SaleUpsert)) *SaleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleUpsertOne) SetUpdatedAt(v time.Time) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateUpdatedAt() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUUID sets the "uuid" field.
func (u *SaleUpsertOne) SetUUID(v string) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateUUID() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateUUID()
	})
}

// ClearUUID clears the value of the "uuid" field.
func (u *SaleUpsertOne) ClearUUID() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.ClearUUID()
	})
}

// SetShiftID sets the "shift_id" field.
func (u *SaleUpsertOne) SetShiftID(v int64) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetShiftID(v)
	})
}

// AddShiftID adds v to the "shift_id" field.
func (u *SaleUpsertOne) AddShiftID(v int64) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.AddShiftID(v)
	})
}

// UpdateShiftID sets the "shift_id" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateShiftID() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateShiftID()
	})
}

// ClearShiftID clears the value of the "shift_id" field.
func (u *SaleUpsertOne) ClearShiftID() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.ClearShiftID()
	})
}

// SetTotal sets the "total" field.
func (u *SaleUpsertOne) SetTotal(v decimal.Decimal) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleUpsertOne) AddTotal(v decimal.Decimal) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateTotal() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateTotal()
	})
}

// SetDiscountTotal sets the "discount_total" field.
func (u *SaleUpsertOne) SetDiscountTotal(v decimal.Decimal) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetDiscountTotal(v)
	})
}

// AddDiscountTotal adds v to the "discount_total" field.
func (u *SaleUpsertOne) AddDiscountTotal(v decimal.Decimal) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.AddDiscountTotal(v)
	})
}

// UpdateDiscountTotal sets the "discount_total" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateDiscountTotal() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateDiscountTotal()
	})
}

// ClearDiscountTotal clears the value of the "discount_total" field.
func (u *SaleUpsertOne) ClearDiscountTotal() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.ClearDiscountTotal()
	})
}

// SetDiscountType sets the "discount_type" field.
func (u *SaleUpsertOne) SetDiscountType(v enum.DiscountType) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetDiscountType(v)
	})
}

// UpdateDiscountType sets the "discount_type" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateDiscountType() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateDiscountType()
	})
}

// SetDiscountValue sets the "discount_value" field.
func (u *SaleUpsertOne) SetDiscountValue(v decimal.Decimal) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetDiscountValue(v)
	})
}

// AddDiscountValue adds v to the "discount_value" field.
func (u *SaleUpsertOne) AddDiscountValue(v decimal.Decimal) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.AddDiscountValue(v)
	})
}

// UpdateDiscountValue sets the "discount_value" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateDiscountValue() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateDiscountValue()
	})
}

// ClearDiscountValue clears the value of the "discount_value" field.
func (u *SaleUpsertOne) ClearDiscountValue() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.ClearDiscountValue()
	})
}

// SetPaymentType sets the "payment_type" field.
func (u *SaleUpsertOne) SetPaymentType(v enum.PaymentType) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetPaymentType(v)
	})
}

// UpdatePaymentType sets the "payment_type" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdatePaymentType() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdatePaymentType()
	})
}

// SetStatus sets the "status" field.
func (u *SaleUpsertOne) SetStatus(v enum.SaleStatus) *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SaleUpsertOne) UpdateStatus() *SaleUpsertOne {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *SaleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SaleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SaleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SaleCreateBulk is the builder for creating many Sale entities in bulk.
type SaleCreateBulk struct {
	config
	err      error
	builders []*SaleCreate
	conflict []sql.ConflictOption
}

// Save creates the Sale entities in the database.
func (_c *SaleCreateBulk) Save(ctx context.Context) ([]*Sale, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sale, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SaleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SaleCreateBulk) SaveX(ctx context.Context) []*Sale {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Sale.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleCreateBulk) OnConflict(opts ...sql.ConflictOption) *SaleUpsertBulk {
	_c.conflict = opts
	return &SaleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Sale.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleCreateBulk) OnConflictColumns(columns ...string) *SaleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleUpsertBulk{
		create: _c,
	}
}

// SaleUpsertBulk is the builder for "upsert"-ing
// a bulk of Sale nodes.
type SaleUpsertBulk struct {
	create *SaleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Sale.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(sale.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleUpsertBulk) UpdateNewValues() *SaleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(sale.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sale.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(sale.FieldTenantID)
			}
			if _, exists := b.mutation.CashierID(); exists {
				s.SetIgnore(sale.FieldCashierID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Sale.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SaleUpsertBulk) Ignore() *SaleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleUpsertBulk) DoNothing() *SaleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleCreateBulk.OnConflict
// documentation for more info.
func (u *SaleUpsertBulk) Update(set func(*SaleUpsert)) *SaleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleUpsertBulk) SetUpdatedAt(v time.Time) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateUpdatedAt() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUUID sets the "uuid" field.
func (u *SaleUpsertBulk) SetUUID(v string) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateUUID() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateUUID()
	})
}

// ClearUUID clears the value of the "uuid" field.
func (u *SaleUpsertBulk) ClearUUID() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.ClearUUID()
	})
}

// SetShiftID sets the "shift_id" field.
func (u *SaleUpsertBulk) SetShiftID(v int64) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetShiftID(v)
	})
}

// AddShiftID adds v to the "shift_id" field.
func (u *SaleUpsertBulk) AddShiftID(v int64) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.AddShiftID(v)
	})
}

// UpdateShiftID sets the "shift_id" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateShiftID() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateShiftID()
	})
}

// ClearShiftID clears the value of the "shift_id" field.
func (u *SaleUpsertBulk) ClearShiftID() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.ClearShiftID()
	})
}

// SetTotal sets the "total" field.
func (u *SaleUpsertBulk) SetTotal(v decimal.Decimal) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleUpsertBulk) AddTotal(v decimal.Decimal) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateTotal() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateTotal()
	})
}

// SetDiscountTotal sets the "discount_total" field.
func (u *SaleUpsertBulk) SetDiscountTotal(v decimal.Decimal) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetDiscountTotal(v)
	})
}

// AddDiscountTotal adds v to the "discount_total" field.
func (u *SaleUpsertBulk) AddDiscountTotal(v decimal.Decimal) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.AddDiscountTotal(v)
	})
}

// UpdateDiscountTotal sets the "discount_total" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateDiscountTotal() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateDiscountTotal()
	})
}

// ClearDiscountTotal clears the value of the "discount_total" field.
func (u *SaleUpsertBulk) ClearDiscountTotal() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.ClearDiscountTotal()
	})
}

// SetDiscountType sets the "discount_type" field.
func (u *SaleUpsertBulk) SetDiscountType(v enum.DiscountType) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetDiscountType(v)
	})
}

// UpdateDiscountType sets the "discount_type" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateDiscountType() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateDiscountType()
	})
}

// SetDiscountValue sets the "discount_value" field.
func (u *SaleUpsertBulk) SetDiscountValue(v decimal.Decimal) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetDiscountValue(v)
	})
}

// AddDiscountValue adds v to the "discount_value" field.
func (u *SaleUpsertBulk) AddDiscountValue(v decimal.Decimal) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.AddDiscountValue(v)
	})
}

// UpdateDiscountValue sets the "discount_value" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateDiscountValue() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateDiscountValue()
	})
}

// ClearDiscountValue clears the value of the "discount_value" field.
func (u *SaleUpsertBulk) ClearDiscountValue() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.ClearDiscountValue()
	})
}

// SetPaymentType sets the "payment_type" field.
func (u *SaleUpsertBulk) SetPaymentType(v enum.PaymentType) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetPaymentType(v)
	})
}

// UpdatePaymentType sets the "payment_type" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdatePaymentType() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdatePaymentType()
	})
}

// SetStatus sets the "status" field.
func (u *SaleUpsertBulk) SetStatus(v enum.SaleStatus) *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SaleUpsertBulk) UpdateStatus() *SaleUpsertBulk {
	return u.Update(func(s *SaleUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *SaleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SaleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
