// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/salereturn"
	"gitlab.calendaria.team/services/sales/ent/salereturnitem"
)

// SaleReturnItem is the model entity for the SaleReturnItem schema.
type SaleReturnItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SaleReturnID holds the value of the "sale_return_id" field.
	SaleReturnID int64 `json:"sale_return_id,omitempty"`
	// SaleItemID holds the value of the "sale_item_id" field.
	SaleItemID int64 `json:"sale_item_id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int64 `json:"product_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity decimal.Decimal `json:"quantity,omitempty"`
	// UnitPrice holds the value of the "unit_price" field.
	UnitPrice decimal.Decimal `json:"unit_price,omitempty"`
	// Total holds the value of the "total" field.
	Total decimal.Decimal `json:"total,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SaleReturnItemQuery when eager-loading is set.
	Edges        SaleReturnItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SaleReturnItemEdges holds the relations/edges for other nodes in the graph.
type SaleReturnItemEdges struct {
	// SaleReturn holds the value of the sale_return edge.
	SaleReturn *SaleReturn `json:"sale_return,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SaleReturnOrErr returns the SaleReturn value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SaleReturnItemEdges) SaleReturnOrErr() (*SaleReturn, error) {
	if e.SaleReturn != nil {
		return e.SaleReturn, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: salereturn.Label}
	}
	return nil, &NotLoadedError{edge: "sale_return"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SaleReturnItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case salereturnitem.FieldQuantity, salereturnitem.FieldUnitPrice, salereturnitem.FieldTotal:
			values[i] = new(decimal.Decimal)
		case salereturnitem.FieldID, salereturnitem.FieldSaleReturnID, salereturnitem.FieldSaleItemID, salereturnitem.FieldProductID:
			values[i] = new(sql.NullInt64)
		case salereturnitem.FieldCreatedAt, salereturnitem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SaleReturnItem fields.
func (_m *SaleReturnItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case salereturnitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case salereturnitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case salereturnitem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case salereturnitem.FieldSaleReturnID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sale_return_id", values[i])
			} else if value.Valid {
				_m.SaleReturnID = value.Int64
			}
		case salereturnitem.FieldSaleItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sale_item_id", values[i])
			} else if value.Valid {
				_m.SaleItemID = value.Int64
			}
		case salereturnitem.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				_m.ProductID = value.Int64
			}
		case salereturnitem.FieldQuantity:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value != nil {
				_m.Quantity = *value
			}
		case salereturnitem.FieldUnitPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field unit_price", values[i])
			} else if value != nil {
				_m.UnitPrice = *value
			}
		case salereturnitem.FieldTotal:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value != nil {
				_m.Total = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SaleReturnItem.
// This includes values selected through modifiers, order, etc.
func (_m *SaleReturnItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySaleReturn queries the "sale_return" edge of the SaleReturnItem entity.
func (_m *SaleReturnItem) QuerySaleReturn() *SaleReturnQuery {
	return NewSaleReturnItemClient(_m.config).QuerySaleReturn(_m)
}

// Update returns a builder for updating this SaleReturnItem.
// Note that you need to call SaleReturnItem.Unwrap() before calling this method if this SaleReturnItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SaleReturnItem) Update() *SaleReturnItemUpdateOne {
	return NewSaleReturnItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SaleReturnItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SaleReturnItem) Unwrap() *SaleReturnItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SaleReturnItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SaleReturnItem) String() string {
	var builder strings.Builder
	builder.WriteString("SaleReturnItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sale_return_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SaleReturnID))
	builder.WriteString(", ")
	builder.WriteString("sale_item_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SaleItemID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.UnitPrice))
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(fmt.Sprintf("%v", _m.Total))
	builder.WriteByte(')')
	return builder.String()
}

// SaleReturnItems is a parsable slice of SaleReturnItem.
type SaleReturnItems []*SaleReturnItem
