// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/predicate"
	"gitlab.calendaria.team/services/sales/ent/salereturn"
	"gitlab.calendaria.team/services/sales/ent/salereturnitem"
)

// SaleReturnUpdate is the builder for updating SaleReturn entities.
type SaleReturnUpdate struct {
	config
	hooks     []Hook
	mutation  *SaleReturnMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SaleReturnUpdate builder.
func (_u *SaleReturnUpdate) Where(ps ...predicate.SaleReturn) *SaleReturnUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SaleReturnUpdate) SetUpdatedAt(v time.Time) *SaleReturnUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUUID sets the "uuid" field.
func (_u *SaleReturnUpdate) SetUUID(v string) *SaleReturnUpdate {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *SaleReturnUpdate) SetNillableUUID(v *string) *SaleReturnUpdate {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// ClearUUID clears the value of the "uuid" field.
func (_u *SaleReturnUpdate) ClearUUID() *SaleReturnUpdate {
	_u.mutation.ClearUUID()
	return _u
}

// SetTotal sets the "total" field.
func (_u *SaleReturnUpdate) SetTotal(v decimal.Decimal) *SaleReturnUpdate {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *SaleReturnUpdate) SetNillableTotal(v *decimal.Decimal) *SaleReturnUpdate {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *SaleReturnUpdate) AddTotal(v decimal.Decimal) *SaleReturnUpdate {
	_u.mutation.AddTotal(v)
	return _u
}

// AddItemIDs adds the "items" edge to the SaleReturnItem entity by IDs.
func (_u *SaleReturnUpdate) AddItemIDs(ids ...int64) *SaleReturnUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the SaleReturnItem entity.
func (_u *SaleReturnUpdate) AddItems(v ...*SaleReturnItem) *SaleReturnUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the SaleReturnMutation object of the builder.
func (_u *SaleReturnUpdate) Mutation() *SaleReturnMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the SaleReturnItem entity.
func (_u *SaleReturnUpdate) ClearItems() *SaleReturnUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to SaleReturnItem entities by IDs.
func (_u *SaleReturnUpdate) RemoveItemIDs(ids ...int64) *SaleReturnUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to SaleReturnItem entities.
func (_u *SaleReturnUpdate) RemoveItems(v ...*SaleReturnItem) *SaleReturnUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SaleReturnUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SaleReturnUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SaleReturnUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SaleReturnUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SaleReturnUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salereturn.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SaleReturnUpdate) check() error {
	if _u.mutation.SaleCleared() && len(_u.mutation.SaleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SaleReturn.sale"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SaleReturnUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleReturnUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SaleReturnUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salereturn.Table, salereturn.Columns, sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salereturn.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(salereturn.FieldUUID, field.TypeString, value)
	}
	if _u.mutation.UUIDCleared() {
		_spec.ClearField(salereturn.FieldUUID, field.TypeString)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(salereturn.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(salereturn.FieldTotal, field.TypeFloat64, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salereturn.ItemsTable,
			Columns: []string{salereturn.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salereturn.ItemsTable,
			Columns: []string{salereturn.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salereturn.ItemsTable,
			Columns: []string{salereturn.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salereturn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SaleReturnUpdateOne is the builder for updating a single SaleReturn entity.
type SaleReturnUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SaleReturnMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SaleReturnUpdateOne) SetUpdatedAt(v time.Time) *SaleReturnUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUUID sets the "uuid" field.
func (_u *SaleReturnUpdateOne) SetUUID(v string) *SaleReturnUpdateOne {
	_u.mutation.SetUUID(v)
	return _u
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_u *SaleReturnUpdateOne) SetNillableUUID(v *string) *SaleReturnUpdateOne {
	if v != nil {
		_u.SetUUID(*v)
	}
	return _u
}

// ClearUUID clears the value of the "uuid" field.
func (_u *SaleReturnUpdateOne) ClearUUID() *SaleReturnUpdateOne {
	_u.mutation.ClearUUID()
	return _u
}

// SetTotal sets the "total" field.
func (_u *SaleReturnUpdateOne) SetTotal(v decimal.Decimal) *SaleReturnUpdateOne {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *SaleReturnUpdateOne) SetNillableTotal(v *decimal.Decimal) *SaleReturnUpdateOne {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *SaleReturnUpdateOne) AddTotal(v decimal.Decimal) *SaleReturnUpdateOne {
	_u.mutation.AddTotal(v)
	return _u
}

// AddItemIDs adds the "items" edge to the SaleReturnItem entity by IDs.
func (_u *SaleReturnUpdateOne) AddItemIDs(ids ...int64) *SaleReturnUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the SaleReturnItem entity.
func (_u *SaleReturnUpdateOne) AddItems(v ...*SaleReturnItem) *SaleReturnUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the SaleReturnMutation object of the builder.
func (_u *SaleReturnUpdateOne) Mutation() *SaleReturnMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the SaleReturnItem entity.
func (_u *SaleReturnUpdateOne) ClearItems() *SaleReturnUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to SaleReturnItem entities by IDs.
func (_u *SaleReturnUpdateOne) RemoveItemIDs(ids ...int64) *SaleReturnUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to SaleReturnItem entities.
func (_u *SaleReturnUpdateOne) RemoveItems(v ...*SaleReturnItem) *SaleReturnUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the SaleReturnUpdate builder.
func (_u *SaleReturnUpdateOne) Where(ps ...predicate.SaleReturn) *SaleReturnUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SaleReturnUpdateOne) Select(field string, fields ...string) *SaleReturnUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SaleReturn entity.
func (_u *SaleReturnUpdateOne) Save(ctx context.Context) (*SaleReturn, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SaleReturnUpdateOne) SaveX(ctx context.Context) *SaleReturn {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SaleReturnUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SaleReturnUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SaleReturnUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := salereturn.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SaleReturnUpdateOne) check() error {
	if _u.mutation.SaleCleared() && len(_u.mutation.SaleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SaleReturn.sale"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SaleReturnUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SaleReturnUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SaleReturnUpdateOne) sqlSave(ctx context.Context) (_node *SaleReturn, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(salereturn.Table, salereturn.Columns, sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SaleReturn.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, salereturn.FieldID)
		for _, f := range fields {
			if !salereturn.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != salereturn.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(salereturn.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UUID(); ok {
		_spec.SetField(salereturn.FieldUUID, field.TypeString, value)
	}
	if _u.mutation.UUIDCleared() {
		_spec.ClearField(salereturn.FieldUUID, field.TypeString)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(salereturn.FieldTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(salereturn.FieldTotal, field.TypeFloat64, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salereturn.ItemsTable,
			Columns: []string{salereturn.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salereturn.ItemsTable,
			Columns: []string{salereturn.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salereturn.ItemsTable,
			Columns: []string{salereturn.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SaleReturn{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{salereturn.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
