// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/sales/ent/salereturn"
	"github.com/makesalekz/sales/ent/salereturnitem"
)

// SaleReturnItemCreate is the builder for creating a SaleReturnItem entity.
type SaleReturnItemCreate struct {
	config
	mutation *SaleReturnItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SaleReturnItemCreate) SetCreatedAt(v time.Time) *SaleReturnItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SaleReturnItemCreate) SetNillableCreatedAt(v *time.Time) *SaleReturnItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SaleReturnItemCreate) SetUpdatedAt(v time.Time) *SaleReturnItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SaleReturnItemCreate) SetNillableUpdatedAt(v *time.Time) *SaleReturnItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSaleReturnID sets the "sale_return_id" field.
func (_c *SaleReturnItemCreate) SetSaleReturnID(v int64) *SaleReturnItemCreate {
	_c.mutation.SetSaleReturnID(v)
	return _c
}

// SetSaleItemID sets the "sale_item_id" field.
func (_c *SaleReturnItemCreate) SetSaleItemID(v int64) *SaleReturnItemCreate {
	_c.mutation.SetSaleItemID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *SaleReturnItemCreate) SetProductID(v int64) *SaleReturnItemCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *SaleReturnItemCreate) SetQuantity(v decimal.Decimal) *SaleReturnItemCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *SaleReturnItemCreate) SetUnitPrice(v decimal.Decimal) *SaleReturnItemCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetTotal sets the "total" field.
func (_c *SaleReturnItemCreate) SetTotal(v decimal.Decimal) *SaleReturnItemCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SaleReturnItemCreate) SetID(v int64) *SaleReturnItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSaleReturn sets the "sale_return" edge to the SaleReturn entity.
func (_c *SaleReturnItemCreate) SetSaleReturn(v *SaleReturn) *SaleReturnItemCreate {
	return _c.SetSaleReturnID(v.ID)
}

// Mutation returns the SaleReturnItemMutation object of the builder.
func (_c *SaleReturnItemCreate) Mutation() *SaleReturnItemMutation {
	return _c.mutation
}

// Save creates the SaleReturnItem in the database.
func (_c *SaleReturnItemCreate) Save(ctx context.Context) (*SaleReturnItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SaleReturnItemCreate) SaveX(ctx context.Context) *SaleReturnItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleReturnItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleReturnItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SaleReturnItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := salereturnitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := salereturnitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SaleReturnItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SaleReturnItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SaleReturnItem.updated_at"`)}
	}
	if _, ok := _c.mutation.SaleReturnID(); !ok {
		return &ValidationError{Name: "sale_return_id", err: errors.New(`ent: missing required field "SaleReturnItem.sale_return_id"`)}
	}
	if _, ok := _c.mutation.SaleItemID(); !ok {
		return &ValidationError{Name: "sale_item_id", err: errors.New(`ent: missing required field "SaleReturnItem.sale_item_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "SaleReturnItem.product_id"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "SaleReturnItem.quantity"`)}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "SaleReturnItem.unit_price"`)}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "SaleReturnItem.total"`)}
	}
	if len(_c.mutation.SaleReturnIDs()) == 0 {
		return &ValidationError{Name: "sale_return", err: errors.New(`ent: missing required edge "SaleReturnItem.sale_return"`)}
	}
	return nil
}

func (_c *SaleReturnItemCreate) sqlSave(ctx context.Context) (*SaleReturnItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SaleReturnItemCreate) createSpec() (*SaleReturnItem, *sqlgraph.CreateSpec) {
	var (
		_node = &SaleReturnItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(salereturnitem.Table, sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(salereturnitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(salereturnitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SaleItemID(); ok {
		_spec.SetField(salereturnitem.FieldSaleItemID, field.TypeInt64, value)
		_node.SaleItemID = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(salereturnitem.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(salereturnitem.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(salereturnitem.FieldUnitPrice, field.TypeFloat64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(salereturnitem.FieldTotal, field.TypeFloat64, value)
		_node.Total = value
	}
	if nodes := _c.mutation.SaleReturnIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   salereturnitem.SaleReturnTable,
			Columns: []string{salereturnitem.SaleReturnColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SaleReturnID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleReturnItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleReturnItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleReturnItemCreate) OnConflict(opts ...sql.ConflictOption) *SaleReturnItemUpsertOne {
	_c.conflict = opts
	return &SaleReturnItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleReturnItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleReturnItemCreate) OnConflictColumns(columns ...string) *SaleReturnItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleReturnItemUpsertOne{
		create: _c,
	}
}

type (
	// SaleReturnItemUpsertOne is the builder for "upsert"-ing
	//  one SaleReturnItem node.
	SaleReturnItemUpsertOne struct {
		create *SaleReturnItemCreate
	}

	// SaleReturnItemUpsert is the "OnConflict" setter.
	SaleReturnItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleReturnItemUpsert) SetUpdatedAt(v time.Time) *SaleReturnItemUpsert {
	u.Set(salereturnitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleReturnItemUpsert) UpdateUpdatedAt() *SaleReturnItemUpsert {
	u.SetExcluded(salereturnitem.FieldUpdatedAt)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *SaleReturnItemUpsert) SetQuantity(v decimal.Decimal) *SaleReturnItemUpsert {
	u.Set(salereturnitem.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *SaleReturnItemUpsert) UpdateQuantity() *SaleReturnItemUpsert {
	u.SetExcluded(salereturnitem.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *SaleReturnItemUpsert) AddQuantity(v decimal.Decimal) *SaleReturnItemUpsert {
	u.Add(salereturnitem.FieldQuantity, v)
	return u
}

// SetUnitPrice sets the "unit_price" field.
func (u *SaleReturnItemUpsert) SetUnitPrice(v decimal.Decimal) *SaleReturnItemUpsert {
	u.Set(salereturnitem.FieldUnitPrice, v)
	return u
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *SaleReturnItemUpsert) UpdateUnitPrice() *SaleReturnItemUpsert {
	u.SetExcluded(salereturnitem.FieldUnitPrice)
	return u
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *SaleReturnItemUpsert) AddUnitPrice(v decimal.Decimal) *SaleReturnItemUpsert {
	u.Add(salereturnitem.FieldUnitPrice, v)
	return u
}

// SetTotal sets the "total" field.
func (u *SaleReturnItemUpsert) SetTotal(v decimal.Decimal) *SaleReturnItemUpsert {
	u.Set(salereturnitem.FieldTotal, v)
	return u
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleReturnItemUpsert) UpdateTotal() *SaleReturnItemUpsert {
	u.SetExcluded(salereturnitem.FieldTotal)
	return u
}

// AddTotal adds v to the "total" field.
func (u *SaleReturnItemUpsert) AddTotal(v decimal.Decimal) *SaleReturnItemUpsert {
	u.Add(salereturnitem.FieldTotal, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SaleReturnItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(salereturnitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleReturnItemUpsertOne) UpdateNewValues() *SaleReturnItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(salereturnitem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(salereturnitem.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.SaleReturnID(); exists {
			s.SetIgnore(salereturnitem.FieldSaleReturnID)
		}
		if _, exists := u.create.mutation.SaleItemID(); exists {
			s.SetIgnore(salereturnitem.FieldSaleItemID)
		}
		if _, exists := u.create.mutation.ProductID(); exists {
			s.SetIgnore(salereturnitem.FieldProductID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleReturnItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SaleReturnItemUpsertOne) Ignore() *SaleReturnItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleReturnItemUpsertOne) DoNothing() *SaleReturnItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleReturnItemCreate.OnConflict
// documentation for more info.
func (u *SaleReturnItemUpsertOne) Update(set func(*SaleReturnItemUpsert)) *SaleReturnItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleReturnItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleReturnItemUpsertOne) SetUpdatedAt(v time.Time) *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleReturnItemUpsertOne) UpdateUpdatedAt() *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetQuantity sets the "quantity" field.
func (u *SaleReturnItemUpsertOne) SetQuantity(v decimal.Decimal) *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *SaleReturnItemUpsertOne) AddQuantity(v decimal.Decimal) *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *SaleReturnItemUpsertOne) UpdateQuantity() *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *SaleReturnItemUpsertOne) SetUnitPrice(v decimal.Decimal) *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *SaleReturnItemUpsertOne) AddUnitPrice(v decimal.Decimal) *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *SaleReturnItemUpsertOne) UpdateUnitPrice() *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetTotal sets the "total" field.
func (u *SaleReturnItemUpsertOne) SetTotal(v decimal.Decimal) *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleReturnItemUpsertOne) AddTotal(v decimal.Decimal) *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleReturnItemUpsertOne) UpdateTotal() *SaleReturnItemUpsertOne {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateTotal()
	})
}

// Exec executes the query.
func (u *SaleReturnItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleReturnItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleReturnItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SaleReturnItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SaleReturnItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SaleReturnItemCreateBulk is the builder for creating many SaleReturnItem entities in bulk.
type SaleReturnItemCreateBulk struct {
	config
	err      error
	builders []*SaleReturnItemCreate
	conflict []sql.ConflictOption
}

// Save creates the SaleReturnItem entities in the database.
func (_c *SaleReturnItemCreateBulk) Save(ctx context.Context) ([]*SaleReturnItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SaleReturnItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SaleReturnItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SaleReturnItemCreateBulk) SaveX(ctx context.Context) []*SaleReturnItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleReturnItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleReturnItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleReturnItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleReturnItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleReturnItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *SaleReturnItemUpsertBulk {
	_c.conflict = opts
	return &SaleReturnItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleReturnItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleReturnItemCreateBulk) OnConflictColumns(columns ...string) *SaleReturnItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleReturnItemUpsertBulk{
		create: _c,
	}
}

// SaleReturnItemUpsertBulk is the builder for "upsert"-ing
// a bulk of SaleReturnItem nodes.
type SaleReturnItemUpsertBulk struct {
	create *SaleReturnItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SaleReturnItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(salereturnitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleReturnItemUpsertBulk) UpdateNewValues() *SaleReturnItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(salereturnitem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(salereturnitem.FieldCreatedAt)
			}
			if _, exists := b.mutation.SaleReturnID(); exists {
				s.SetIgnore(salereturnitem.FieldSaleReturnID)
			}
			if _, exists := b.mutation.SaleItemID(); exists {
				s.SetIgnore(salereturnitem.FieldSaleItemID)
			}
			if _, exists := b.mutation.ProductID(); exists {
				s.SetIgnore(salereturnitem.FieldProductID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleReturnItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SaleReturnItemUpsertBulk) Ignore() *SaleReturnItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleReturnItemUpsertBulk) DoNothing() *SaleReturnItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleReturnItemCreateBulk.OnConflict
// documentation for more info.
func (u *SaleReturnItemUpsertBulk) Update(set func(*SaleReturnItemUpsert)) *SaleReturnItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleReturnItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleReturnItemUpsertBulk) SetUpdatedAt(v time.Time) *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleReturnItemUpsertBulk) UpdateUpdatedAt() *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetQuantity sets the "quantity" field.
func (u *SaleReturnItemUpsertBulk) SetQuantity(v decimal.Decimal) *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *SaleReturnItemUpsertBulk) AddQuantity(v decimal.Decimal) *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *SaleReturnItemUpsertBulk) UpdateQuantity() *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *SaleReturnItemUpsertBulk) SetUnitPrice(v decimal.Decimal) *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *SaleReturnItemUpsertBulk) AddUnitPrice(v decimal.Decimal) *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *SaleReturnItemUpsertBulk) UpdateUnitPrice() *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetTotal sets the "total" field.
func (u *SaleReturnItemUpsertBulk) SetTotal(v decimal.Decimal) *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleReturnItemUpsertBulk) AddTotal(v decimal.Decimal) *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleReturnItemUpsertBulk) UpdateTotal() *SaleReturnItemUpsertBulk {
	return u.Update(func(s *SaleReturnItemUpsert) {
		s.UpdateTotal()
	})
}

// Exec executes the query.
func (u *SaleReturnItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SaleReturnItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleReturnItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleReturnItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
