// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/sales/ent/sale"
	"github.com/makesalekz/sales/ent/saleitem"
)

// SaleItemCreate is the builder for creating a SaleItem entity.
type SaleItemCreate struct {
	config
	mutation *SaleItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SaleItemCreate) SetCreatedAt(v time.Time) *SaleItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SaleItemCreate) SetNillableCreatedAt(v *time.Time) *SaleItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SaleItemCreate) SetUpdatedAt(v time.Time) *SaleItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SaleItemCreate) SetNillableUpdatedAt(v *time.Time) *SaleItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSaleID sets the "sale_id" field.
func (_c *SaleItemCreate) SetSaleID(v int64) *SaleItemCreate {
	_c.mutation.SetSaleID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *SaleItemCreate) SetProductID(v int64) *SaleItemCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *SaleItemCreate) SetProductName(v string) *SaleItemCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *SaleItemCreate) SetQuantity(v decimal.Decimal) *SaleItemCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetUnitPrice sets the "unit_price" field.
func (_c *SaleItemCreate) SetUnitPrice(v decimal.Decimal) *SaleItemCreate {
	_c.mutation.SetUnitPrice(v)
	return _c
}

// SetDiscount sets the "discount" field.
func (_c *SaleItemCreate) SetDiscount(v decimal.Decimal) *SaleItemCreate {
	_c.mutation.SetDiscount(v)
	return _c
}

// SetNillableDiscount sets the "discount" field if the given value is not nil.
func (_c *SaleItemCreate) SetNillableDiscount(v *decimal.Decimal) *SaleItemCreate {
	if v != nil {
		_c.SetDiscount(*v)
	}
	return _c
}

// SetTotal sets the "total" field.
func (_c *SaleItemCreate) SetTotal(v decimal.Decimal) *SaleItemCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SaleItemCreate) SetID(v int64) *SaleItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSale sets the "sale" edge to the Sale entity.
func (_c *SaleItemCreate) SetSale(v *Sale) *SaleItemCreate {
	return _c.SetSaleID(v.ID)
}

// Mutation returns the SaleItemMutation object of the builder.
func (_c *SaleItemCreate) Mutation() *SaleItemMutation {
	return _c.mutation
}

// Save creates the SaleItem in the database.
func (_c *SaleItemCreate) Save(ctx context.Context) (*SaleItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SaleItemCreate) SaveX(ctx context.Context) *SaleItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SaleItemCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := saleitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := saleitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SaleItemCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SaleItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SaleItem.updated_at"`)}
	}
	if _, ok := _c.mutation.SaleID(); !ok {
		return &ValidationError{Name: "sale_id", err: errors.New(`ent: missing required field "SaleItem.sale_id"`)}
	}
	if _, ok := _c.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "SaleItem.product_id"`)}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "SaleItem.product_name"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "SaleItem.quantity"`)}
	}
	if _, ok := _c.mutation.UnitPrice(); !ok {
		return &ValidationError{Name: "unit_price", err: errors.New(`ent: missing required field "SaleItem.unit_price"`)}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "SaleItem.total"`)}
	}
	if len(_c.mutation.SaleIDs()) == 0 {
		return &ValidationError{Name: "sale", err: errors.New(`ent: missing required edge "SaleItem.sale"`)}
	}
	return nil
}

func (_c *SaleItemCreate) sqlSave(ctx context.Context) (*SaleItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SaleItemCreate) createSpec() (*SaleItem, *sqlgraph.CreateSpec) {
	var (
		_node = &SaleItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(saleitem.Table, sqlgraph.NewFieldSpec(saleitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(saleitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(saleitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProductID(); ok {
		_spec.SetField(saleitem.FieldProductID, field.TypeInt64, value)
		_node.ProductID = value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(saleitem.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(saleitem.FieldQuantity, field.TypeFloat64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.UnitPrice(); ok {
		_spec.SetField(saleitem.FieldUnitPrice, field.TypeFloat64, value)
		_node.UnitPrice = value
	}
	if value, ok := _c.mutation.Discount(); ok {
		_spec.SetField(saleitem.FieldDiscount, field.TypeFloat64, value)
		_node.Discount = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(saleitem.FieldTotal, field.TypeFloat64, value)
		_node.Total = value
	}
	if nodes := _c.mutation.SaleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   saleitem.SaleTable,
			Columns: []string{saleitem.SaleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sale.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SaleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleItem.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleItemCreate) OnConflict(opts ...sql.ConflictOption) *SaleItemUpsertOne {
	_c.conflict = opts
	return &SaleItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleItemCreate) OnConflictColumns(columns ...string) *SaleItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleItemUpsertOne{
		create: _c,
	}
}

type (
	// SaleItemUpsertOne is the builder for "upsert"-ing
	//  one SaleItem node.
	SaleItemUpsertOne struct {
		create *SaleItemCreate
	}

	// SaleItemUpsert is the "OnConflict" setter.
	SaleItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleItemUpsert) SetUpdatedAt(v time.Time) *SaleItemUpsert {
	u.Set(saleitem.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleItemUpsert) UpdateUpdatedAt() *SaleItemUpsert {
	u.SetExcluded(saleitem.FieldUpdatedAt)
	return u
}

// SetProductName sets the "product_name" field.
func (u *SaleItemUpsert) SetProductName(v string) *SaleItemUpsert {
	u.Set(saleitem.FieldProductName, v)
	return u
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *SaleItemUpsert) UpdateProductName() *SaleItemUpsert {
	u.SetExcluded(saleitem.FieldProductName)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *SaleItemUpsert) SetQuantity(v decimal.Decimal) *SaleItemUpsert {
	u.Set(saleitem.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *SaleItemUpsert) UpdateQuantity() *SaleItemUpsert {
	u.SetExcluded(saleitem.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *SaleItemUpsert) AddQuantity(v decimal.Decimal) *SaleItemUpsert {
	u.Add(saleitem.FieldQuantity, v)
	return u
}

// SetUnitPrice sets the "unit_price" field.
func (u *SaleItemUpsert) SetUnitPrice(v decimal.Decimal) *SaleItemUpsert {
	u.Set(saleitem.FieldUnitPrice, v)
	return u
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *SaleItemUpsert) UpdateUnitPrice() *SaleItemUpsert {
	u.SetExcluded(saleitem.FieldUnitPrice)
	return u
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *SaleItemUpsert) AddUnitPrice(v decimal.Decimal) *SaleItemUpsert {
	u.Add(saleitem.FieldUnitPrice, v)
	return u
}

// SetDiscount sets the "discount" field.
func (u *SaleItemUpsert) SetDiscount(v decimal.Decimal) *SaleItemUpsert {
	u.Set(saleitem.FieldDiscount, v)
	return u
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *SaleItemUpsert) UpdateDiscount() *SaleItemUpsert {
	u.SetExcluded(saleitem.FieldDiscount)
	return u
}

// AddDiscount adds v to the "discount" field.
func (u *SaleItemUpsert) AddDiscount(v decimal.Decimal) *SaleItemUpsert {
	u.Add(saleitem.FieldDiscount, v)
	return u
}

// ClearDiscount clears the value of the "discount" field.
func (u *SaleItemUpsert) ClearDiscount() *SaleItemUpsert {
	u.SetNull(saleitem.FieldDiscount)
	return u
}

// SetTotal sets the "total" field.
func (u *SaleItemUpsert) SetTotal(v decimal.Decimal) *SaleItemUpsert {
	u.Set(saleitem.FieldTotal, v)
	return u
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleItemUpsert) UpdateTotal() *SaleItemUpsert {
	u.SetExcluded(saleitem.FieldTotal)
	return u
}

// AddTotal adds v to the "total" field.
func (u *SaleItemUpsert) AddTotal(v decimal.Decimal) *SaleItemUpsert {
	u.Add(saleitem.FieldTotal, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SaleItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(saleitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleItemUpsertOne) UpdateNewValues() *SaleItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(saleitem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(saleitem.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.SaleID(); exists {
			s.SetIgnore(saleitem.FieldSaleID)
		}
		if _, exists := u.create.mutation.ProductID(); exists {
			s.SetIgnore(saleitem.FieldProductID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SaleItemUpsertOne) Ignore() *SaleItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleItemUpsertOne) DoNothing() *SaleItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleItemCreate.OnConflict
// documentation for more info.
func (u *SaleItemUpsertOne) Update(set func(*SaleItemUpsert)) *SaleItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleItemUpsertOne) SetUpdatedAt(v time.Time) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleItemUpsertOne) UpdateUpdatedAt() *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductName sets the "product_name" field.
func (u *SaleItemUpsertOne) SetProductName(v string) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *SaleItemUpsertOne) UpdateProductName() *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateProductName()
	})
}

// SetQuantity sets the "quantity" field.
func (u *SaleItemUpsertOne) SetQuantity(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *SaleItemUpsertOne) AddQuantity(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *SaleItemUpsertOne) UpdateQuantity() *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *SaleItemUpsertOne) SetUnitPrice(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *SaleItemUpsertOne) AddUnitPrice(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *SaleItemUpsertOne) UpdateUnitPrice() *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetDiscount sets the "discount" field.
func (u *SaleItemUpsertOne) SetDiscount(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetDiscount(v)
	})
}

// AddDiscount adds v to the "discount" field.
func (u *SaleItemUpsertOne) AddDiscount(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddDiscount(v)
	})
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *SaleItemUpsertOne) UpdateDiscount() *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateDiscount()
	})
}

// ClearDiscount clears the value of the "discount" field.
func (u *SaleItemUpsertOne) ClearDiscount() *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.ClearDiscount()
	})
}

// SetTotal sets the "total" field.
func (u *SaleItemUpsertOne) SetTotal(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleItemUpsertOne) AddTotal(v decimal.Decimal) *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleItemUpsertOne) UpdateTotal() *SaleItemUpsertOne {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateTotal()
	})
}

// Exec executes the query.
func (u *SaleItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SaleItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SaleItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SaleItemCreateBulk is the builder for creating many SaleItem entities in bulk.
type SaleItemCreateBulk struct {
	config
	err      error
	builders []*SaleItemCreate
	conflict []sql.ConflictOption
}

// Save creates the SaleItem entities in the database.
func (_c *SaleItemCreateBulk) Save(ctx context.Context) ([]*SaleItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SaleItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SaleItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SaleItemCreateBulk) SaveX(ctx context.Context) []*SaleItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleItemUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *SaleItemUpsertBulk {
	_c.conflict = opts
	return &SaleItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleItemCreateBulk) OnConflictColumns(columns ...string) *SaleItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleItemUpsertBulk{
		create: _c,
	}
}

// SaleItemUpsertBulk is the builder for "upsert"-ing
// a bulk of SaleItem nodes.
type SaleItemUpsertBulk struct {
	create *SaleItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SaleItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(saleitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleItemUpsertBulk) UpdateNewValues() *SaleItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(saleitem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(saleitem.FieldCreatedAt)
			}
			if _, exists := b.mutation.SaleID(); exists {
				s.SetIgnore(saleitem.FieldSaleID)
			}
			if _, exists := b.mutation.ProductID(); exists {
				s.SetIgnore(saleitem.FieldProductID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SaleItemUpsertBulk) Ignore() *SaleItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleItemUpsertBulk) DoNothing() *SaleItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleItemCreateBulk.OnConflict
// documentation for more info.
func (u *SaleItemUpsertBulk) Update(set func(*SaleItemUpsert)) *SaleItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleItemUpsertBulk) SetUpdatedAt(v time.Time) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleItemUpsertBulk) UpdateUpdatedAt() *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductName sets the "product_name" field.
func (u *SaleItemUpsertBulk) SetProductName(v string) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *SaleItemUpsertBulk) UpdateProductName() *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateProductName()
	})
}

// SetQuantity sets the "quantity" field.
func (u *SaleItemUpsertBulk) SetQuantity(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *SaleItemUpsertBulk) AddQuantity(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *SaleItemUpsertBulk) UpdateQuantity() *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateQuantity()
	})
}

// SetUnitPrice sets the "unit_price" field.
func (u *SaleItemUpsertBulk) SetUnitPrice(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetUnitPrice(v)
	})
}

// AddUnitPrice adds v to the "unit_price" field.
func (u *SaleItemUpsertBulk) AddUnitPrice(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddUnitPrice(v)
	})
}

// UpdateUnitPrice sets the "unit_price" field to the value that was provided on create.
func (u *SaleItemUpsertBulk) UpdateUnitPrice() *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateUnitPrice()
	})
}

// SetDiscount sets the "discount" field.
func (u *SaleItemUpsertBulk) SetDiscount(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetDiscount(v)
	})
}

// AddDiscount adds v to the "discount" field.
func (u *SaleItemUpsertBulk) AddDiscount(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddDiscount(v)
	})
}

// UpdateDiscount sets the "discount" field to the value that was provided on create.
func (u *SaleItemUpsertBulk) UpdateDiscount() *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateDiscount()
	})
}

// ClearDiscount clears the value of the "discount" field.
func (u *SaleItemUpsertBulk) ClearDiscount() *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.ClearDiscount()
	})
}

// SetTotal sets the "total" field.
func (u *SaleItemUpsertBulk) SetTotal(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleItemUpsertBulk) AddTotal(v decimal.Decimal) *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleItemUpsertBulk) UpdateTotal() *SaleItemUpsertBulk {
	return u.Update(func(s *SaleItemUpsert) {
		s.UpdateTotal()
	})
}

// Exec executes the query.
func (u *SaleItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SaleItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
