// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/sale"
	"gitlab.calendaria.team/services/sales/ent/salereturn"
)

// SaleReturn is the model entity for the SaleReturn schema.
type SaleReturn struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID *string `json:"uuid,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// SaleID holds the value of the "sale_id" field.
	SaleID int64 `json:"sale_id,omitempty"`
	// CashierID holds the value of the "cashier_id" field.
	CashierID int64 `json:"cashier_id,omitempty"`
	// Total holds the value of the "total" field.
	Total decimal.Decimal `json:"total,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SaleReturnQuery when eager-loading is set.
	Edges        SaleReturnEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SaleReturnEdges holds the relations/edges for other nodes in the graph.
type SaleReturnEdges struct {
	// Sale holds the value of the sale edge.
	Sale *Sale `json:"sale,omitempty"`
	// Items holds the value of the items edge.
	Items []*SaleReturnItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SaleOrErr returns the Sale value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SaleReturnEdges) SaleOrErr() (*Sale, error) {
	if e.Sale != nil {
		return e.Sale, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sale.Label}
	}
	return nil, &NotLoadedError{edge: "sale"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e SaleReturnEdges) ItemsOrErr() ([]*SaleReturnItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SaleReturn) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case salereturn.FieldTotal:
			values[i] = new(decimal.Decimal)
		case salereturn.FieldID, salereturn.FieldTenantID, salereturn.FieldSaleID, salereturn.FieldCashierID:
			values[i] = new(sql.NullInt64)
		case salereturn.FieldUUID:
			values[i] = new(sql.NullString)
		case salereturn.FieldCreatedAt, salereturn.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SaleReturn fields.
func (_m *SaleReturn) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case salereturn.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case salereturn.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case salereturn.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case salereturn.FieldUUID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value.Valid {
				_m.UUID = new(string)
				*_m.UUID = value.String
			}
		case salereturn.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.Int64
			}
		case salereturn.FieldSaleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sale_id", values[i])
			} else if value.Valid {
				_m.SaleID = value.Int64
			}
		case salereturn.FieldCashierID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cashier_id", values[i])
			} else if value.Valid {
				_m.CashierID = value.Int64
			}
		case salereturn.FieldTotal:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field total", values[i])
			} else if value != nil {
				_m.Total = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SaleReturn.
// This includes values selected through modifiers, order, etc.
func (_m *SaleReturn) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySale queries the "sale" edge of the SaleReturn entity.
func (_m *SaleReturn) QuerySale() *SaleQuery {
	return NewSaleReturnClient(_m.config).QuerySale(_m)
}

// QueryItems queries the "items" edge of the SaleReturn entity.
func (_m *SaleReturn) QueryItems() *SaleReturnItemQuery {
	return NewSaleReturnClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this SaleReturn.
// Note that you need to call SaleReturn.Unwrap() before calling this method if this SaleReturn
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SaleReturn) Update() *SaleReturnUpdateOne {
	return NewSaleReturnClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SaleReturn entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SaleReturn) Unwrap() *SaleReturn {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SaleReturn is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SaleReturn) String() string {
	var builder strings.Builder
	builder.WriteString("SaleReturn(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UUID; v != nil {
		builder.WriteString("uuid=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("sale_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SaleID))
	builder.WriteString(", ")
	builder.WriteString("cashier_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CashierID))
	builder.WriteString(", ")
	builder.WriteString("total=")
	builder.WriteString(fmt.Sprintf("%v", _m.Total))
	builder.WriteByte(')')
	return builder.String()
}

// SaleReturns is a parsable slice of SaleReturn.
type SaleReturns []*SaleReturn
