// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/sale"
	"gitlab.calendaria.team/services/sales/ent/salereturn"
	"gitlab.calendaria.team/services/sales/ent/salereturnitem"
)

// SaleReturnCreate is the builder for creating a SaleReturn entity.
type SaleReturnCreate struct {
	config
	mutation *SaleReturnMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SaleReturnCreate) SetCreatedAt(v time.Time) *SaleReturnCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SaleReturnCreate) SetNillableCreatedAt(v *time.Time) *SaleReturnCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SaleReturnCreate) SetUpdatedAt(v time.Time) *SaleReturnCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SaleReturnCreate) SetNillableUpdatedAt(v *time.Time) *SaleReturnCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUUID sets the "uuid" field.
func (_c *SaleReturnCreate) SetUUID(v string) *SaleReturnCreate {
	_c.mutation.SetUUID(v)
	return _c
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (_c *SaleReturnCreate) SetNillableUUID(v *string) *SaleReturnCreate {
	if v != nil {
		_c.SetUUID(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SaleReturnCreate) SetTenantID(v int64) *SaleReturnCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetSaleID sets the "sale_id" field.
func (_c *SaleReturnCreate) SetSaleID(v int64) *SaleReturnCreate {
	_c.mutation.SetSaleID(v)
	return _c
}

// SetCashierID sets the "cashier_id" field.
func (_c *SaleReturnCreate) SetCashierID(v int64) *SaleReturnCreate {
	_c.mutation.SetCashierID(v)
	return _c
}

// SetTotal sets the "total" field.
func (_c *SaleReturnCreate) SetTotal(v decimal.Decimal) *SaleReturnCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SaleReturnCreate) SetID(v int64) *SaleReturnCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSale sets the "sale" edge to the Sale entity.
func (_c *SaleReturnCreate) SetSale(v *Sale) *SaleReturnCreate {
	return _c.SetSaleID(v.ID)
}

// AddItemIDs adds the "items" edge to the SaleReturnItem entity by IDs.
func (_c *SaleReturnCreate) AddItemIDs(ids ...int64) *SaleReturnCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the SaleReturnItem entity.
func (_c *SaleReturnCreate) AddItems(v ...*SaleReturnItem) *SaleReturnCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the SaleReturnMutation object of the builder.
func (_c *SaleReturnCreate) Mutation() *SaleReturnMutation {
	return _c.mutation
}

// Save creates the SaleReturn in the database.
func (_c *SaleReturnCreate) Save(ctx context.Context) (*SaleReturn, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SaleReturnCreate) SaveX(ctx context.Context) *SaleReturn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleReturnCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleReturnCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SaleReturnCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := salereturn.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := salereturn.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SaleReturnCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SaleReturn.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SaleReturn.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SaleReturn.tenant_id"`)}
	}
	if _, ok := _c.mutation.SaleID(); !ok {
		return &ValidationError{Name: "sale_id", err: errors.New(`ent: missing required field "SaleReturn.sale_id"`)}
	}
	if _, ok := _c.mutation.CashierID(); !ok {
		return &ValidationError{Name: "cashier_id", err: errors.New(`ent: missing required field "SaleReturn.cashier_id"`)}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "SaleReturn.total"`)}
	}
	if len(_c.mutation.SaleIDs()) == 0 {
		return &ValidationError{Name: "sale", err: errors.New(`ent: missing required edge "SaleReturn.sale"`)}
	}
	return nil
}

func (_c *SaleReturnCreate) sqlSave(ctx context.Context) (*SaleReturn, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SaleReturnCreate) createSpec() (*SaleReturn, *sqlgraph.CreateSpec) {
	var (
		_node = &SaleReturn{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(salereturn.Table, sqlgraph.NewFieldSpec(salereturn.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(salereturn.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(salereturn.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UUID(); ok {
		_spec.SetField(salereturn.FieldUUID, field.TypeString, value)
		_node.UUID = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(salereturn.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CashierID(); ok {
		_spec.SetField(salereturn.FieldCashierID, field.TypeInt64, value)
		_node.CashierID = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(salereturn.FieldTotal, field.TypeFloat64, value)
		_node.Total = value
	}
	if nodes := _c.mutation.SaleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   salereturn.SaleTable,
			Columns: []string{salereturn.SaleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sale.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SaleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   salereturn.ItemsTable,
			Columns: []string{salereturn.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(salereturnitem.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleReturn.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleReturnUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleReturnCreate) OnConflict(opts ...sql.ConflictOption) *SaleReturnUpsertOne {
	_c.conflict = opts
	return &SaleReturnUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleReturn.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleReturnCreate) OnConflictColumns(columns ...string) *SaleReturnUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleReturnUpsertOne{
		create: _c,
	}
}

type (
	// SaleReturnUpsertOne is the builder for "upsert"-ing
	//  one SaleReturn node.
	SaleReturnUpsertOne struct {
		create *SaleReturnCreate
	}

	// SaleReturnUpsert is the "OnConflict" setter.
	SaleReturnUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleReturnUpsert) SetUpdatedAt(v time.Time) *SaleReturnUpsert {
	u.Set(salereturn.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleReturnUpsert) UpdateUpdatedAt() *SaleReturnUpsert {
	u.SetExcluded(salereturn.FieldUpdatedAt)
	return u
}

// SetUUID sets the "uuid" field.
func (u *SaleReturnUpsert) SetUUID(v string) *SaleReturnUpsert {
	u.Set(salereturn.FieldUUID, v)
	return u
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *SaleReturnUpsert) UpdateUUID() *SaleReturnUpsert {
	u.SetExcluded(salereturn.FieldUUID)
	return u
}

// ClearUUID clears the value of the "uuid" field.
func (u *SaleReturnUpsert) ClearUUID() *SaleReturnUpsert {
	u.SetNull(salereturn.FieldUUID)
	return u
}

// SetTotal sets the "total" field.
func (u *SaleReturnUpsert) SetTotal(v decimal.Decimal) *SaleReturnUpsert {
	u.Set(salereturn.FieldTotal, v)
	return u
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleReturnUpsert) UpdateTotal() *SaleReturnUpsert {
	u.SetExcluded(salereturn.FieldTotal)
	return u
}

// AddTotal adds v to the "total" field.
func (u *SaleReturnUpsert) AddTotal(v decimal.Decimal) *SaleReturnUpsert {
	u.Add(salereturn.FieldTotal, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SaleReturn.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(salereturn.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleReturnUpsertOne) UpdateNewValues() *SaleReturnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(salereturn.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(salereturn.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(salereturn.FieldTenantID)
		}
		if _, exists := u.create.mutation.SaleID(); exists {
			s.SetIgnore(salereturn.FieldSaleID)
		}
		if _, exists := u.create.mutation.CashierID(); exists {
			s.SetIgnore(salereturn.FieldCashierID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleReturn.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SaleReturnUpsertOne) Ignore() *SaleReturnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleReturnUpsertOne) DoNothing() *SaleReturnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleReturnCreate.OnConflict
// documentation for more info.
func (u *SaleReturnUpsertOne) Update(set func(*SaleReturnUpsert)) *SaleReturnUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleReturnUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleReturnUpsertOne) SetUpdatedAt(v time.Time) *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleReturnUpsertOne) UpdateUpdatedAt() *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUUID sets the "uuid" field.
func (u *SaleReturnUpsertOne) SetUUID(v string) *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *SaleReturnUpsertOne) UpdateUUID() *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.UpdateUUID()
	})
}

// ClearUUID clears the value of the "uuid" field.
func (u *SaleReturnUpsertOne) ClearUUID() *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.ClearUUID()
	})
}

// SetTotal sets the "total" field.
func (u *SaleReturnUpsertOne) SetTotal(v decimal.Decimal) *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleReturnUpsertOne) AddTotal(v decimal.Decimal) *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleReturnUpsertOne) UpdateTotal() *SaleReturnUpsertOne {
	return u.Update(func(s *SaleReturnUpsert) {
		s.UpdateTotal()
	})
}

// Exec executes the query.
func (u *SaleReturnUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleReturnCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleReturnUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SaleReturnUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SaleReturnUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SaleReturnCreateBulk is the builder for creating many SaleReturn entities in bulk.
type SaleReturnCreateBulk struct {
	config
	err      error
	builders []*SaleReturnCreate
	conflict []sql.ConflictOption
}

// Save creates the SaleReturn entities in the database.
func (_c *SaleReturnCreateBulk) Save(ctx context.Context) ([]*SaleReturn, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SaleReturn, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SaleReturnMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SaleReturnCreateBulk) SaveX(ctx context.Context) []*SaleReturn {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SaleReturnCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SaleReturnCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SaleReturn.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SaleReturnUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SaleReturnCreateBulk) OnConflict(opts ...sql.ConflictOption) *SaleReturnUpsertBulk {
	_c.conflict = opts
	return &SaleReturnUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SaleReturn.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SaleReturnCreateBulk) OnConflictColumns(columns ...string) *SaleReturnUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SaleReturnUpsertBulk{
		create: _c,
	}
}

// SaleReturnUpsertBulk is the builder for "upsert"-ing
// a bulk of SaleReturn nodes.
type SaleReturnUpsertBulk struct {
	create *SaleReturnCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SaleReturn.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(salereturn.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SaleReturnUpsertBulk) UpdateNewValues() *SaleReturnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(salereturn.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(salereturn.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(salereturn.FieldTenantID)
			}
			if _, exists := b.mutation.SaleID(); exists {
				s.SetIgnore(salereturn.FieldSaleID)
			}
			if _, exists := b.mutation.CashierID(); exists {
				s.SetIgnore(salereturn.FieldCashierID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SaleReturn.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SaleReturnUpsertBulk) Ignore() *SaleReturnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SaleReturnUpsertBulk) DoNothing() *SaleReturnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SaleReturnCreateBulk.OnConflict
// documentation for more info.
func (u *SaleReturnUpsertBulk) Update(set func(*SaleReturnUpsert)) *SaleReturnUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SaleReturnUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SaleReturnUpsertBulk) SetUpdatedAt(v time.Time) *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SaleReturnUpsertBulk) UpdateUpdatedAt() *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUUID sets the "uuid" field.
func (u *SaleReturnUpsertBulk) SetUUID(v string) *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.SetUUID(v)
	})
}

// UpdateUUID sets the "uuid" field to the value that was provided on create.
func (u *SaleReturnUpsertBulk) UpdateUUID() *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.UpdateUUID()
	})
}

// ClearUUID clears the value of the "uuid" field.
func (u *SaleReturnUpsertBulk) ClearUUID() *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.ClearUUID()
	})
}

// SetTotal sets the "total" field.
func (u *SaleReturnUpsertBulk) SetTotal(v decimal.Decimal) *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.SetTotal(v)
	})
}

// AddTotal adds v to the "total" field.
func (u *SaleReturnUpsertBulk) AddTotal(v decimal.Decimal) *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.AddTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *SaleReturnUpsertBulk) UpdateTotal() *SaleReturnUpsertBulk {
	return u.Update(func(s *SaleReturnUpsert) {
		s.UpdateTotal()
	})
}

// Exec executes the query.
func (u *SaleReturnUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SaleReturnCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SaleReturnCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SaleReturnUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
