// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/sales/ent/enum"
	"github.com/makesalekz/sales/ent/predicate"
	"github.com/makesalekz/sales/ent/shift"
)

// ShiftUpdate is the builder for updating Shift entities.
type ShiftUpdate struct {
	config
	hooks     []Hook
	mutation  *ShiftMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ShiftUpdate builder.
func (_u *ShiftUpdate) Where(ps ...predicate.Shift) *ShiftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShiftUpdate) SetUpdatedAt(v time.Time) *ShiftUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *ShiftUpdate) SetStoreID(v int64) *ShiftUpdate {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableStoreID(v *int64) *ShiftUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *ShiftUpdate) AddStoreID(v int64) *ShiftUpdate {
	_u.mutation.AddStoreID(v)
	return _u
}

// ClearStoreID clears the value of the "store_id" field.
func (_u *ShiftUpdate) ClearStoreID() *ShiftUpdate {
	_u.mutation.ClearStoreID()
	return _u
}

// SetOpeningAmount sets the "opening_amount" field.
func (_u *ShiftUpdate) SetOpeningAmount(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.ResetOpeningAmount()
	_u.mutation.SetOpeningAmount(v)
	return _u
}

// SetNillableOpeningAmount sets the "opening_amount" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableOpeningAmount(v *decimal.Decimal) *ShiftUpdate {
	if v != nil {
		_u.SetOpeningAmount(*v)
	}
	return _u
}

// AddOpeningAmount adds value to the "opening_amount" field.
func (_u *ShiftUpdate) AddOpeningAmount(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.AddOpeningAmount(v)
	return _u
}

// SetClosingAmount sets the "closing_amount" field.
func (_u *ShiftUpdate) SetClosingAmount(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.ResetClosingAmount()
	_u.mutation.SetClosingAmount(v)
	return _u
}

// SetNillableClosingAmount sets the "closing_amount" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableClosingAmount(v *decimal.Decimal) *ShiftUpdate {
	if v != nil {
		_u.SetClosingAmount(*v)
	}
	return _u
}

// AddClosingAmount adds value to the "closing_amount" field.
func (_u *ShiftUpdate) AddClosingAmount(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.AddClosingAmount(v)
	return _u
}

// ClearClosingAmount clears the value of the "closing_amount" field.
func (_u *ShiftUpdate) ClearClosingAmount() *ShiftUpdate {
	_u.mutation.ClearClosingAmount()
	return _u
}

// SetTotalSales sets the "total_sales" field.
func (_u *ShiftUpdate) SetTotalSales(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.ResetTotalSales()
	_u.mutation.SetTotalSales(v)
	return _u
}

// SetNillableTotalSales sets the "total_sales" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableTotalSales(v *decimal.Decimal) *ShiftUpdate {
	if v != nil {
		_u.SetTotalSales(*v)
	}
	return _u
}

// AddTotalSales adds value to the "total_sales" field.
func (_u *ShiftUpdate) AddTotalSales(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.AddTotalSales(v)
	return _u
}

// ClearTotalSales clears the value of the "total_sales" field.
func (_u *ShiftUpdate) ClearTotalSales() *ShiftUpdate {
	_u.mutation.ClearTotalSales()
	return _u
}

// SetTotalReturns sets the "total_returns" field.
func (_u *ShiftUpdate) SetTotalReturns(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.ResetTotalReturns()
	_u.mutation.SetTotalReturns(v)
	return _u
}

// SetNillableTotalReturns sets the "total_returns" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableTotalReturns(v *decimal.Decimal) *ShiftUpdate {
	if v != nil {
		_u.SetTotalReturns(*v)
	}
	return _u
}

// AddTotalReturns adds value to the "total_returns" field.
func (_u *ShiftUpdate) AddTotalReturns(v decimal.Decimal) *ShiftUpdate {
	_u.mutation.AddTotalReturns(v)
	return _u
}

// ClearTotalReturns clears the value of the "total_returns" field.
func (_u *ShiftUpdate) ClearTotalReturns() *ShiftUpdate {
	_u.mutation.ClearTotalReturns()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ShiftUpdate) SetStatus(v enum.ShiftStatus) *ShiftUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableStatus(v *enum.ShiftStatus) *ShiftUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *ShiftUpdate) SetOpenedAt(v time.Time) *ShiftUpdate {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableOpenedAt(v *time.Time) *ShiftUpdate {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *ShiftUpdate) SetClosedAt(v time.Time) *ShiftUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *ShiftUpdate) SetNillableClosedAt(v *time.Time) *ShiftUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *ShiftUpdate) ClearClosedAt() *ShiftUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// Mutation returns the ShiftMutation object of the builder.
func (_u *ShiftUpdate) Mutation() *ShiftMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShiftUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShiftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShiftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShiftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShiftUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shift.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShiftUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := shift.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Shift.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ShiftUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ShiftUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ShiftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shift.Table, shift.Columns, sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shift.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(shift.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(shift.FieldStoreID, field.TypeInt64, value)
	}
	if _u.mutation.StoreIDCleared() {
		_spec.ClearField(shift.FieldStoreID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OpeningAmount(); ok {
		_spec.SetField(shift.FieldOpeningAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOpeningAmount(); ok {
		_spec.AddField(shift.FieldOpeningAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClosingAmount(); ok {
		_spec.SetField(shift.FieldClosingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedClosingAmount(); ok {
		_spec.AddField(shift.FieldClosingAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ClosingAmountCleared() {
		_spec.ClearField(shift.FieldClosingAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalSales(); ok {
		_spec.SetField(shift.FieldTotalSales, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalSales(); ok {
		_spec.AddField(shift.FieldTotalSales, field.TypeFloat64, value)
	}
	if _u.mutation.TotalSalesCleared() {
		_spec.ClearField(shift.FieldTotalSales, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalReturns(); ok {
		_spec.SetField(shift.FieldTotalReturns, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalReturns(); ok {
		_spec.AddField(shift.FieldTotalReturns, field.TypeFloat64, value)
	}
	if _u.mutation.TotalReturnsCleared() {
		_spec.ClearField(shift.FieldTotalReturns, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(shift.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(shift.FieldOpenedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(shift.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(shift.FieldClosedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shift.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShiftUpdateOne is the builder for updating a single Shift entity.
type ShiftUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ShiftMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShiftUpdateOne) SetUpdatedAt(v time.Time) *ShiftUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *ShiftUpdateOne) SetStoreID(v int64) *ShiftUpdateOne {
	_u.mutation.ResetStoreID()
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableStoreID(v *int64) *ShiftUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// AddStoreID adds value to the "store_id" field.
func (_u *ShiftUpdateOne) AddStoreID(v int64) *ShiftUpdateOne {
	_u.mutation.AddStoreID(v)
	return _u
}

// ClearStoreID clears the value of the "store_id" field.
func (_u *ShiftUpdateOne) ClearStoreID() *ShiftUpdateOne {
	_u.mutation.ClearStoreID()
	return _u
}

// SetOpeningAmount sets the "opening_amount" field.
func (_u *ShiftUpdateOne) SetOpeningAmount(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.ResetOpeningAmount()
	_u.mutation.SetOpeningAmount(v)
	return _u
}

// SetNillableOpeningAmount sets the "opening_amount" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableOpeningAmount(v *decimal.Decimal) *ShiftUpdateOne {
	if v != nil {
		_u.SetOpeningAmount(*v)
	}
	return _u
}

// AddOpeningAmount adds value to the "opening_amount" field.
func (_u *ShiftUpdateOne) AddOpeningAmount(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.AddOpeningAmount(v)
	return _u
}

// SetClosingAmount sets the "closing_amount" field.
func (_u *ShiftUpdateOne) SetClosingAmount(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.ResetClosingAmount()
	_u.mutation.SetClosingAmount(v)
	return _u
}

// SetNillableClosingAmount sets the "closing_amount" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableClosingAmount(v *decimal.Decimal) *ShiftUpdateOne {
	if v != nil {
		_u.SetClosingAmount(*v)
	}
	return _u
}

// AddClosingAmount adds value to the "closing_amount" field.
func (_u *ShiftUpdateOne) AddClosingAmount(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.AddClosingAmount(v)
	return _u
}

// ClearClosingAmount clears the value of the "closing_amount" field.
func (_u *ShiftUpdateOne) ClearClosingAmount() *ShiftUpdateOne {
	_u.mutation.ClearClosingAmount()
	return _u
}

// SetTotalSales sets the "total_sales" field.
func (_u *ShiftUpdateOne) SetTotalSales(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.ResetTotalSales()
	_u.mutation.SetTotalSales(v)
	return _u
}

// SetNillableTotalSales sets the "total_sales" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableTotalSales(v *decimal.Decimal) *ShiftUpdateOne {
	if v != nil {
		_u.SetTotalSales(*v)
	}
	return _u
}

// AddTotalSales adds value to the "total_sales" field.
func (_u *ShiftUpdateOne) AddTotalSales(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.AddTotalSales(v)
	return _u
}

// ClearTotalSales clears the value of the "total_sales" field.
func (_u *ShiftUpdateOne) ClearTotalSales() *ShiftUpdateOne {
	_u.mutation.ClearTotalSales()
	return _u
}

// SetTotalReturns sets the "total_returns" field.
func (_u *ShiftUpdateOne) SetTotalReturns(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.ResetTotalReturns()
	_u.mutation.SetTotalReturns(v)
	return _u
}

// SetNillableTotalReturns sets the "total_returns" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableTotalReturns(v *decimal.Decimal) *ShiftUpdateOne {
	if v != nil {
		_u.SetTotalReturns(*v)
	}
	return _u
}

// AddTotalReturns adds value to the "total_returns" field.
func (_u *ShiftUpdateOne) AddTotalReturns(v decimal.Decimal) *ShiftUpdateOne {
	_u.mutation.AddTotalReturns(v)
	return _u
}

// ClearTotalReturns clears the value of the "total_returns" field.
func (_u *ShiftUpdateOne) ClearTotalReturns() *ShiftUpdateOne {
	_u.mutation.ClearTotalReturns()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ShiftUpdateOne) SetStatus(v enum.ShiftStatus) *ShiftUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableStatus(v *enum.ShiftStatus) *ShiftUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetOpenedAt sets the "opened_at" field.
func (_u *ShiftUpdateOne) SetOpenedAt(v time.Time) *ShiftUpdateOne {
	_u.mutation.SetOpenedAt(v)
	return _u
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableOpenedAt(v *time.Time) *ShiftUpdateOne {
	if v != nil {
		_u.SetOpenedAt(*v)
	}
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *ShiftUpdateOne) SetClosedAt(v time.Time) *ShiftUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *ShiftUpdateOne) SetNillableClosedAt(v *time.Time) *ShiftUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *ShiftUpdateOne) ClearClosedAt() *ShiftUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// Mutation returns the ShiftMutation object of the builder.
func (_u *ShiftUpdateOne) Mutation() *ShiftMutation {
	return _u.mutation
}

// Where appends a list predicates to the ShiftUpdate builder.
func (_u *ShiftUpdateOne) Where(ps ...predicate.Shift) *ShiftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShiftUpdateOne) Select(field string, fields ...string) *ShiftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Shift entity.
func (_u *ShiftUpdateOne) Save(ctx context.Context) (*Shift, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShiftUpdateOne) SaveX(ctx context.Context) *Shift {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShiftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShiftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShiftUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shift.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShiftUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := shift.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Shift.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ShiftUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ShiftUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ShiftUpdateOne) sqlSave(ctx context.Context) (_node *Shift, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shift.Table, shift.Columns, sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Shift.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shift.FieldID)
		for _, f := range fields {
			if !shift.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shift.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shift.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(shift.FieldStoreID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStoreID(); ok {
		_spec.AddField(shift.FieldStoreID, field.TypeInt64, value)
	}
	if _u.mutation.StoreIDCleared() {
		_spec.ClearField(shift.FieldStoreID, field.TypeInt64)
	}
	if value, ok := _u.mutation.OpeningAmount(); ok {
		_spec.SetField(shift.FieldOpeningAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOpeningAmount(); ok {
		_spec.AddField(shift.FieldOpeningAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ClosingAmount(); ok {
		_spec.SetField(shift.FieldClosingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedClosingAmount(); ok {
		_spec.AddField(shift.FieldClosingAmount, field.TypeFloat64, value)
	}
	if _u.mutation.ClosingAmountCleared() {
		_spec.ClearField(shift.FieldClosingAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalSales(); ok {
		_spec.SetField(shift.FieldTotalSales, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalSales(); ok {
		_spec.AddField(shift.FieldTotalSales, field.TypeFloat64, value)
	}
	if _u.mutation.TotalSalesCleared() {
		_spec.ClearField(shift.FieldTotalSales, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalReturns(); ok {
		_spec.SetField(shift.FieldTotalReturns, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalReturns(); ok {
		_spec.AddField(shift.FieldTotalReturns, field.TypeFloat64, value)
	}
	if _u.mutation.TotalReturnsCleared() {
		_spec.ClearField(shift.FieldTotalReturns, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(shift.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OpenedAt(); ok {
		_spec.SetField(shift.FieldOpenedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(shift.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(shift.FieldClosedAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Shift{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shift.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
