// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/sales/ent/enum"
	"github.com/makesalekz/sales/ent/shift"
)

// ShiftCreate is the builder for creating a Shift entity.
type ShiftCreate struct {
	config
	mutation *ShiftMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShiftCreate) SetCreatedAt(v time.Time) *ShiftCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableCreatedAt(v *time.Time) *ShiftCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ShiftCreate) SetUpdatedAt(v time.Time) *ShiftCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableUpdatedAt(v *time.Time) *ShiftCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ShiftCreate) SetTenantID(v int64) *ShiftCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCashierID sets the "cashier_id" field.
func (_c *ShiftCreate) SetCashierID(v int64) *ShiftCreate {
	_c.mutation.SetCashierID(v)
	return _c
}

// SetStoreID sets the "store_id" field.
func (_c *ShiftCreate) SetStoreID(v int64) *ShiftCreate {
	_c.mutation.SetStoreID(v)
	return _c
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableStoreID(v *int64) *ShiftCreate {
	if v != nil {
		_c.SetStoreID(*v)
	}
	return _c
}

// SetOpeningAmount sets the "opening_amount" field.
func (_c *ShiftCreate) SetOpeningAmount(v decimal.Decimal) *ShiftCreate {
	_c.mutation.SetOpeningAmount(v)
	return _c
}

// SetClosingAmount sets the "closing_amount" field.
func (_c *ShiftCreate) SetClosingAmount(v decimal.Decimal) *ShiftCreate {
	_c.mutation.SetClosingAmount(v)
	return _c
}

// SetNillableClosingAmount sets the "closing_amount" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableClosingAmount(v *decimal.Decimal) *ShiftCreate {
	if v != nil {
		_c.SetClosingAmount(*v)
	}
	return _c
}

// SetTotalSales sets the "total_sales" field.
func (_c *ShiftCreate) SetTotalSales(v decimal.Decimal) *ShiftCreate {
	_c.mutation.SetTotalSales(v)
	return _c
}

// SetNillableTotalSales sets the "total_sales" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableTotalSales(v *decimal.Decimal) *ShiftCreate {
	if v != nil {
		_c.SetTotalSales(*v)
	}
	return _c
}

// SetTotalReturns sets the "total_returns" field.
func (_c *ShiftCreate) SetTotalReturns(v decimal.Decimal) *ShiftCreate {
	_c.mutation.SetTotalReturns(v)
	return _c
}

// SetNillableTotalReturns sets the "total_returns" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableTotalReturns(v *decimal.Decimal) *ShiftCreate {
	if v != nil {
		_c.SetTotalReturns(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ShiftCreate) SetStatus(v enum.ShiftStatus) *ShiftCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableStatus(v *enum.ShiftStatus) *ShiftCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOpenedAt sets the "opened_at" field.
func (_c *ShiftCreate) SetOpenedAt(v time.Time) *ShiftCreate {
	_c.mutation.SetOpenedAt(v)
	return _c
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableOpenedAt(v *time.Time) *ShiftCreate {
	if v != nil {
		_c.SetOpenedAt(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *ShiftCreate) SetClosedAt(v time.Time) *ShiftCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *ShiftCreate) SetNillableClosedAt(v *time.Time) *ShiftCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShiftCreate) SetID(v int64) *ShiftCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ShiftMutation object of the builder.
func (_c *ShiftCreate) Mutation() *ShiftMutation {
	return _c.mutation
}

// Save creates the Shift in the database.
func (_c *ShiftCreate) Save(ctx context.Context) (*Shift, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShiftCreate) SaveX(ctx context.Context) *Shift {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShiftCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShiftCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShiftCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shift.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := shift.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := shift.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.OpenedAt(); !ok {
		v := shift.DefaultOpenedAt()
		_c.mutation.SetOpenedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShiftCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Shift.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Shift.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Shift.tenant_id"`)}
	}
	if _, ok := _c.mutation.CashierID(); !ok {
		return &ValidationError{Name: "cashier_id", err: errors.New(`ent: missing required field "Shift.cashier_id"`)}
	}
	if _, ok := _c.mutation.OpeningAmount(); !ok {
		return &ValidationError{Name: "opening_amount", err: errors.New(`ent: missing required field "Shift.opening_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Shift.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := shift.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Shift.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OpenedAt(); !ok {
		return &ValidationError{Name: "opened_at", err: errors.New(`ent: missing required field "Shift.opened_at"`)}
	}
	return nil
}

func (_c *ShiftCreate) sqlSave(ctx context.Context) (*Shift, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShiftCreate) createSpec() (*Shift, *sqlgraph.CreateSpec) {
	var (
		_node = &Shift{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shift.Table, sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shift.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(shift.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(shift.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CashierID(); ok {
		_spec.SetField(shift.FieldCashierID, field.TypeInt64, value)
		_node.CashierID = value
	}
	if value, ok := _c.mutation.StoreID(); ok {
		_spec.SetField(shift.FieldStoreID, field.TypeInt64, value)
		_node.StoreID = &value
	}
	if value, ok := _c.mutation.OpeningAmount(); ok {
		_spec.SetField(shift.FieldOpeningAmount, field.TypeFloat64, value)
		_node.OpeningAmount = value
	}
	if value, ok := _c.mutation.ClosingAmount(); ok {
		_spec.SetField(shift.FieldClosingAmount, field.TypeFloat64, value)
		_node.ClosingAmount = value
	}
	if value, ok := _c.mutation.TotalSales(); ok {
		_spec.SetField(shift.FieldTotalSales, field.TypeFloat64, value)
		_node.TotalSales = value
	}
	if value, ok := _c.mutation.TotalReturns(); ok {
		_spec.SetField(shift.FieldTotalReturns, field.TypeFloat64, value)
		_node.TotalReturns = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(shift.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.OpenedAt(); ok {
		_spec.SetField(shift.FieldOpenedAt, field.TypeTime, value)
		_node.OpenedAt = value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(shift.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shift.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShiftUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShiftCreate) OnConflict(opts ...sql.ConflictOption) *ShiftUpsertOne {
	_c.conflict = opts
	return &ShiftUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shift.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShiftCreate) OnConflictColumns(columns ...string) *ShiftUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShiftUpsertOne{
		create: _c,
	}
}

type (
	// ShiftUpsertOne is the builder for "upsert"-ing
	//  one Shift node.
	ShiftUpsertOne struct {
		create *ShiftCreate
	}

	// ShiftUpsert is the "OnConflict" setter.
	ShiftUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ShiftUpsert) SetUpdatedAt(v time.Time) *ShiftUpsert {
	u.Set(shift.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateUpdatedAt() *ShiftUpsert {
	u.SetExcluded(shift.FieldUpdatedAt)
	return u
}

// SetStoreID sets the "store_id" field.
func (u *ShiftUpsert) SetStoreID(v int64) *ShiftUpsert {
	u.Set(shift.FieldStoreID, v)
	return u
}

// UpdateStoreID sets the "store_id" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateStoreID() *ShiftUpsert {
	u.SetExcluded(shift.FieldStoreID)
	return u
}

// AddStoreID adds v to the "store_id" field.
func (u *ShiftUpsert) AddStoreID(v int64) *ShiftUpsert {
	u.Add(shift.FieldStoreID, v)
	return u
}

// ClearStoreID clears the value of the "store_id" field.
func (u *ShiftUpsert) ClearStoreID() *ShiftUpsert {
	u.SetNull(shift.FieldStoreID)
	return u
}

// SetOpeningAmount sets the "opening_amount" field.
func (u *ShiftUpsert) SetOpeningAmount(v decimal.Decimal) *ShiftUpsert {
	u.Set(shift.FieldOpeningAmount, v)
	return u
}

// UpdateOpeningAmount sets the "opening_amount" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateOpeningAmount() *ShiftUpsert {
	u.SetExcluded(shift.FieldOpeningAmount)
	return u
}

// AddOpeningAmount adds v to the "opening_amount" field.
func (u *ShiftUpsert) AddOpeningAmount(v decimal.Decimal) *ShiftUpsert {
	u.Add(shift.FieldOpeningAmount, v)
	return u
}

// SetClosingAmount sets the "closing_amount" field.
func (u *ShiftUpsert) SetClosingAmount(v decimal.Decimal) *ShiftUpsert {
	u.Set(shift.FieldClosingAmount, v)
	return u
}

// UpdateClosingAmount sets the "closing_amount" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateClosingAmount() *ShiftUpsert {
	u.SetExcluded(shift.FieldClosingAmount)
	return u
}

// AddClosingAmount adds v to the "closing_amount" field.
func (u *ShiftUpsert) AddClosingAmount(v decimal.Decimal) *ShiftUpsert {
	u.Add(shift.FieldClosingAmount, v)
	return u
}

// ClearClosingAmount clears the value of the "closing_amount" field.
func (u *ShiftUpsert) ClearClosingAmount() *ShiftUpsert {
	u.SetNull(shift.FieldClosingAmount)
	return u
}

// SetTotalSales sets the "total_sales" field.
func (u *ShiftUpsert) SetTotalSales(v decimal.Decimal) *ShiftUpsert {
	u.Set(shift.FieldTotalSales, v)
	return u
}

// UpdateTotalSales sets the "total_sales" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateTotalSales() *ShiftUpsert {
	u.SetExcluded(shift.FieldTotalSales)
	return u
}

// AddTotalSales adds v to the "total_sales" field.
func (u *ShiftUpsert) AddTotalSales(v decimal.Decimal) *ShiftUpsert {
	u.Add(shift.FieldTotalSales, v)
	return u
}

// ClearTotalSales clears the value of the "total_sales" field.
func (u *ShiftUpsert) ClearTotalSales() *ShiftUpsert {
	u.SetNull(shift.FieldTotalSales)
	return u
}

// SetTotalReturns sets the "total_returns" field.
func (u *ShiftUpsert) SetTotalReturns(v decimal.Decimal) *ShiftUpsert {
	u.Set(shift.FieldTotalReturns, v)
	return u
}

// UpdateTotalReturns sets the "total_returns" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateTotalReturns() *ShiftUpsert {
	u.SetExcluded(shift.FieldTotalReturns)
	return u
}

// AddTotalReturns adds v to the "total_returns" field.
func (u *ShiftUpsert) AddTotalReturns(v decimal.Decimal) *ShiftUpsert {
	u.Add(shift.FieldTotalReturns, v)
	return u
}

// ClearTotalReturns clears the value of the "total_returns" field.
func (u *ShiftUpsert) ClearTotalReturns() *ShiftUpsert {
	u.SetNull(shift.FieldTotalReturns)
	return u
}

// SetStatus sets the "status" field.
func (u *ShiftUpsert) SetStatus(v enum.ShiftStatus) *ShiftUpsert {
	u.Set(shift.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateStatus() *ShiftUpsert {
	u.SetExcluded(shift.FieldStatus)
	return u
}

// SetOpenedAt sets the "opened_at" field.
func (u *ShiftUpsert) SetOpenedAt(v time.Time) *ShiftUpsert {
	u.Set(shift.FieldOpenedAt, v)
	return u
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateOpenedAt() *ShiftUpsert {
	u.SetExcluded(shift.FieldOpenedAt)
	return u
}

// SetClosedAt sets the "closed_at" field.
func (u *ShiftUpsert) SetClosedAt(v time.Time) *ShiftUpsert {
	u.Set(shift.FieldClosedAt, v)
	return u
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *ShiftUpsert) UpdateClosedAt() *ShiftUpsert {
	u.SetExcluded(shift.FieldClosedAt)
	return u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *ShiftUpsert) ClearClosedAt() *ShiftUpsert {
	u.SetNull(shift.FieldClosedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Shift.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(shift.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShiftUpsertOne) UpdateNewValues() *ShiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(shift.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(shift.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(shift.FieldTenantID)
		}
		if _, exists := u.create.mutation.CashierID(); exists {
			s.SetIgnore(shift.FieldCashierID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shift.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShiftUpsertOne) Ignore() *ShiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShiftUpsertOne) DoNothing() *ShiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShiftCreate.OnConflict
// documentation for more info.
func (u *ShiftUpsertOne) Update(set func(*ShiftUpsert)) *ShiftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShiftUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShiftUpsertOne) SetUpdatedAt(v time.Time) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateUpdatedAt() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStoreID sets the "store_id" field.
func (u *ShiftUpsertOne) SetStoreID(v int64) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetStoreID(v)
	})
}

// AddStoreID adds v to the "store_id" field.
func (u *ShiftUpsertOne) AddStoreID(v int64) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.AddStoreID(v)
	})
}

// UpdateStoreID sets the "store_id" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateStoreID() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateStoreID()
	})
}

// ClearStoreID clears the value of the "store_id" field.
func (u *ShiftUpsertOne) ClearStoreID() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearStoreID()
	})
}

// SetOpeningAmount sets the "opening_amount" field.
func (u *ShiftUpsertOne) SetOpeningAmount(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetOpeningAmount(v)
	})
}

// AddOpeningAmount adds v to the "opening_amount" field.
func (u *ShiftUpsertOne) AddOpeningAmount(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.AddOpeningAmount(v)
	})
}

// UpdateOpeningAmount sets the "opening_amount" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateOpeningAmount() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateOpeningAmount()
	})
}

// SetClosingAmount sets the "closing_amount" field.
func (u *ShiftUpsertOne) SetClosingAmount(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetClosingAmount(v)
	})
}

// AddClosingAmount adds v to the "closing_amount" field.
func (u *ShiftUpsertOne) AddClosingAmount(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.AddClosingAmount(v)
	})
}

// UpdateClosingAmount sets the "closing_amount" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateClosingAmount() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateClosingAmount()
	})
}

// ClearClosingAmount clears the value of the "closing_amount" field.
func (u *ShiftUpsertOne) ClearClosingAmount() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearClosingAmount()
	})
}

// SetTotalSales sets the "total_sales" field.
func (u *ShiftUpsertOne) SetTotalSales(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetTotalSales(v)
	})
}

// AddTotalSales adds v to the "total_sales" field.
func (u *ShiftUpsertOne) AddTotalSales(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.AddTotalSales(v)
	})
}

// UpdateTotalSales sets the "total_sales" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateTotalSales() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateTotalSales()
	})
}

// ClearTotalSales clears the value of the "total_sales" field.
func (u *ShiftUpsertOne) ClearTotalSales() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearTotalSales()
	})
}

// SetTotalReturns sets the "total_returns" field.
func (u *ShiftUpsertOne) SetTotalReturns(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetTotalReturns(v)
	})
}

// AddTotalReturns adds v to the "total_returns" field.
func (u *ShiftUpsertOne) AddTotalReturns(v decimal.Decimal) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.AddTotalReturns(v)
	})
}

// UpdateTotalReturns sets the "total_returns" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateTotalReturns() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateTotalReturns()
	})
}

// ClearTotalReturns clears the value of the "total_returns" field.
func (u *ShiftUpsertOne) ClearTotalReturns() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearTotalReturns()
	})
}

// SetStatus sets the "status" field.
func (u *ShiftUpsertOne) SetStatus(v enum.ShiftStatus) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateStatus() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateStatus()
	})
}

// SetOpenedAt sets the "opened_at" field.
func (u *ShiftUpsertOne) SetOpenedAt(v time.Time) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetOpenedAt(v)
	})
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateOpenedAt() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateOpenedAt()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *ShiftUpsertOne) SetClosedAt(v time.Time) *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *ShiftUpsertOne) UpdateClosedAt() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *ShiftUpsertOne) ClearClosedAt() *ShiftUpsertOne {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearClosedAt()
	})
}

// Exec executes the query.
func (u *ShiftUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShiftCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShiftUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShiftUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShiftUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShiftCreateBulk is the builder for creating many Shift entities in bulk.
type ShiftCreateBulk struct {
	config
	err      error
	builders []*ShiftCreate
	conflict []sql.ConflictOption
}

// Save creates the Shift entities in the database.
func (_c *ShiftCreateBulk) Save(ctx context.Context) ([]*Shift, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Shift, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShiftMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShiftCreateBulk) SaveX(ctx context.Context) []*Shift {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShiftCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShiftCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shift.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShiftUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ShiftCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShiftUpsertBulk {
	_c.conflict = opts
	return &ShiftUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shift.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShiftCreateBulk) OnConflictColumns(columns ...string) *ShiftUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShiftUpsertBulk{
		create: _c,
	}
}

// ShiftUpsertBulk is the builder for "upsert"-ing
// a bulk of Shift nodes.
type ShiftUpsertBulk struct {
	create *ShiftCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Shift.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(shift.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShiftUpsertBulk) UpdateNewValues() *ShiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(shift.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(shift.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(shift.FieldTenantID)
			}
			if _, exists := b.mutation.CashierID(); exists {
				s.SetIgnore(shift.FieldCashierID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shift.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShiftUpsertBulk) Ignore() *ShiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShiftUpsertBulk) DoNothing() *ShiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShiftCreateBulk.OnConflict
// documentation for more info.
func (u *ShiftUpsertBulk) Update(set func(*ShiftUpsert)) *ShiftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShiftUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ShiftUpsertBulk) SetUpdatedAt(v time.Time) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateUpdatedAt() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStoreID sets the "store_id" field.
func (u *ShiftUpsertBulk) SetStoreID(v int64) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetStoreID(v)
	})
}

// AddStoreID adds v to the "store_id" field.
func (u *ShiftUpsertBulk) AddStoreID(v int64) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.AddStoreID(v)
	})
}

// UpdateStoreID sets the "store_id" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateStoreID() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateStoreID()
	})
}

// ClearStoreID clears the value of the "store_id" field.
func (u *ShiftUpsertBulk) ClearStoreID() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearStoreID()
	})
}

// SetOpeningAmount sets the "opening_amount" field.
func (u *ShiftUpsertBulk) SetOpeningAmount(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetOpeningAmount(v)
	})
}

// AddOpeningAmount adds v to the "opening_amount" field.
func (u *ShiftUpsertBulk) AddOpeningAmount(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.AddOpeningAmount(v)
	})
}

// UpdateOpeningAmount sets the "opening_amount" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateOpeningAmount() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateOpeningAmount()
	})
}

// SetClosingAmount sets the "closing_amount" field.
func (u *ShiftUpsertBulk) SetClosingAmount(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetClosingAmount(v)
	})
}

// AddClosingAmount adds v to the "closing_amount" field.
func (u *ShiftUpsertBulk) AddClosingAmount(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.AddClosingAmount(v)
	})
}

// UpdateClosingAmount sets the "closing_amount" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateClosingAmount() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateClosingAmount()
	})
}

// ClearClosingAmount clears the value of the "closing_amount" field.
func (u *ShiftUpsertBulk) ClearClosingAmount() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearClosingAmount()
	})
}

// SetTotalSales sets the "total_sales" field.
func (u *ShiftUpsertBulk) SetTotalSales(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetTotalSales(v)
	})
}

// AddTotalSales adds v to the "total_sales" field.
func (u *ShiftUpsertBulk) AddTotalSales(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.AddTotalSales(v)
	})
}

// UpdateTotalSales sets the "total_sales" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateTotalSales() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateTotalSales()
	})
}

// ClearTotalSales clears the value of the "total_sales" field.
func (u *ShiftUpsertBulk) ClearTotalSales() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearTotalSales()
	})
}

// SetTotalReturns sets the "total_returns" field.
func (u *ShiftUpsertBulk) SetTotalReturns(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetTotalReturns(v)
	})
}

// AddTotalReturns adds v to the "total_returns" field.
func (u *ShiftUpsertBulk) AddTotalReturns(v decimal.Decimal) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.AddTotalReturns(v)
	})
}

// UpdateTotalReturns sets the "total_returns" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateTotalReturns() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateTotalReturns()
	})
}

// ClearTotalReturns clears the value of the "total_returns" field.
func (u *ShiftUpsertBulk) ClearTotalReturns() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearTotalReturns()
	})
}

// SetStatus sets the "status" field.
func (u *ShiftUpsertBulk) SetStatus(v enum.ShiftStatus) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateStatus() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateStatus()
	})
}

// SetOpenedAt sets the "opened_at" field.
func (u *ShiftUpsertBulk) SetOpenedAt(v time.Time) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetOpenedAt(v)
	})
}

// UpdateOpenedAt sets the "opened_at" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateOpenedAt() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateOpenedAt()
	})
}

// SetClosedAt sets the "closed_at" field.
func (u *ShiftUpsertBulk) SetClosedAt(v time.Time) *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.SetClosedAt(v)
	})
}

// UpdateClosedAt sets the "closed_at" field to the value that was provided on create.
func (u *ShiftUpsertBulk) UpdateClosedAt() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.UpdateClosedAt()
	})
}

// ClearClosedAt clears the value of the "closed_at" field.
func (u *ShiftUpsertBulk) ClearClosedAt() *ShiftUpsertBulk {
	return u.Update(func(s *ShiftUpsert) {
		s.ClearClosedAt()
	})
}

// Exec executes the query.
func (u *ShiftUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShiftCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShiftCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShiftUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
