// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/enum"
	"gitlab.calendaria.team/services/sales/ent/shift"
)

// Shift is the model entity for the Shift schema.
type Shift struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// CashierID holds the value of the "cashier_id" field.
	CashierID int64 `json:"cashier_id,omitempty"`
	// StoreID holds the value of the "store_id" field.
	StoreID *int64 `json:"store_id,omitempty"`
	// OpeningAmount holds the value of the "opening_amount" field.
	OpeningAmount decimal.Decimal `json:"opening_amount,omitempty"`
	// ClosingAmount holds the value of the "closing_amount" field.
	ClosingAmount decimal.Decimal `json:"closing_amount,omitempty"`
	// TotalSales holds the value of the "total_sales" field.
	TotalSales decimal.Decimal `json:"total_sales,omitempty"`
	// TotalReturns holds the value of the "total_returns" field.
	TotalReturns decimal.Decimal `json:"total_returns,omitempty"`
	// Status holds the value of the "status" field.
	Status enum.ShiftStatus `json:"status,omitempty"`
	// OpenedAt holds the value of the "opened_at" field.
	OpenedAt time.Time `json:"opened_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt     *time.Time `json:"closed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Shift) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shift.FieldOpeningAmount, shift.FieldClosingAmount, shift.FieldTotalSales, shift.FieldTotalReturns:
			values[i] = new(decimal.Decimal)
		case shift.FieldID, shift.FieldTenantID, shift.FieldCashierID, shift.FieldStoreID:
			values[i] = new(sql.NullInt64)
		case shift.FieldStatus:
			values[i] = new(sql.NullString)
		case shift.FieldCreatedAt, shift.FieldUpdatedAt, shift.FieldOpenedAt, shift.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Shift fields.
func (_m *Shift) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shift.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case shift.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case shift.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case shift.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.Int64
			}
		case shift.FieldCashierID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cashier_id", values[i])
			} else if value.Valid {
				_m.CashierID = value.Int64
			}
		case shift.FieldStoreID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field store_id", values[i])
			} else if value.Valid {
				_m.StoreID = new(int64)
				*_m.StoreID = value.Int64
			}
		case shift.FieldOpeningAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field opening_amount", values[i])
			} else if value != nil {
				_m.OpeningAmount = *value
			}
		case shift.FieldClosingAmount:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field closing_amount", values[i])
			} else if value != nil {
				_m.ClosingAmount = *value
			}
		case shift.FieldTotalSales:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field total_sales", values[i])
			} else if value != nil {
				_m.TotalSales = *value
			}
		case shift.FieldTotalReturns:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field total_returns", values[i])
			} else if value != nil {
				_m.TotalReturns = *value
			}
		case shift.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = enum.ShiftStatus(value.String)
			}
		case shift.FieldOpenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opened_at", values[i])
			} else if value.Valid {
				_m.OpenedAt = value.Time
			}
		case shift.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Shift.
// This includes values selected through modifiers, order, etc.
func (_m *Shift) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Shift.
// Note that you need to call Shift.Unwrap() before calling this method if this Shift
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Shift) Update() *ShiftUpdateOne {
	return NewShiftClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Shift entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Shift) Unwrap() *Shift {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Shift is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Shift) String() string {
	var builder strings.Builder
	builder.WriteString("Shift(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("cashier_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CashierID))
	builder.WriteString(", ")
	if v := _m.StoreID; v != nil {
		builder.WriteString("store_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("opening_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.OpeningAmount))
	builder.WriteString(", ")
	builder.WriteString("closing_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClosingAmount))
	builder.WriteString(", ")
	builder.WriteString("total_sales=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSales))
	builder.WriteString(", ")
	builder.WriteString("total_returns=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalReturns))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("opened_at=")
	builder.WriteString(_m.OpenedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Shifts is a parsable slice of Shift.
type Shifts []*Shift
