// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/sales/v1/sales.proto

package sales_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncOperationType int32

const (
	SyncOperationType_SALE   SyncOperationType = 0
	SyncOperationType_RETURN SyncOperationType = 1
)

// Enum value maps for SyncOperationType.
var (
	SyncOperationType_name = map[int32]string{
		0: "SALE",
		1: "RETURN",
	}
	SyncOperationType_value = map[string]int32{
		"SALE":   0,
		"RETURN": 1,
	}
)

func (x SyncOperationType) Enum() *SyncOperationType {
	p := new(SyncOperationType)
	*p = x
	return p
}

func (x SyncOperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncOperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_sales_v1_sales_proto_enumTypes[0].Descriptor()
}

func (SyncOperationType) Type() protoreflect.EnumType {
	return &file_api_sales_v1_sales_proto_enumTypes[0]
}

func (x SyncOperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncOperationType.Descriptor instead.
func (SyncOperationType) EnumDescriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{0}
}

type CreateSaleItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Quantity      string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Discount      string                 `protobuf:"bytes,5,opt,name=discount,proto3" json:"discount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaleItemRequest) Reset() {
	*x = CreateSaleItemRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaleItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleItemRequest) ProtoMessage() {}

func (x *CreateSaleItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleItemRequest.ProtoReflect.Descriptor instead.
func (*CreateSaleItemRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSaleItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateSaleItemRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CreateSaleItemRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CreateSaleItemRequest) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *CreateSaleItemRequest) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

type CreateSaleRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*CreateSaleItemRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	PaymentType   string                   `protobuf:"bytes,2,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	ShiftId       int64                    `protobuf:"varint,3,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	DiscountType  string                   `protobuf:"bytes,4,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountValue string                   `protobuf:"bytes,5,opt,name=discount_value,json=discountValue,proto3" json:"discount_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaleRequest) Reset() {
	*x = CreateSaleRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleRequest) ProtoMessage() {}

func (x *CreateSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleRequest.ProtoReflect.Descriptor instead.
func (*CreateSaleRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSaleRequest) GetItems() []*CreateSaleItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateSaleRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreateSaleRequest) GetShiftId() int64 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

func (x *CreateSaleRequest) GetDiscountType() string {
	if x != nil {
		return x.DiscountType
	}
	return ""
}

func (x *CreateSaleRequest) GetDiscountValue() string {
	if x != nil {
		return x.DiscountValue
	}
	return ""
}

type CreateSaleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sale          *Sale                  `protobuf:"bytes,1,opt,name=sale,proto3" json:"sale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSaleReply) Reset() {
	*x = CreateSaleReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSaleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleReply) ProtoMessage() {}

func (x *CreateSaleReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleReply.ProtoReflect.Descriptor instead.
func (*CreateSaleReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSaleReply) GetSale() *Sale {
	if x != nil {
		return x.Sale
	}
	return nil
}

type OpenShiftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpeningAmount string                 `protobuf:"bytes,1,opt,name=opening_amount,json=openingAmount,proto3" json:"opening_amount,omitempty"`
	StoreId       *int64                 `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3,oneof" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShiftRequest) Reset() {
	*x = OpenShiftRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShiftRequest) ProtoMessage() {}

func (x *OpenShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShiftRequest.ProtoReflect.Descriptor instead.
func (*OpenShiftRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{3}
}

func (x *OpenShiftRequest) GetOpeningAmount() string {
	if x != nil {
		return x.OpeningAmount
	}
	return ""
}

func (x *OpenShiftRequest) GetStoreId() int64 {
	if x != nil && x.StoreId != nil {
		return *x.StoreId
	}
	return 0
}

type OpenShiftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shift         *Shift                 `protobuf:"bytes,1,opt,name=shift,proto3" json:"shift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenShiftReply) Reset() {
	*x = OpenShiftReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenShiftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenShiftReply) ProtoMessage() {}

func (x *OpenShiftReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenShiftReply.ProtoReflect.Descriptor instead.
func (*OpenShiftReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{4}
}

func (x *OpenShiftReply) GetShift() *Shift {
	if x != nil {
		return x.Shift
	}
	return nil
}

type CloseShiftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShiftId       int64                  `protobuf:"varint,1,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShiftRequest) Reset() {
	*x = CloseShiftRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShiftRequest) ProtoMessage() {}

func (x *CloseShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShiftRequest.ProtoReflect.Descriptor instead.
func (*CloseShiftRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{5}
}

func (x *CloseShiftRequest) GetShiftId() int64 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

type CloseShiftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shift         *Shift                 `protobuf:"bytes,1,opt,name=shift,proto3" json:"shift,omitempty"`
	ZReport       *ZReport               `protobuf:"bytes,2,opt,name=z_report,json=zReport,proto3" json:"z_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseShiftReply) Reset() {
	*x = CloseShiftReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseShiftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseShiftReply) ProtoMessage() {}

func (x *CloseShiftReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseShiftReply.ProtoReflect.Descriptor instead.
func (*CloseShiftReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{6}
}

func (x *CloseShiftReply) GetShift() *Shift {
	if x != nil {
		return x.Shift
	}
	return nil
}

func (x *CloseShiftReply) GetZReport() *ZReport {
	if x != nil {
		return x.ZReport
	}
	return nil
}

type GetShiftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShiftId       int64                  `protobuf:"varint,1,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShiftRequest) Reset() {
	*x = GetShiftRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShiftRequest) ProtoMessage() {}

func (x *GetShiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShiftRequest.ProtoReflect.Descriptor instead.
func (*GetShiftRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{7}
}

func (x *GetShiftRequest) GetShiftId() int64 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

type GetShiftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shift         *Shift                 `protobuf:"bytes,1,opt,name=shift,proto3" json:"shift,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShiftReply) Reset() {
	*x = GetShiftReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShiftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShiftReply) ProtoMessage() {}

func (x *GetShiftReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShiftReply.ProtoReflect.Descriptor instead.
func (*GetShiftReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{8}
}

func (x *GetShiftReply) GetShift() *Shift {
	if x != nil {
		return x.Shift
	}
	return nil
}

type ListShiftsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	FromId        int64                  `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	StoreId       *int64                 `protobuf:"varint,3,opt,name=store_id,json=storeId,proto3,oneof" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShiftsRequest) Reset() {
	*x = ListShiftsRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShiftsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShiftsRequest) ProtoMessage() {}

func (x *ListShiftsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShiftsRequest.ProtoReflect.Descriptor instead.
func (*ListShiftsRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{9}
}

func (x *ListShiftsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListShiftsRequest) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *ListShiftsRequest) GetStoreId() int64 {
	if x != nil && x.StoreId != nil {
		return *x.StoreId
	}
	return 0
}

type ListShiftsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shifts        []*Shift               `protobuf:"bytes,1,rep,name=shifts,proto3" json:"shifts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShiftsReply) Reset() {
	*x = ListShiftsReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShiftsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShiftsReply) ProtoMessage() {}

func (x *ListShiftsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShiftsReply.ProtoReflect.Descriptor instead.
func (*ListShiftsReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{10}
}

func (x *ListShiftsReply) GetShifts() []*Shift {
	if x != nil {
		return x.Shifts
	}
	return nil
}

type CreateReturnItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaleItemId    int64                  `protobuf:"varint,1,opt,name=sale_item_id,json=saleItemId,proto3" json:"sale_item_id,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReturnItemRequest) Reset() {
	*x = CreateReturnItemRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReturnItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReturnItemRequest) ProtoMessage() {}

func (x *CreateReturnItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReturnItemRequest.ProtoReflect.Descriptor instead.
func (*CreateReturnItemRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{11}
}

func (x *CreateReturnItemRequest) GetSaleItemId() int64 {
	if x != nil {
		return x.SaleItemId
	}
	return 0
}

func (x *CreateReturnItemRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type CreateReturnRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	SaleId        int64                      `protobuf:"varint,1,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	Items         []*CreateReturnItemRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReturnRequest) Reset() {
	*x = CreateReturnRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReturnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReturnRequest) ProtoMessage() {}

func (x *CreateReturnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReturnRequest.ProtoReflect.Descriptor instead.
func (*CreateReturnRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{12}
}

func (x *CreateReturnRequest) GetSaleId() int64 {
	if x != nil {
		return x.SaleId
	}
	return 0
}

func (x *CreateReturnRequest) GetItems() []*CreateReturnItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateReturnReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SaleReturn    *Return                `protobuf:"bytes,1,opt,name=sale_return,json=saleReturn,proto3" json:"sale_return,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReturnReply) Reset() {
	*x = CreateReturnReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReturnReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReturnReply) ProtoMessage() {}

func (x *CreateReturnReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReturnReply.ProtoReflect.Descriptor instead.
func (*CreateReturnReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{13}
}

func (x *CreateReturnReply) GetSaleReturn() *Return {
	if x != nil {
		return x.SaleReturn
	}
	return nil
}

type SyncOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Type          SyncOperationType      `protobuf:"varint,2,opt,name=type,proto3,enum=sales.v1.SyncOperationType" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOperation) Reset() {
	*x = SyncOperation{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOperation) ProtoMessage() {}

func (x *SyncOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOperation.ProtoReflect.Descriptor instead.
func (*SyncOperation) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{14}
}

func (x *SyncOperation) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SyncOperation) GetType() SyncOperationType {
	if x != nil {
		return x.Type
	}
	return SyncOperationType_SALE
}

func (x *SyncOperation) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SyncOperation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type SyncOperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "synced", "already_synced", "error"
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOperationResult) Reset() {
	*x = SyncOperationResult{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOperationResult) ProtoMessage() {}

func (x *SyncOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOperationResult.ProtoReflect.Descriptor instead.
func (*SyncOperationResult) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{15}
}

func (x *SyncOperationResult) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SyncOperationResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SyncOperationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SyncOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*SyncOperation       `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOperationsRequest) Reset() {
	*x = SyncOperationsRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOperationsRequest) ProtoMessage() {}

func (x *SyncOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOperationsRequest.ProtoReflect.Descriptor instead.
func (*SyncOperationsRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{16}
}

func (x *SyncOperationsRequest) GetOperations() []*SyncOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type SyncOperationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SyncOperationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOperationsReply) Reset() {
	*x = SyncOperationsReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOperationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOperationsReply) ProtoMessage() {}

func (x *SyncOperationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOperationsReply.ProtoReflect.Descriptor instead.
func (*SyncOperationsReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{17}
}

func (x *SyncOperationsReply) GetResults() []*SyncOperationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetCashierLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CashierId     int64                  `protobuf:"varint,1,opt,name=cashier_id,json=cashierId,proto3" json:"cashier_id,omitempty"`
	ShiftId       int64                  `protobuf:"varint,2,opt,name=shift_id,json=shiftId,proto3" json:"shift_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	FromId        int64                  `protobuf:"varint,6,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCashierLogRequest) Reset() {
	*x = GetCashierLogRequest{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCashierLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCashierLogRequest) ProtoMessage() {}

func (x *GetCashierLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCashierLogRequest.ProtoReflect.Descriptor instead.
func (*GetCashierLogRequest) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{18}
}

func (x *GetCashierLogRequest) GetCashierId() int64 {
	if x != nil {
		return x.CashierId
	}
	return 0
}

func (x *GetCashierLogRequest) GetShiftId() int64 {
	if x != nil {
		return x.ShiftId
	}
	return 0
}

func (x *GetCashierLogRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetCashierLogRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetCashierLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCashierLogRequest) GetFromId() int64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

type GetCashierLogReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CashierLogEntry     `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCashierLogReply) Reset() {
	*x = GetCashierLogReply{}
	mi := &file_api_sales_v1_sales_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCashierLogReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCashierLogReply) ProtoMessage() {}

func (x *GetCashierLogReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_sales_v1_sales_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCashierLogReply.ProtoReflect.Descriptor instead.
func (*GetCashierLogReply) Descriptor() ([]byte, []int) {
	return file_api_sales_v1_sales_proto_rawDescGZIP(), []int{19}
}

func (x *GetCashierLogReply) GetEntries() []*CashierLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_api_sales_v1_sales_proto protoreflect.FileDescriptor

const file_api_sales_v1_sales_proto_rawDesc = "" +
	"\n" +
	"\x18api/sales/v1/sales.proto\x12\bsales.v1\x1a\x19api/sales/v1/models.proto\"\xb0\x01\n" +
	"\x15CreateSaleItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\tR\tunitPrice\x12\x1a\n" +
	"\bdiscount\x18\x05 \x01(\tR\bdiscount\"\xd4\x01\n" +
	"\x11CreateSaleRequest\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.sales.v1.CreateSaleItemRequestR\x05items\x12!\n" +
	"\fpayment_type\x18\x02 \x01(\tR\vpaymentType\x12\x19\n" +
	"\bshift_id\x18\x03 \x01(\x03R\ashiftId\x12#\n" +
	"\rdiscount_type\x18\x04 \x01(\tR\fdiscountType\x12%\n" +
	"\x0ediscount_value\x18\x05 \x01(\tR\rdiscountValue\"5\n" +
	"\x0fCreateSaleReply\x12\"\n" +
	"\x04sale\x18\x01 \x01(\v2\x0e.sales.v1.SaleR\x04sale\"f\n" +
	"\x10OpenShiftRequest\x12%\n" +
	"\x0eopening_amount\x18\x01 \x01(\tR\ropeningAmount\x12\x1e\n" +
	"\bstore_id\x18\x02 \x01(\x03H\x00R\astoreId\x88\x01\x01B\v\n" +
	"\t_store_id\"7\n" +
	"\x0eOpenShiftReply\x12%\n" +
	"\x05shift\x18\x01 \x01(\v2\x0f.sales.v1.ShiftR\x05shift\".\n" +
	"\x11CloseShiftRequest\x12\x19\n" +
	"\bshift_id\x18\x01 \x01(\x03R\ashiftId\"f\n" +
	"\x0fCloseShiftReply\x12%\n" +
	"\x05shift\x18\x01 \x01(\v2\x0f.sales.v1.ShiftR\x05shift\x12,\n" +
	"\bz_report\x18\x02 \x01(\v2\x11.sales.v1.ZReportR\azReport\",\n" +
	"\x0fGetShiftRequest\x12\x19\n" +
	"\bshift_id\x18\x01 \x01(\x03R\ashiftId\"6\n" +
	"\rGetShiftReply\x12%\n" +
	"\x05shift\x18\x01 \x01(\v2\x0f.sales.v1.ShiftR\x05shift\"o\n" +
	"\x11ListShiftsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x17\n" +
	"\afrom_id\x18\x02 \x01(\x03R\x06fromId\x12\x1e\n" +
	"\bstore_id\x18\x03 \x01(\x03H\x00R\astoreId\x88\x01\x01B\v\n" +
	"\t_store_id\":\n" +
	"\x0fListShiftsReply\x12'\n" +
	"\x06shifts\x18\x01 \x03(\v2\x0f.sales.v1.ShiftR\x06shifts\"W\n" +
	"\x17CreateReturnItemRequest\x12 \n" +
	"\fsale_item_id\x18\x01 \x01(\x03R\n" +
	"saleItemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"g\n" +
	"\x13CreateReturnRequest\x12\x17\n" +
	"\asale_id\x18\x01 \x01(\x03R\x06saleId\x127\n" +
	"\x05items\x18\x02 \x03(\v2!.sales.v1.CreateReturnItemRequestR\x05items\"F\n" +
	"\x11CreateReturnReply\x121\n" +
	"\vsale_return\x18\x01 \x01(\v2\x10.sales.v1.ReturnR\n" +
	"saleReturn\"\x87\x01\n" +
	"\rSyncOperation\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12/\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1b.sales.v1.SyncOperationTypeR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"f\n" +
	"\x13SyncOperationResult\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"P\n" +
	"\x15SyncOperationsRequest\x127\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x17.sales.v1.SyncOperationR\n" +
	"operations\"N\n" +
	"\x13SyncOperationsReply\x127\n" +
	"\aresults\x18\x01 \x03(\v2\x1d.sales.v1.SyncOperationResultR\aresults\"\xb5\x01\n" +
	"\x14GetCashierLogRequest\x12\x1d\n" +
	"\n" +
	"cashier_id\x18\x01 \x01(\x03R\tcashierId\x12\x19\n" +
	"\bshift_id\x18\x02 \x01(\x03R\ashiftId\x12\x1b\n" +
	"\tdate_from\x18\x03 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x04 \x01(\tR\x06dateTo\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x17\n" +
	"\afrom_id\x18\x06 \x01(\x03R\x06fromId\"I\n" +
	"\x12GetCashierLogReply\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.sales.v1.CashierLogEntryR\aentries*)\n" +
	"\x11SyncOperationType\x12\b\n" +
	"\x04SALE\x10\x00\x12\n" +
	"\n" +
	"\x06RETURN\x10\x012T\n" +
	"\fSalesService\x12D\n" +
	"\n" +
	"CreateSale\x12\x1b.sales.v1.CreateSaleRequest\x1a\x19.sales.v1.CreateSaleReply2\x9d\x02\n" +
	"\fShiftService\x12A\n" +
	"\tOpenShift\x12\x1a.sales.v1.OpenShiftRequest\x1a\x18.sales.v1.OpenShiftReply\x12D\n" +
	"\n" +
	"CloseShift\x12\x1b.sales.v1.CloseShiftRequest\x1a\x19.sales.v1.CloseShiftReply\x12>\n" +
	"\bGetShift\x12\x19.sales.v1.GetShiftRequest\x1a\x17.sales.v1.GetShiftReply\x12D\n" +
	"\n" +
	"ListShifts\x12\x1b.sales.v1.ListShiftsRequest\x1a\x19.sales.v1.ListShiftsReply2\\\n" +
	"\x0eReturnsService\x12J\n" +
	"\fCreateReturn\x12\x1d.sales.v1.CreateReturnRequest\x1a\x1b.sales.v1.CreateReturnReply2b\n" +
	"\x11CashierLogService\x12M\n" +
	"\rGetCashierLog\x12\x1e.sales.v1.GetCashierLogRequest\x1a\x1c.sales.v1.GetCashierLogReply2_\n" +
	"\vSyncService\x12P\n" +
	"\x0eSyncOperations\x12\x1f.sales.v1.SyncOperationsRequest\x1a\x1d.sales.v1.SyncOperationsReplyB=Z;github.com/makesalekz/sales/api/sales/v1;sales_v1b\x06proto3"

var (
	file_api_sales_v1_sales_proto_rawDescOnce sync.Once
	file_api_sales_v1_sales_proto_rawDescData []byte
)

func file_api_sales_v1_sales_proto_rawDescGZIP() []byte {
	file_api_sales_v1_sales_proto_rawDescOnce.Do(func() {
		file_api_sales_v1_sales_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sales_v1_sales_proto_rawDesc), len(file_api_sales_v1_sales_proto_rawDesc)))
	})
	return file_api_sales_v1_sales_proto_rawDescData
}

var file_api_sales_v1_sales_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_sales_v1_sales_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_sales_v1_sales_proto_goTypes = []any{
	(SyncOperationType)(0),          // 0: sales.v1.SyncOperationType
	(*CreateSaleItemRequest)(nil),   // 1: sales.v1.CreateSaleItemRequest
	(*CreateSaleRequest)(nil),       // 2: sales.v1.CreateSaleRequest
	(*CreateSaleReply)(nil),         // 3: sales.v1.CreateSaleReply
	(*OpenShiftRequest)(nil),        // 4: sales.v1.OpenShiftRequest
	(*OpenShiftReply)(nil),          // 5: sales.v1.OpenShiftReply
	(*CloseShiftRequest)(nil),       // 6: sales.v1.CloseShiftRequest
	(*CloseShiftReply)(nil),         // 7: sales.v1.CloseShiftReply
	(*GetShiftRequest)(nil),         // 8: sales.v1.GetShiftRequest
	(*GetShiftReply)(nil),           // 9: sales.v1.GetShiftReply
	(*ListShiftsRequest)(nil),       // 10: sales.v1.ListShiftsRequest
	(*ListShiftsReply)(nil),         // 11: sales.v1.ListShiftsReply
	(*CreateReturnItemRequest)(nil), // 12: sales.v1.CreateReturnItemRequest
	(*CreateReturnRequest)(nil),     // 13: sales.v1.CreateReturnRequest
	(*CreateReturnReply)(nil),       // 14: sales.v1.CreateReturnReply
	(*SyncOperation)(nil),           // 15: sales.v1.SyncOperation
	(*SyncOperationResult)(nil),     // 16: sales.v1.SyncOperationResult
	(*SyncOperationsRequest)(nil),   // 17: sales.v1.SyncOperationsRequest
	(*SyncOperationsReply)(nil),     // 18: sales.v1.SyncOperationsReply
	(*GetCashierLogRequest)(nil),    // 19: sales.v1.GetCashierLogRequest
	(*GetCashierLogReply)(nil),      // 20: sales.v1.GetCashierLogReply
	(*Sale)(nil),                    // 21: sales.v1.Sale
	(*Shift)(nil),                   // 22: sales.v1.Shift
	(*ZReport)(nil),                 // 23: sales.v1.ZReport
	(*Return)(nil),                  // 24: sales.v1.Return
	(*CashierLogEntry)(nil),         // 25: sales.v1.CashierLogEntry
}
var file_api_sales_v1_sales_proto_depIdxs = []int32{
	1,  // 0: sales.v1.CreateSaleRequest.items:type_name -> sales.v1.CreateSaleItemRequest
	21, // 1: sales.v1.CreateSaleReply.sale:type_name -> sales.v1.Sale
	22, // 2: sales.v1.OpenShiftReply.shift:type_name -> sales.v1.Shift
	22, // 3: sales.v1.CloseShiftReply.shift:type_name -> sales.v1.Shift
	23, // 4: sales.v1.CloseShiftReply.z_report:type_name -> sales.v1.ZReport
	22, // 5: sales.v1.GetShiftReply.shift:type_name -> sales.v1.Shift
	22, // 6: sales.v1.ListShiftsReply.shifts:type_name -> sales.v1.Shift
	12, // 7: sales.v1.CreateReturnRequest.items:type_name -> sales.v1.CreateReturnItemRequest
	24, // 8: sales.v1.CreateReturnReply.sale_return:type_name -> sales.v1.Return
	0,  // 9: sales.v1.SyncOperation.type:type_name -> sales.v1.SyncOperationType
	15, // 10: sales.v1.SyncOperationsRequest.operations:type_name -> sales.v1.SyncOperation
	16, // 11: sales.v1.SyncOperationsReply.results:type_name -> sales.v1.SyncOperationResult
	25, // 12: sales.v1.GetCashierLogReply.entries:type_name -> sales.v1.CashierLogEntry
	2,  // 13: sales.v1.SalesService.CreateSale:input_type -> sales.v1.CreateSaleRequest
	4,  // 14: sales.v1.ShiftService.OpenShift:input_type -> sales.v1.OpenShiftRequest
	6,  // 15: sales.v1.ShiftService.CloseShift:input_type -> sales.v1.CloseShiftRequest
	8,  // 16: sales.v1.ShiftService.GetShift:input_type -> sales.v1.GetShiftRequest
	10, // 17: sales.v1.ShiftService.ListShifts:input_type -> sales.v1.ListShiftsRequest
	13, // 18: sales.v1.ReturnsService.CreateReturn:input_type -> sales.v1.CreateReturnRequest
	19, // 19: sales.v1.CashierLogService.GetCashierLog:input_type -> sales.v1.GetCashierLogRequest
	17, // 20: sales.v1.SyncService.SyncOperations:input_type -> sales.v1.SyncOperationsRequest
	3,  // 21: sales.v1.SalesService.CreateSale:output_type -> sales.v1.CreateSaleReply
	5,  // 22: sales.v1.ShiftService.OpenShift:output_type -> sales.v1.OpenShiftReply
	7,  // 23: sales.v1.ShiftService.CloseShift:output_type -> sales.v1.CloseShiftReply
	9,  // 24: sales.v1.ShiftService.GetShift:output_type -> sales.v1.GetShiftReply
	11, // 25: sales.v1.ShiftService.ListShifts:output_type -> sales.v1.ListShiftsReply
	14, // 26: sales.v1.ReturnsService.CreateReturn:output_type -> sales.v1.CreateReturnReply
	20, // 27: sales.v1.CashierLogService.GetCashierLog:output_type -> sales.v1.GetCashierLogReply
	18, // 28: sales.v1.SyncService.SyncOperations:output_type -> sales.v1.SyncOperationsReply
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_sales_v1_sales_proto_init() }
func file_api_sales_v1_sales_proto_init() {
	if File_api_sales_v1_sales_proto != nil {
		return
	}
	file_api_sales_v1_models_proto_init()
	file_api_sales_v1_sales_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_sales_v1_sales_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sales_v1_sales_proto_rawDesc), len(file_api_sales_v1_sales_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_api_sales_v1_sales_proto_goTypes,
		DependencyIndexes: file_api_sales_v1_sales_proto_depIdxs,
		EnumInfos:         file_api_sales_v1_sales_proto_enumTypes,
		MessageInfos:      file_api_sales_v1_sales_proto_msgTypes,
	}.Build()
	File_api_sales_v1_sales_proto = out.File
	file_api_sales_v1_sales_proto_goTypes = nil
	file_api_sales_v1_sales_proto_depIdxs = nil
}
