// Code generated by ent, DO NOT EDIT.

package salereturn

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldUpdatedAt, v))
}

// UUID applies equality check predicate on the "uuid" field. It's identical to UUIDEQ.
func UUID(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldUUID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldTenantID, v))
}

// SaleID applies equality check predicate on the "sale_id" field. It's identical to SaleIDEQ.
func SaleID(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldSaleID, v))
}

// CashierID applies equality check predicate on the "cashier_id" field. It's identical to CashierIDEQ.
func CashierID(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldCashierID, v))
}

// Total applies equality check predicate on the "total" field. It's identical to TotalEQ.
func Total(v decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldTotal, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLTE(FieldUpdatedAt, v))
}

// UUIDEQ applies the EQ predicate on the "uuid" field.
func UUIDEQ(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldUUID, v))
}

// UUIDNEQ applies the NEQ predicate on the "uuid" field.
func UUIDNEQ(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldUUID, v))
}

// UUIDIn applies the In predicate on the "uuid" field.
func UUIDIn(vs ...string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldUUID, vs...))
}

// UUIDNotIn applies the NotIn predicate on the "uuid" field.
func UUIDNotIn(vs ...string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldUUID, vs...))
}

// UUIDGT applies the GT predicate on the "uuid" field.
func UUIDGT(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGT(FieldUUID, v))
}

// UUIDGTE applies the GTE predicate on the "uuid" field.
func UUIDGTE(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGTE(FieldUUID, v))
}

// UUIDLT applies the LT predicate on the "uuid" field.
func UUIDLT(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLT(FieldUUID, v))
}

// UUIDLTE applies the LTE predicate on the "uuid" field.
func UUIDLTE(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLTE(FieldUUID, v))
}

// UUIDContains applies the Contains predicate on the "uuid" field.
func UUIDContains(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldContains(FieldUUID, v))
}

// UUIDHasPrefix applies the HasPrefix predicate on the "uuid" field.
func UUIDHasPrefix(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldHasPrefix(FieldUUID, v))
}

// UUIDHasSuffix applies the HasSuffix predicate on the "uuid" field.
func UUIDHasSuffix(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldHasSuffix(FieldUUID, v))
}

// UUIDIsNil applies the IsNil predicate on the "uuid" field.
func UUIDIsNil() predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIsNull(FieldUUID))
}

// UUIDNotNil applies the NotNil predicate on the "uuid" field.
func UUIDNotNil() predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotNull(FieldUUID))
}

// UUIDEqualFold applies the EqualFold predicate on the "uuid" field.
func UUIDEqualFold(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEqualFold(FieldUUID, v))
}

// UUIDContainsFold applies the ContainsFold predicate on the "uuid" field.
func UUIDContainsFold(v string) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldContainsFold(FieldUUID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLTE(FieldTenantID, v))
}

// SaleIDEQ applies the EQ predicate on the "sale_id" field.
func SaleIDEQ(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldSaleID, v))
}

// SaleIDNEQ applies the NEQ predicate on the "sale_id" field.
func SaleIDNEQ(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldSaleID, v))
}

// SaleIDIn applies the In predicate on the "sale_id" field.
func SaleIDIn(vs ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldSaleID, vs...))
}

// SaleIDNotIn applies the NotIn predicate on the "sale_id" field.
func SaleIDNotIn(vs ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldSaleID, vs...))
}

// CashierIDEQ applies the EQ predicate on the "cashier_id" field.
func CashierIDEQ(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldCashierID, v))
}

// CashierIDNEQ applies the NEQ predicate on the "cashier_id" field.
func CashierIDNEQ(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldCashierID, v))
}

// CashierIDIn applies the In predicate on the "cashier_id" field.
func CashierIDIn(vs ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldCashierID, vs...))
}

// CashierIDNotIn applies the NotIn predicate on the "cashier_id" field.
func CashierIDNotIn(vs ...int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldCashierID, vs...))
}

// CashierIDGT applies the GT predicate on the "cashier_id" field.
func CashierIDGT(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGT(FieldCashierID, v))
}

// CashierIDGTE applies the GTE predicate on the "cashier_id" field.
func CashierIDGTE(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGTE(FieldCashierID, v))
}

// CashierIDLT applies the LT predicate on the "cashier_id" field.
func CashierIDLT(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLT(FieldCashierID, v))
}

// CashierIDLTE applies the LTE predicate on the "cashier_id" field.
func CashierIDLTE(v int64) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLTE(FieldCashierID, v))
}

// TotalEQ applies the EQ predicate on the "total" field.
func TotalEQ(v decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldEQ(FieldTotal, v))
}

// TotalNEQ applies the NEQ predicate on the "total" field.
func TotalNEQ(v decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNEQ(FieldTotal, v))
}

// TotalIn applies the In predicate on the "total" field.
func TotalIn(vs ...decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldIn(FieldTotal, vs...))
}

// TotalNotIn applies the NotIn predicate on the "total" field.
func TotalNotIn(vs ...decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldNotIn(FieldTotal, vs...))
}

// TotalGT applies the GT predicate on the "total" field.
func TotalGT(v decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGT(FieldTotal, v))
}

// TotalGTE applies the GTE predicate on the "total" field.
func TotalGTE(v decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldGTE(FieldTotal, v))
}

// TotalLT applies the LT predicate on the "total" field.
func TotalLT(v decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLT(FieldTotal, v))
}

// TotalLTE applies the LTE predicate on the "total" field.
func TotalLTE(v decimal.Decimal) predicate.SaleReturn {
	return predicate.SaleReturn(sql.FieldLTE(FieldTotal, v))
}

// HasSale applies the HasEdge predicate on the "sale" edge.
func HasSale() predicate.SaleReturn {
	return predicate.SaleReturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SaleTable, SaleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSaleWith applies the HasEdge predicate on the "sale" edge with a given conditions (other predicates).
func HasSaleWith(preds ...predicate.Sale) predicate.SaleReturn {
	return predicate.SaleReturn(func(s *sql.Selector) {
		step := newSaleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.SaleReturn {
	return predicate.SaleReturn(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.SaleReturnItem) predicate.SaleReturn {
	return predicate.SaleReturn(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SaleReturn) predicate.SaleReturn {
	return predicate.SaleReturn(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SaleReturn) predicate.SaleReturn {
	return predicate.SaleReturn(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SaleReturn) predicate.SaleReturn {
	return predicate.SaleReturn(sql.NotPredicates(p))
}
