// Code generated by ent, DO NOT EDIT.

package shift

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/sales/ent/enum"
)

const (
	// Label holds the string label denoting the shift type in the database.
	Label = "shift"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCashierID holds the string denoting the cashier_id field in the database.
	FieldCashierID = "cashier_id"
	// FieldStoreID holds the string denoting the store_id field in the database.
	FieldStoreID = "store_id"
	// FieldOpeningAmount holds the string denoting the opening_amount field in the database.
	FieldOpeningAmount = "opening_amount"
	// FieldClosingAmount holds the string denoting the closing_amount field in the database.
	FieldClosingAmount = "closing_amount"
	// FieldTotalSales holds the string denoting the total_sales field in the database.
	FieldTotalSales = "total_sales"
	// FieldTotalReturns holds the string denoting the total_returns field in the database.
	FieldTotalReturns = "total_returns"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldOpenedAt holds the string denoting the opened_at field in the database.
	FieldOpenedAt = "opened_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// Table holds the table name of the shift in the database.
	Table = "shifts"
)

// Columns holds all SQL columns for shift fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldCashierID,
	FieldStoreID,
	FieldOpeningAmount,
	FieldClosingAmount,
	FieldTotalSales,
	FieldTotalReturns,
	FieldStatus,
	FieldOpenedAt,
	FieldClosedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultOpenedAt holds the default value on creation for the "opened_at" field.
	DefaultOpenedAt func() time.Time
)

const DefaultStatus enum.ShiftStatus = "OPEN"

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s enum.ShiftStatus) error {
	switch s {
	case "OPEN", "CLOSED":
		return nil
	default:
		return fmt.Errorf("shift: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Shift queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCashierID orders the results by the cashier_id field.
func ByCashierID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCashierID, opts...).ToFunc()
}

// ByStoreID orders the results by the store_id field.
func ByStoreID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreID, opts...).ToFunc()
}

// ByOpeningAmount orders the results by the opening_amount field.
func ByOpeningAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpeningAmount, opts...).ToFunc()
}

// ByClosingAmount orders the results by the closing_amount field.
func ByClosingAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosingAmount, opts...).ToFunc()
}

// ByTotalSales orders the results by the total_sales field.
func ByTotalSales(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalSales, opts...).ToFunc()
}

// ByTotalReturns orders the results by the total_returns field.
func ByTotalReturns(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalReturns, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByOpenedAt orders the results by the opened_at field.
func ByOpenedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenedAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}
