// Code generated by ent, DO NOT EDIT.

package shift

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/sales/ent/enum"
	"gitlab.calendaria.team/services/sales/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldTenantID, v))
}

// CashierID applies equality check predicate on the "cashier_id" field. It's identical to CashierIDEQ.
func CashierID(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldCashierID, v))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldStoreID, v))
}

// OpeningAmount applies equality check predicate on the "opening_amount" field. It's identical to OpeningAmountEQ.
func OpeningAmount(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldOpeningAmount, v))
}

// ClosingAmount applies equality check predicate on the "closing_amount" field. It's identical to ClosingAmountEQ.
func ClosingAmount(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldClosingAmount, v))
}

// TotalSales applies equality check predicate on the "total_sales" field. It's identical to TotalSalesEQ.
func TotalSales(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldTotalSales, v))
}

// TotalReturns applies equality check predicate on the "total_returns" field. It's identical to TotalReturnsEQ.
func TotalReturns(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldTotalReturns, v))
}

// OpenedAt applies equality check predicate on the "opened_at" field. It's identical to OpenedAtEQ.
func OpenedAt(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldOpenedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldTenantID, v))
}

// CashierIDEQ applies the EQ predicate on the "cashier_id" field.
func CashierIDEQ(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldCashierID, v))
}

// CashierIDNEQ applies the NEQ predicate on the "cashier_id" field.
func CashierIDNEQ(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldCashierID, v))
}

// CashierIDIn applies the In predicate on the "cashier_id" field.
func CashierIDIn(vs ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldCashierID, vs...))
}

// CashierIDNotIn applies the NotIn predicate on the "cashier_id" field.
func CashierIDNotIn(vs ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldCashierID, vs...))
}

// CashierIDGT applies the GT predicate on the "cashier_id" field.
func CashierIDGT(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldCashierID, v))
}

// CashierIDGTE applies the GTE predicate on the "cashier_id" field.
func CashierIDGTE(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldCashierID, v))
}

// CashierIDLT applies the LT predicate on the "cashier_id" field.
func CashierIDLT(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldCashierID, v))
}

// CashierIDLTE applies the LTE predicate on the "cashier_id" field.
func CashierIDLTE(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldCashierID, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...int64) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldStoreID, vs...))
}

// StoreIDGT applies the GT predicate on the "store_id" field.
func StoreIDGT(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldStoreID, v))
}

// StoreIDGTE applies the GTE predicate on the "store_id" field.
func StoreIDGTE(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldStoreID, v))
}

// StoreIDLT applies the LT predicate on the "store_id" field.
func StoreIDLT(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldStoreID, v))
}

// StoreIDLTE applies the LTE predicate on the "store_id" field.
func StoreIDLTE(v int64) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldStoreID, v))
}

// StoreIDIsNil applies the IsNil predicate on the "store_id" field.
func StoreIDIsNil() predicate.Shift {
	return predicate.Shift(sql.FieldIsNull(FieldStoreID))
}

// StoreIDNotNil applies the NotNil predicate on the "store_id" field.
func StoreIDNotNil() predicate.Shift {
	return predicate.Shift(sql.FieldNotNull(FieldStoreID))
}

// OpeningAmountEQ applies the EQ predicate on the "opening_amount" field.
func OpeningAmountEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldOpeningAmount, v))
}

// OpeningAmountNEQ applies the NEQ predicate on the "opening_amount" field.
func OpeningAmountNEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldOpeningAmount, v))
}

// OpeningAmountIn applies the In predicate on the "opening_amount" field.
func OpeningAmountIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldOpeningAmount, vs...))
}

// OpeningAmountNotIn applies the NotIn predicate on the "opening_amount" field.
func OpeningAmountNotIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldOpeningAmount, vs...))
}

// OpeningAmountGT applies the GT predicate on the "opening_amount" field.
func OpeningAmountGT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldOpeningAmount, v))
}

// OpeningAmountGTE applies the GTE predicate on the "opening_amount" field.
func OpeningAmountGTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldOpeningAmount, v))
}

// OpeningAmountLT applies the LT predicate on the "opening_amount" field.
func OpeningAmountLT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldOpeningAmount, v))
}

// OpeningAmountLTE applies the LTE predicate on the "opening_amount" field.
func OpeningAmountLTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldOpeningAmount, v))
}

// ClosingAmountEQ applies the EQ predicate on the "closing_amount" field.
func ClosingAmountEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldClosingAmount, v))
}

// ClosingAmountNEQ applies the NEQ predicate on the "closing_amount" field.
func ClosingAmountNEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldClosingAmount, v))
}

// ClosingAmountIn applies the In predicate on the "closing_amount" field.
func ClosingAmountIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldClosingAmount, vs...))
}

// ClosingAmountNotIn applies the NotIn predicate on the "closing_amount" field.
func ClosingAmountNotIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldClosingAmount, vs...))
}

// ClosingAmountGT applies the GT predicate on the "closing_amount" field.
func ClosingAmountGT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldClosingAmount, v))
}

// ClosingAmountGTE applies the GTE predicate on the "closing_amount" field.
func ClosingAmountGTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldClosingAmount, v))
}

// ClosingAmountLT applies the LT predicate on the "closing_amount" field.
func ClosingAmountLT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldClosingAmount, v))
}

// ClosingAmountLTE applies the LTE predicate on the "closing_amount" field.
func ClosingAmountLTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldClosingAmount, v))
}

// ClosingAmountIsNil applies the IsNil predicate on the "closing_amount" field.
func ClosingAmountIsNil() predicate.Shift {
	return predicate.Shift(sql.FieldIsNull(FieldClosingAmount))
}

// ClosingAmountNotNil applies the NotNil predicate on the "closing_amount" field.
func ClosingAmountNotNil() predicate.Shift {
	return predicate.Shift(sql.FieldNotNull(FieldClosingAmount))
}

// TotalSalesEQ applies the EQ predicate on the "total_sales" field.
func TotalSalesEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldTotalSales, v))
}

// TotalSalesNEQ applies the NEQ predicate on the "total_sales" field.
func TotalSalesNEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldTotalSales, v))
}

// TotalSalesIn applies the In predicate on the "total_sales" field.
func TotalSalesIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldTotalSales, vs...))
}

// TotalSalesNotIn applies the NotIn predicate on the "total_sales" field.
func TotalSalesNotIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldTotalSales, vs...))
}

// TotalSalesGT applies the GT predicate on the "total_sales" field.
func TotalSalesGT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldTotalSales, v))
}

// TotalSalesGTE applies the GTE predicate on the "total_sales" field.
func TotalSalesGTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldTotalSales, v))
}

// TotalSalesLT applies the LT predicate on the "total_sales" field.
func TotalSalesLT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldTotalSales, v))
}

// TotalSalesLTE applies the LTE predicate on the "total_sales" field.
func TotalSalesLTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldTotalSales, v))
}

// TotalSalesIsNil applies the IsNil predicate on the "total_sales" field.
func TotalSalesIsNil() predicate.Shift {
	return predicate.Shift(sql.FieldIsNull(FieldTotalSales))
}

// TotalSalesNotNil applies the NotNil predicate on the "total_sales" field.
func TotalSalesNotNil() predicate.Shift {
	return predicate.Shift(sql.FieldNotNull(FieldTotalSales))
}

// TotalReturnsEQ applies the EQ predicate on the "total_returns" field.
func TotalReturnsEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldTotalReturns, v))
}

// TotalReturnsNEQ applies the NEQ predicate on the "total_returns" field.
func TotalReturnsNEQ(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldTotalReturns, v))
}

// TotalReturnsIn applies the In predicate on the "total_returns" field.
func TotalReturnsIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldTotalReturns, vs...))
}

// TotalReturnsNotIn applies the NotIn predicate on the "total_returns" field.
func TotalReturnsNotIn(vs ...decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldTotalReturns, vs...))
}

// TotalReturnsGT applies the GT predicate on the "total_returns" field.
func TotalReturnsGT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldTotalReturns, v))
}

// TotalReturnsGTE applies the GTE predicate on the "total_returns" field.
func TotalReturnsGTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldTotalReturns, v))
}

// TotalReturnsLT applies the LT predicate on the "total_returns" field.
func TotalReturnsLT(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldTotalReturns, v))
}

// TotalReturnsLTE applies the LTE predicate on the "total_returns" field.
func TotalReturnsLTE(v decimal.Decimal) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldTotalReturns, v))
}

// TotalReturnsIsNil applies the IsNil predicate on the "total_returns" field.
func TotalReturnsIsNil() predicate.Shift {
	return predicate.Shift(sql.FieldIsNull(FieldTotalReturns))
}

// TotalReturnsNotNil applies the NotNil predicate on the "total_returns" field.
func TotalReturnsNotNil() predicate.Shift {
	return predicate.Shift(sql.FieldNotNull(FieldTotalReturns))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v enum.ShiftStatus) predicate.Shift {
	vc := v
	return predicate.Shift(sql.FieldEQ(FieldStatus, vc))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v enum.ShiftStatus) predicate.Shift {
	vc := v
	return predicate.Shift(sql.FieldNEQ(FieldStatus, vc))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...enum.ShiftStatus) predicate.Shift {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Shift(sql.FieldIn(FieldStatus, v...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...enum.ShiftStatus) predicate.Shift {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Shift(sql.FieldNotIn(FieldStatus, v...))
}

// OpenedAtEQ applies the EQ predicate on the "opened_at" field.
func OpenedAtEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldOpenedAt, v))
}

// OpenedAtNEQ applies the NEQ predicate on the "opened_at" field.
func OpenedAtNEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldOpenedAt, v))
}

// OpenedAtIn applies the In predicate on the "opened_at" field.
func OpenedAtIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldOpenedAt, vs...))
}

// OpenedAtNotIn applies the NotIn predicate on the "opened_at" field.
func OpenedAtNotIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldOpenedAt, vs...))
}

// OpenedAtGT applies the GT predicate on the "opened_at" field.
func OpenedAtGT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldOpenedAt, v))
}

// OpenedAtGTE applies the GTE predicate on the "opened_at" field.
func OpenedAtGTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldOpenedAt, v))
}

// OpenedAtLT applies the LT predicate on the "opened_at" field.
func OpenedAtLT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldOpenedAt, v))
}

// OpenedAtLTE applies the LTE predicate on the "opened_at" field.
func OpenedAtLTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldOpenedAt, v))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.Shift {
	return predicate.Shift(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.Shift {
	return predicate.Shift(sql.FieldNotNull(FieldClosedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Shift) predicate.Shift {
	return predicate.Shift(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Shift) predicate.Shift {
	return predicate.Shift(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Shift) predicate.Shift {
	return predicate.Shift(sql.NotPredicates(p))
}
