// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CashierLog is the predicate function for cashierlog builders.
type CashierLog func(*sql.Selector)

// Sale is the predicate function for sale builders.
type Sale func(*sql.Selector)

// SaleItem is the predicate function for saleitem builders.
type SaleItem func(*sql.Selector)

// SaleReturn is the predicate function for salereturn builders.
type SaleReturn func(*sql.Selector)

// SaleReturnItem is the predicate function for salereturnitem builders.
type SaleReturnItem func(*sql.Selector)

// Shift is the predicate function for shift builders.
type Shift func(*sql.Selector)
